// Code generated by abstraction-idl from abstraction-config/config.thrift. DO NOT EDIT.

#pragma once

#include <cstddef>
#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

namespace abstraction::config {

using Raw = std::string;

class Refusal : public std::runtime_error {
public:
    Refusal(const char* word, std::size_t offset)
        : std::runtime_error(std::string("refused: ") + word + " at byte " + std::to_string(offset)),
          word(word),
          offset(offset) {}
    const char* word;
    std::size_t offset;
};

enum class UserReplaceOutcome : std::int32_t {
    Applied = 1,
    Conflict = 2,
    Forbidden = 3,
    Unavailable = 4,
};

// The member's name on the wire; empty for a value that names no member.
inline constexpr std::string_view wire_name(UserReplaceOutcome value) {
    switch (value) {
        case UserReplaceOutcome::Applied: return "applied";
        case UserReplaceOutcome::Conflict: return "conflict";
        case UserReplaceOutcome::Forbidden: return "forbidden";
        case UserReplaceOutcome::Unavailable: return "unavailable";
    }
    return {};
}

// The member a wire name spells; empty for a name this vocabulary refuses.
inline std::optional<UserReplaceOutcome> parse_user_replace_outcome(std::string_view name) {
    if (name == "applied") return UserReplaceOutcome::Applied;
    if (name == "conflict") return UserReplaceOutcome::Conflict;
    if (name == "forbidden") return UserReplaceOutcome::Forbidden;
    if (name == "unavailable") return UserReplaceOutcome::Unavailable;
    return std::nullopt;
}

// A member equals its wire name, so code holding the contract's word compares directly.
inline constexpr bool operator==(UserReplaceOutcome value, std::string_view name) { return wire_name(value) == name; }
inline constexpr bool operator!=(UserReplaceOutcome value, std::string_view name) { return wire_name(value) != name; }
inline constexpr bool operator==(std::string_view name, UserReplaceOutcome value) { return wire_name(value) == name; }
inline constexpr bool operator!=(std::string_view name, UserReplaceOutcome value) { return wire_name(value) != name; }

inline const std::vector<std::string> kUserReplaceOutcomeNames = {"applied", "conflict", "forbidden", "unavailable"};

enum class ConfigObservationOutcome : std::int32_t {
    Snapshot = 1,
    Unchanged = 2,
    Gap = 3,
    Unavailable = 4,
    Unsupported = 5,
    Invalid = 6,
};

// The member's name on the wire; empty for a value that names no member.
inline constexpr std::string_view wire_name(ConfigObservationOutcome value) {
    switch (value) {
        case ConfigObservationOutcome::Snapshot: return "snapshot";
        case ConfigObservationOutcome::Unchanged: return "unchanged";
        case ConfigObservationOutcome::Gap: return "gap";
        case ConfigObservationOutcome::Unavailable: return "unavailable";
        case ConfigObservationOutcome::Unsupported: return "unsupported";
        case ConfigObservationOutcome::Invalid: return "invalid";
    }
    return {};
}

// The member a wire name spells; empty for a name this vocabulary refuses.
inline std::optional<ConfigObservationOutcome> parse_config_observation_outcome(std::string_view name) {
    if (name == "snapshot") return ConfigObservationOutcome::Snapshot;
    if (name == "unchanged") return ConfigObservationOutcome::Unchanged;
    if (name == "gap") return ConfigObservationOutcome::Gap;
    if (name == "unavailable") return ConfigObservationOutcome::Unavailable;
    if (name == "unsupported") return ConfigObservationOutcome::Unsupported;
    if (name == "invalid") return ConfigObservationOutcome::Invalid;
    return std::nullopt;
}

// A member equals its wire name, so code holding the contract's word compares directly.
inline constexpr bool operator==(ConfigObservationOutcome value, std::string_view name) { return wire_name(value) == name; }
inline constexpr bool operator!=(ConfigObservationOutcome value, std::string_view name) { return wire_name(value) != name; }
inline constexpr bool operator==(std::string_view name, ConfigObservationOutcome value) { return wire_name(value) == name; }
inline constexpr bool operator!=(std::string_view name, ConfigObservationOutcome value) { return wire_name(value) != name; }

inline const std::vector<std::string> kConfigObservationOutcomeNames = {"snapshot", "unchanged", "gap", "unavailable", "unsupported", "invalid"};

inline const std::vector<std::string> kServiceErrorCodeNames = {"handler_error", "invalid_result", "unknown_version", "unknown_service", "unknown_method", "wrong_mode", "storage_unavailable", "caller_unavailable", "identity_required", "wrong_user", "invalid_revision"};
inline constexpr std::string_view kServiceErrorCodeHandlerError = "handler_error";
inline constexpr std::string_view kServiceErrorCodeInvalidResult = "invalid_result";
inline constexpr std::string_view kServiceErrorCodeUnknownVersion = "unknown_version";
inline constexpr std::string_view kServiceErrorCodeUnknownService = "unknown_service";
inline constexpr std::string_view kServiceErrorCodeUnknownMethod = "unknown_method";
inline constexpr std::string_view kServiceErrorCodeWrongMode = "wrong_mode";
inline constexpr std::string_view kServiceErrorCodeStorageUnavailable = "storage_unavailable";
inline constexpr std::string_view kServiceErrorCodeCallerUnavailable = "caller_unavailable";
inline constexpr std::string_view kServiceErrorCodeIdentityRequired = "identity_required";
inline constexpr std::string_view kServiceErrorCodeWrongUser = "wrong_user";
inline constexpr std::string_view kServiceErrorCodeInvalidRevision = "invalid_revision";

inline const std::vector<std::string> kReaderErrorCodes = {"storage_unavailable", "caller_unavailable", "identity_required", "wrong_user"};

inline const std::vector<std::string> kEditorErrorCodes = {"invalid_revision", "storage_unavailable", "caller_unavailable", "identity_required", "wrong_user"};

// Existing per-run overrides. Empty strings do not override file values.
struct RunOverrides {
    std::string nas_store;
    std::string store;
    std::string log_sink;
    std::string log_service;
};

// Per-key provenance: machine/user file path, or environment/default with empty
// path.
struct Origin {
    std::string rung;
    std::string path;
};

// Provenance for every configuration key, including default answers.
struct Origins {
    Origin nas_store;
    Origin store;
    Origin log_sink;
    Origin log_service;
    Origin off;
};

// Existing provider values and provenance. Empty values mean absence. Stamp
// follows values rather than provenance; paths are diagnostic configuration
// data, not permission to access a store.
struct Snapshot {
    std::string nas_store;
    std::string store;
    std::string log_sink;
    std::string log_service;
    std::map<std::string, std::string> off;
    Origins origins;
    std::string stamp;
};

// User-rung overrides only. Empty values clear overrides; machine and run
// values never enter this record. The configuration backing-file path is
// selected by the service; path-valued settings grant no provider storage
// authority.
struct UserSettings {
    std::string nas_store;
    std::string store;
    std::string log_sink;
    std::string log_service;
    std::map<std::string, std::string> off;
};

// Normalized user-rung content and an opaque content revision. A missing file
// yields empty values; unreadable or unsupported storage is refused. Revision
// may recur when identical content is restored.
struct UserSnapshot {
    UserSettings values;
    std::string revision;
};

// Applied returns the written snapshot. Conflict performs no write and returns
// the current snapshot. Forbidden reports an evaluated edit-policy refusal;
// unavailable reports that the edit-policy decision could not be obtained and
// may be retried. Both perform no storage access and carry empty values with an
// empty revision. No outcome merges settings implicitly.
struct UserReplaceResult {
    UserReplaceOutcome outcome{};
    UserSnapshot snapshot;
};

// Latest effective configuration, with an opaque cursor bound to provider
// instance and explicit run overrides. snapshot carries a snapshot and new
// cursor; unchanged carries the original cursor and no snapshot. Other outcomes
// carry no snapshot and preserve the supplied cursor. Intermediate revisions
// may be coalesced; this is not an event history. A restarted provider or
// changed override binding gives gap and requires an explicit empty-cursor
// restart.
struct ConfigObservation {
    ConfigObservationOutcome outcome{};
    std::string cursor;
    std::optional<Snapshot> snapshot;
};

// Codec machinery. Nothing here is API; it may change in any release.
namespace detail {

inline void esc(std::string& out, const std::string& s);

inline void esc_byte(std::string& out, unsigned char c) {
    static const char* kHex = "0123456789abcdef";
    switch (c) {
        case '"': out += "\\\""; return;
        case '\\': out += "\\\\"; return;
        case 0x08: out += "\\b"; return;
        case 0x0c: out += "\\f"; return;
        case '\n': out += "\\n"; return;
        case '\r': out += "\\r"; return;
        case '\t': out += "\\t"; return;
        default: break;
    }
    if (c < 0x20) {
        out += "\\u00";
        out += kHex[c >> 4];
        out += kHex[c & 0x0F];
    } else {
        out += static_cast<char>(c);
    }
}

inline void num(std::string& out, std::int64_t n) { out += std::to_string(n); }

inline void pad(std::string& out, int depth) {
    out.append(static_cast<std::size_t>(depth) * 2, ' ');
}

inline void strs(std::string& out, const std::vector<std::string>& v, int depth) {
    if (v.empty()) { out += "[]"; return; }
    out += "[\n";
    for (std::size_t i = 0; i < v.size(); ++i) {
        pad(out, depth + 1);
        esc(out, v[i]);
        if (i + 1 < v.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += ']';
}



inline bool ws(unsigned char c) { return c == ' ' || c == '\t' || c == '\n' || c == '\r'; }

inline void raw(std::string& out, const std::string& s, int depth) {
    const std::size_t n = s.size();
    for (std::size_t i = 0; i < n;) {
        const unsigned char c = static_cast<unsigned char>(s[i]);
        if (ws(c)) {
            ++i;
        } else if (c == '"') {
            std::size_t j = i + 1;
            while (j < n) {
                if (s[j] == '\\') { j += 2; continue; }
                if (s[j] == '"') { ++j; break; }
                ++j;
            }
            out.append(s, i, j - i);
            i = j;
        } else if (c == '{' || c == '[') {
            out += static_cast<char>(c);
            ++i;
            std::size_t j = i;
            while (j < n && ws(static_cast<unsigned char>(s[j]))) ++j;
            if (j < n && (s[j] == '}' || s[j] == ']')) {
                out += s[j];
                i = j + 1;
            } else {
                ++depth;
                out += '\n';
                pad(out, depth);
            }
        } else if (c == '}' || c == ']') {
            --depth;
            out += '\n';
            pad(out, depth);
            out += static_cast<char>(c);
            ++i;
        } else if (c == ',') {
            out += ",\n";
            pad(out, depth);
            ++i;
        } else if (c == ':') {
            out += ": ";
            ++i;
        } else {
            out += static_cast<char>(c);
            ++i;
        }
    }
}

// std::char_traits<char>::compare is specified to order by unsigned char, so a
// std::map<std::string, ...> already walks its keys in UTF-8 byte order — which
// is what the definition declares. Nothing sorts here because nothing needs to.
inline void rawmap(std::string& out, const std::map<std::string, Raw>& m, int depth) {
    if (m.empty()) { out += "{}"; return; }
    out += "{\n";
    std::size_t i = 0;
    for (const auto& kv : m) {
        pad(out, depth + 1);
        esc(out, kv.first);
        out += ": ";
        raw(out, kv.second, depth + 1);
        if (++i < m.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += '}';
}

inline void esc(std::string& out, const std::string& s) {
    out += '"';
    for (unsigned char c : s) esc_byte(out, c);
    out += '"';
}

inline void strmap(std::string& out, const std::map<std::string, std::string>& m, int depth) {
    if (m.empty()) { out += "{}"; return; }
    out += "{\n";
    std::size_t i = 0;
    for (const auto& kv : m) {
        pad(out, depth + 1);
        esc(out, kv.first);
        out += ": ";
        esc(out, kv.second);
        if (++i < m.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += '}';
}

struct OAConfigReaderReadArguments {
    RunOverrides overrides;
};

struct OAConfigEditorReadUserArguments {
};

struct OAConfigEditorReplaceUserArguments {
    std::string expected_revision;
    UserSettings values;
};

struct OAConfigObserverObserveArguments {
    RunOverrides overrides;
    std::string cursor;
    std::int64_t wait_ms = 0;
};

struct OAServiceFrame {
    std::int32_t version = 0;
    std::string service;
    std::string method;
    Raw arguments;
};

struct OAServiceReply {
    std::int32_t version = 0;
    std::string service;
    std::string method;
    bool ok = false;
    Raw payload;
};

struct OAServiceError {
    std::string code;
    std::string message;
};

struct OAConfigReaderReadResult {
    Snapshot value;
};

struct OAConfigEditorReadUserResult {
    UserSnapshot value;
};

struct OAConfigEditorReplaceUserResult {
    UserReplaceResult value;
};

struct OAConfigObserverObserveResult {
    ConfigObservation value;
};
inline void enc_run_overrides(std::string&, const RunOverrides&, int);
inline void enc_origin(std::string&, const Origin&, int);
inline void enc_origins(std::string&, const Origins&, int);
inline void enc_snapshot(std::string&, const Snapshot&, int);
inline void enc_user_settings(std::string&, const UserSettings&, int);
inline void enc_user_snapshot(std::string&, const UserSnapshot&, int);
inline void enc_user_replace_result(std::string&, const UserReplaceResult&, int);
inline void enc_config_observation(std::string&, const ConfigObservation&, int);
inline void enc_oa_config_reader_read_arguments(std::string&, const OAConfigReaderReadArguments&, int);
inline void enc_oa_config_editor_read_user_arguments(std::string&, const OAConfigEditorReadUserArguments&, int);
inline void enc_oa_config_editor_replace_user_arguments(std::string&, const OAConfigEditorReplaceUserArguments&, int);
inline void enc_oa_config_observer_observe_arguments(std::string&, const OAConfigObserverObserveArguments&, int);
inline void enc_oa_service_frame(std::string&, const OAServiceFrame&, int);
inline void enc_oa_service_reply(std::string&, const OAServiceReply&, int);
inline void enc_oa_service_error(std::string&, const OAServiceError&, int);
inline void enc_oa_config_reader_read_result(std::string&, const OAConfigReaderReadResult&, int);
inline void enc_oa_config_editor_read_user_result(std::string&, const OAConfigEditorReadUserResult&, int);
inline void enc_oa_config_editor_replace_user_result(std::string&, const OAConfigEditorReplaceUserResult&, int);
inline void enc_oa_config_observer_observe_result(std::string&, const OAConfigObserverObserveResult&, int);

inline void enc_run_overrides(std::string& out, const RunOverrides& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "nas_store");
    out += ": ";
    esc(out, v.nas_store);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "store");
    out += ": ";
    esc(out, v.store);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "log_sink");
    out += ": ";
    esc(out, v.log_sink);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "log_service");
    out += ": ";
    esc(out, v.log_service);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_origin(std::string& out, const Origin& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "rung");
    out += ": ";
    esc(out, v.rung);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "path");
    out += ": ";
    esc(out, v.path);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_origins(std::string& out, const Origins& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "nas_store");
    out += ": ";
    enc_origin(out, v.nas_store, depth + 1);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "store");
    out += ": ";
    enc_origin(out, v.store, depth + 1);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "log_sink");
    out += ": ";
    enc_origin(out, v.log_sink, depth + 1);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "log_service");
    out += ": ";
    enc_origin(out, v.log_service, depth + 1);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "off");
    out += ": ";
    enc_origin(out, v.off, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_snapshot(std::string& out, const Snapshot& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "nas_store");
    out += ": ";
    esc(out, v.nas_store);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "store");
    out += ": ";
    esc(out, v.store);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "log_sink");
    out += ": ";
    esc(out, v.log_sink);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "log_service");
    out += ": ";
    esc(out, v.log_service);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "off");
    out += ": ";
    strmap(out, v.off, depth + 1);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "origins");
    out += ": ";
    enc_origins(out, v.origins, depth + 1);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "stamp");
    out += ": ";
    esc(out, v.stamp);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_user_settings(std::string& out, const UserSettings& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "nas_store");
    out += ": ";
    esc(out, v.nas_store);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "store");
    out += ": ";
    esc(out, v.store);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "log_sink");
    out += ": ";
    esc(out, v.log_sink);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "log_service");
    out += ": ";
    esc(out, v.log_service);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "off");
    out += ": ";
    strmap(out, v.off, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_user_snapshot(std::string& out, const UserSnapshot& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "values");
    out += ": ";
    enc_user_settings(out, v.values, depth + 1);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "revision");
    out += ": ";
    esc(out, v.revision);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_user_replace_result(std::string& out, const UserReplaceResult& v, int depth) {
    if (wire_name(v.outcome).empty()) throw Refusal("bad_enum", 0);
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "outcome");
    out += ": ";
    esc(out, std::string(wire_name(v.outcome)));
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "snapshot");
    out += ": ";
    enc_user_snapshot(out, v.snapshot, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_config_observation(std::string& out, const ConfigObservation& v, int depth) {
    if (wire_name(v.outcome).empty()) throw Refusal("bad_enum", 0);
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "outcome");
    out += ": ";
    esc(out, std::string(wire_name(v.outcome)));
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "cursor");
    out += ": ";
    esc(out, v.cursor);
    if (v.snapshot.has_value()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "snapshot");
        out += ": ";
        enc_snapshot(out, *v.snapshot, depth + 1);
    }
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oa_config_reader_read_arguments(std::string& out, const OAConfigReaderReadArguments& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "overrides");
    out += ": ";
    enc_run_overrides(out, v.overrides, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oa_config_editor_read_user_arguments(std::string& out, const OAConfigEditorReadUserArguments& v, int depth) {
    out += '{';
    out += '}';
}

inline void enc_oa_config_editor_replace_user_arguments(std::string& out, const OAConfigEditorReplaceUserArguments& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "expected_revision");
    out += ": ";
    esc(out, v.expected_revision);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "values");
    out += ": ";
    enc_user_settings(out, v.values, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oa_config_observer_observe_arguments(std::string& out, const OAConfigObserverObserveArguments& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "overrides");
    out += ": ";
    enc_run_overrides(out, v.overrides, depth + 1);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "cursor");
    out += ": ";
    esc(out, v.cursor);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "wait_ms");
    out += ": ";
    num(out, v.wait_ms);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oa_service_frame(std::string& out, const OAServiceFrame& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "version");
    out += ": ";
    num(out, v.version);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "service");
    out += ": ";
    esc(out, v.service);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "method");
    out += ": ";
    esc(out, v.method);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "arguments");
    out += ": ";
    out += v.arguments;
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oa_service_reply(std::string& out, const OAServiceReply& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "version");
    out += ": ";
    num(out, v.version);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "service");
    out += ": ";
    esc(out, v.service);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "method");
    out += ": ";
    esc(out, v.method);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "ok");
    out += ": ";
    out += v.ok ? "true" : "false";
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "payload");
    out += ": ";
    out += v.payload;
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oa_service_error(std::string& out, const OAServiceError& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "code");
    out += ": ";
    esc(out, v.code);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "message");
    out += ": ";
    esc(out, v.message);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oa_config_reader_read_result(std::string& out, const OAConfigReaderReadResult& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "value");
    out += ": ";
    enc_snapshot(out, v.value, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oa_config_editor_read_user_result(std::string& out, const OAConfigEditorReadUserResult& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "value");
    out += ": ";
    enc_user_snapshot(out, v.value, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oa_config_editor_replace_user_result(std::string& out, const OAConfigEditorReplaceUserResult& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "value");
    out += ": ";
    enc_user_replace_result(out, v.value, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oa_config_observer_observe_result(std::string& out, const OAConfigObserverObserveResult& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "value");
    out += ": ";
    enc_config_observation(out, v.value, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline constexpr int kDepthLimit = 64;
inline constexpr std::size_t kI64Digits = 19;

inline void append_rune(std::string& out, std::uint32_t cp) {
    if (cp < 0x80) {
        out += static_cast<char>(cp);
    } else if (cp < 0x800) {
        out += static_cast<char>(0xC0 | (cp >> 6));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    } else if (cp < 0x10000) {
        out += static_cast<char>(0xE0 | (cp >> 12));
        out += static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    } else {
        out += static_cast<char>(0xF0 | (cp >> 18));
        out += static_cast<char>(0x80 | ((cp >> 12) & 0x3F));
        out += static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    }
}

inline bool valid_utf8(const std::string& b) {
    for (std::size_t i = 0; i < b.size();) {
        const unsigned char c = static_cast<unsigned char>(b[i]);
        if (c < 0x80) { ++i; continue; }
        std::size_t n = 0;
        std::uint32_t cp = 0;
        if ((c >> 5) == 0x6) { n = 2; cp = c & 0x1Fu; }
        else if ((c >> 4) == 0xE) { n = 3; cp = c & 0x0Fu; }
        else if ((c >> 3) == 0x1E) { n = 4; cp = c & 0x07u; }
        else return false;
        if (i + n > b.size()) return false;
        for (std::size_t k = 1; k < n; ++k) {
            const unsigned char t = static_cast<unsigned char>(b[i + k]);
            if ((t >> 6) != 0x2) return false;
            cp = cp << 6 | (t & 0x3Fu);
        }
        static const std::uint32_t kLowest[5] = {0, 0, 0x80, 0x800, 0x10000};
        if (cp < kLowest[n] || cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF)) return false;
        i += n;
    }
    return true;
}

struct Reader {
    std::string_view buf;
    std::size_t pos = 0;
    int depth = 0;

    [[noreturn]] void refuse(const char* word) const { throw Refusal(word, pos); }

    unsigned char at() const {
        return pos < buf.size() ? static_cast<unsigned char>(buf[pos]) : 0;
    }

    bool digit() const { return at() >= '0' && at() <= '9'; }

    void skip_ws() {
        while (pos < buf.size() && ws(static_cast<unsigned char>(buf[pos]))) ++pos;
    }

    void enter() {
        if (++depth > kDepthLimit) refuse("depth_exceeded");
    }

    std::string str() {
        if (at() != '"') refuse("wrong_type");
        ++pos;
        std::string out;
        for (;;) {
            if (pos >= buf.size()) refuse("malformed");
            const unsigned char c = static_cast<unsigned char>(buf[pos]);
            if (c == '"') {
                ++pos;
                if (!valid_utf8(out)) refuse("bad_string");
                return out;
            }
            if (c < 0x20) refuse("bad_string");
            if (c == '\\') {
                escape(out);
            } else {
                out += static_cast<char>(c);
                ++pos;
            }
        }
    }

    void escape(std::string& out) {
        ++pos;
        if (pos >= buf.size()) refuse("malformed");
        const unsigned char c = static_cast<unsigned char>(buf[pos]);
        ++pos;
        switch (c) {
            case '"': case '\\': case '/': out += static_cast<char>(c); return;
            case 'b': out += static_cast<char>(0x08); return;
            case 'f': out += static_cast<char>(0x0c); return;
            case 'n': out += '\n'; return;
            case 'r': out += '\r'; return;
            case 't': out += '\t'; return;
            case 'u': break;
            default: refuse("bad_string");
        }
        std::uint32_t u = hex4();
        if (u >= 0xDC00 && u <= 0xDFFF) refuse("bad_string");
        if (u >= 0xD800 && u <= 0xDBFF) {
            if (pos + 1 >= buf.size() || buf[pos] != '\\' || buf[pos + 1] != 'u') refuse("bad_string");
            pos += 2;
            const std::uint32_t low = hex4();
            if (low < 0xDC00 || low > 0xDFFF) refuse("bad_string");
            u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00);
        }
        append_rune(out, u);
    }

    std::uint32_t hex4() {
        if (pos + 4 > buf.size()) refuse("bad_string");
        std::uint32_t u = 0;
        for (std::size_t i = 0; i < 4; ++i) {
            const unsigned char c = static_cast<unsigned char>(buf[pos + i]);
            if (c >= '0' && c <= '9') u = u << 4 | static_cast<std::uint32_t>(c - '0');
            else if (c >= 'a' && c <= 'f') u = u << 4 | static_cast<std::uint32_t>(c - 'a' + 10);
            else if (c >= 'A' && c <= 'F') u = u << 4 | static_cast<std::uint32_t>(c - 'A' + 10);
            else refuse("bad_string");
        }
        pos += 4;
        return u;
    }

    std::int64_t integer(std::int64_t low, std::int64_t high) {
        const unsigned char c = at();
        if (c != '-' && !digit()) refuse("wrong_type");
        const bool negative = c == '-';
        if (negative) ++pos;
        if (!digit()) refuse("malformed");
        std::uint64_t u = 0;
        if (at() == '0') {
            ++pos;
        } else {
            while (digit()) {
                if (u > 922337203685477580ULL) refuse("number_spelling");
                u = u * 10 + static_cast<std::uint64_t>(at() - '0');
                ++pos;
            }
        }
        const unsigned char after = at();
        if (after == '.' || after == 'e' || after == 'E' || digit()) refuse("number_spelling");
        if (negative && u == 0) refuse("number_spelling");
        std::int64_t n = 0;
        if (negative) {
            if (u > (1ULL << 63)) refuse("number_spelling");
            n = u == (1ULL << 63) ? INT64_MIN : -static_cast<std::int64_t>(u);
        } else {
            if (u > static_cast<std::uint64_t>(INT64_MAX)) refuse("number_spelling");
            n = static_cast<std::int64_t>(u);
        }
        if (n < low || n > high) refuse("number_spelling");
        return n;
    }

    bool boolean() {
        if (at() == 't') { literal("true"); return true; }
        if (at() == 'f') { literal("false"); return false; }
        refuse("wrong_type");
    }

    void literal(std::string_view word) {
        if (buf.substr(pos, word.size()) != word) refuse("malformed");
        pos += word.size();
    }

    std::vector<std::string> str_list() {
        if (at() != '[') refuse("wrong_type");
        enter();
        ++pos;
        std::vector<std::string> out;
        skip_ws();
        if (at() != ']') {
            for (;;) {
                skip_ws();
                out.push_back(str());
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != ']') refuse("malformed");
        ++pos;
        --depth;
        return out;
    }

    std::map<std::string, Raw> raw_map() {
        if (at() != '{') refuse("wrong_type");
        enter();
        ++pos;
        std::map<std::string, Raw> out;
        skip_ws();
        if (at() != '}') {
            for (;;) {
                skip_ws();
                if (at() != '"') refuse("malformed");
                const std::string k = str();
                skip_ws();
                if (at() != ':') refuse("malformed");
                ++pos;
                skip_ws();
                out[k] = raw_value();
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != '}') refuse("malformed");
        ++pos;
        --depth;
        return out;
    }

    Raw raw_value() {
        const std::size_t start = pos;
        skip_value();
        return std::string(buf.substr(start, pos - start));
    }

    void skip_value() {
        const unsigned char c = at();
        if (c == '"') skip_string();
        else if (c == '{' || c == '[') skip_container();
        else if (c == 't') literal("true");
        else if (c == 'f') literal("false");
        else if (c == 'n') literal("null");
        else if (c == '-' || digit()) skip_number();
        else refuse("malformed");
    }

    // An opaque value is validated and carried, never interpreted. Its syntax is
    // the record's own — the same string reader, so an escape, a control byte or
    // a lone surrogate is judged identically at any depth — and what it is free
    // to spell, it keeps: the bytes between these two offsets are what a writer
    // re-emits. A number is walked, never converted, so a value no host type
    // holds survives the reader that carried it.
    void skip_string() { str(); }

    void some_digits() {
        int n = 0;
        while (digit()) { ++pos; ++n; }
        if (n == 0) refuse("number_spelling");
    }

    void skip_number() {
        if (at() == '-') ++pos;
        const unsigned char c = at();
        if (c == '0') ++pos;
        else if (c >= '1' && c <= '9') { while (digit()) ++pos; }
        else refuse("number_spelling");
        if (at() == '.') { ++pos; some_digits(); }
        if (at() == 'e' || at() == 'E') {
            ++pos;
            if (at() == '+' || at() == '-') ++pos;
            some_digits();
        }
    }

    void skip_container() {
        const unsigned char opener = at();
        const char shut = opener == '{' ? '}' : ']';
        enter();
        ++pos;
        skip_ws();
        if (at() != static_cast<unsigned char>(shut)) {
            for (;;) {
                skip_ws();
                if (opener == '{') {
                    if (at() != '"') refuse("malformed");
                    str();
                    skip_ws();
                    if (at() != ':') refuse("malformed");
                    ++pos;
                    skip_ws();
                }
                skip_value();
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != static_cast<unsigned char>(shut)) refuse("malformed");
        ++pos;
        --depth;
    }
};

inline std::map<std::string, std::string> str_map(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    std::map<std::string, std::string> out;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string k = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            out[k] = r.str();
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    return out;
}

inline RunOverrides decode_run_overrides(Reader& r);
inline Origin decode_origin(Reader& r);
inline Origins decode_origins(Reader& r);
inline Snapshot decode_snapshot(Reader& r);
inline UserSettings decode_user_settings(Reader& r);
inline UserSnapshot decode_user_snapshot(Reader& r);
inline UserReplaceResult decode_user_replace_result(Reader& r);
inline ConfigObservation decode_config_observation(Reader& r);
inline OAConfigReaderReadArguments decode_oa_config_reader_read_arguments(Reader& r);
inline OAConfigEditorReadUserArguments decode_oa_config_editor_read_user_arguments(Reader& r);
inline OAConfigEditorReplaceUserArguments decode_oa_config_editor_replace_user_arguments(Reader& r);
inline OAConfigObserverObserveArguments decode_oa_config_observer_observe_arguments(Reader& r);
inline OAServiceFrame decode_oa_service_frame(Reader& r);
inline OAServiceReply decode_oa_service_reply(Reader& r);
inline OAServiceError decode_oa_service_error(Reader& r);
inline OAConfigReaderReadResult decode_oa_config_reader_read_result(Reader& r);
inline OAConfigEditorReadUserResult decode_oa_config_editor_read_user_result(Reader& r);
inline OAConfigEditorReplaceUserResult decode_oa_config_editor_replace_user_result(Reader& r);
inline OAConfigObserverObserveResult decode_oa_config_observer_observe_result(Reader& r);

inline RunOverrides decode_run_overrides(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    RunOverrides v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "nas_store") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.nas_store = r.str();
            } else if (key == "store") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.store = r.str();
            } else if (key == "log_sink") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.log_sink = r.str();
            } else if (key == "log_service") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.log_service = r.str();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 15u) != 15u) r.refuse("missing_field");
    return v;
}

inline Origin decode_origin(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    Origin v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "rung") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.rung = r.str();
            } else if (key == "path") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.path = r.str();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 3u) != 3u) r.refuse("missing_field");
    return v;
}

inline Origins decode_origins(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    Origins v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "nas_store") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.nas_store = decode_origin(r);
            } else if (key == "store") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.store = decode_origin(r);
            } else if (key == "log_sink") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.log_sink = decode_origin(r);
            } else if (key == "log_service") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.log_service = decode_origin(r);
            } else if (key == "off") {
                if (seen & 16u) r.refuse("duplicate_field");
                seen |= 16u;
                v.off = decode_origin(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 31u) != 31u) r.refuse("missing_field");
    return v;
}

inline Snapshot decode_snapshot(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    Snapshot v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "nas_store") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.nas_store = r.str();
            } else if (key == "store") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.store = r.str();
            } else if (key == "log_sink") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.log_sink = r.str();
            } else if (key == "log_service") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.log_service = r.str();
            } else if (key == "off") {
                if (seen & 16u) r.refuse("duplicate_field");
                seen |= 16u;
                v.off = str_map(r);
            } else if (key == "origins") {
                if (seen & 32u) r.refuse("duplicate_field");
                seen |= 32u;
                v.origins = decode_origins(r);
            } else if (key == "stamp") {
                if (seen & 64u) r.refuse("duplicate_field");
                seen |= 64u;
                v.stamp = r.str();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 127u) != 127u) r.refuse("missing_field");
    return v;
}

inline UserSettings decode_user_settings(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    UserSettings v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "nas_store") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.nas_store = r.str();
            } else if (key == "store") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.store = r.str();
            } else if (key == "log_sink") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.log_sink = r.str();
            } else if (key == "log_service") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.log_service = r.str();
            } else if (key == "off") {
                if (seen & 16u) r.refuse("duplicate_field");
                seen |= 16u;
                v.off = str_map(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 31u) != 31u) r.refuse("missing_field");
    return v;
}

inline UserSnapshot decode_user_snapshot(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    UserSnapshot v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "values") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.values = decode_user_settings(r);
            } else if (key == "revision") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.revision = r.str();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 3u) != 3u) r.refuse("missing_field");
    return v;
}

inline UserReplaceResult decode_user_replace_result(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    UserReplaceResult v;
    std::optional<std::string> wire_outcome;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "outcome") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                wire_outcome = r.str();
            } else if (key == "snapshot") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.snapshot = decode_user_snapshot(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 3u) != 3u) r.refuse("missing_field");
    if (wire_outcome) {
        const auto parsed = parse_user_replace_outcome(*wire_outcome);
        if (!parsed) r.refuse("bad_enum");
        v.outcome = *parsed;
    }
    return v;
}

inline ConfigObservation decode_config_observation(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    ConfigObservation v;
    std::optional<std::string> wire_outcome;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "outcome") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                wire_outcome = r.str();
            } else if (key == "cursor") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.cursor = r.str();
            } else if (key == "snapshot") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.snapshot = decode_snapshot(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 3u) != 3u) r.refuse("missing_field");
    if (wire_outcome) {
        const auto parsed = parse_config_observation_outcome(*wire_outcome);
        if (!parsed) r.refuse("bad_enum");
        v.outcome = *parsed;
    }
    return v;
}

inline OAConfigReaderReadArguments decode_oa_config_reader_read_arguments(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAConfigReaderReadArguments v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "overrides") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.overrides = decode_run_overrides(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline OAConfigEditorReadUserArguments decode_oa_config_editor_read_user_arguments(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAConfigEditorReadUserArguments v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (false) {
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    return v;
}

inline OAConfigEditorReplaceUserArguments decode_oa_config_editor_replace_user_arguments(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAConfigEditorReplaceUserArguments v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "expected_revision") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.expected_revision = r.str();
            } else if (key == "values") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.values = decode_user_settings(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 3u) != 3u) r.refuse("missing_field");
    return v;
}

inline OAConfigObserverObserveArguments decode_oa_config_observer_observe_arguments(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAConfigObserverObserveArguments v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "overrides") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.overrides = decode_run_overrides(r);
            } else if (key == "cursor") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.cursor = r.str();
            } else if (key == "wait_ms") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.wait_ms = r.integer(INT64_MIN, INT64_MAX);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 7u) != 7u) r.refuse("missing_field");
    return v;
}

inline OAServiceFrame decode_oa_service_frame(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAServiceFrame v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "version") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.version = static_cast<std::int32_t>(r.integer(INT32_MIN, INT32_MAX));
            } else if (key == "service") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.service = r.str();
            } else if (key == "method") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.method = r.str();
            } else if (key == "arguments") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.arguments = r.raw_value();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 15u) != 15u) r.refuse("missing_field");
    return v;
}

inline OAServiceReply decode_oa_service_reply(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAServiceReply v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "version") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.version = static_cast<std::int32_t>(r.integer(INT32_MIN, INT32_MAX));
            } else if (key == "service") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.service = r.str();
            } else if (key == "method") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.method = r.str();
            } else if (key == "ok") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.ok = r.boolean();
            } else if (key == "payload") {
                if (seen & 16u) r.refuse("duplicate_field");
                seen |= 16u;
                v.payload = r.raw_value();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 31u) != 31u) r.refuse("missing_field");
    return v;
}

inline OAServiceError decode_oa_service_error(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAServiceError v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "code") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.code = r.str();
            } else if (key == "message") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.message = r.str();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 3u) != 3u) r.refuse("missing_field");
    return v;
}

inline OAConfigReaderReadResult decode_oa_config_reader_read_result(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAConfigReaderReadResult v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "value") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.value = decode_snapshot(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline OAConfigEditorReadUserResult decode_oa_config_editor_read_user_result(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAConfigEditorReadUserResult v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "value") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.value = decode_user_snapshot(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline OAConfigEditorReplaceUserResult decode_oa_config_editor_replace_user_result(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAConfigEditorReplaceUserResult v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "value") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.value = decode_user_replace_result(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline OAConfigObserverObserveResult decode_oa_config_observer_observe_result(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAConfigObserverObserveResult v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "value") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.value = decode_config_observation(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

}  // namespace detail

inline std::string encode(const Snapshot& v) {
    std::string out;
    detail::enc_snapshot(out, v, 0);
    out += '\n';
    return out;
}

inline Snapshot decode(std::string_view data) {
    detail::Reader r{data};
    r.skip_ws();
    Snapshot v = detail::decode_snapshot(r);
    r.skip_ws();
    if (r.pos < r.buf.size()) r.refuse("trailing_bytes");
    return v;
}

namespace detail {
// kRefusals is in the order two of them are chosen between.
inline const std::vector<std::string> kRefusals = {"malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"};

inline int refusal_rank(std::string_view word) {
    for (std::size_t i = 0; i < kRefusals.size(); ++i)
        if (kRefusals[i] == word) return static_cast<int>(i);
    return -1;
}
}  // namespace detail

struct FrameWriter{virtual ~FrameWriter()=default;virtual void write_frame(std::string_view frame)=0;};
struct DispatchError:std::runtime_error{using std::runtime_error::runtime_error;};
namespace detail {
inline OAServiceFrame service_payload(std::string_view frame){Reader r{frame};r.skip_ws();auto v=decode_oa_service_frame(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");if(v.version!=1)throw DispatchError("unknown_version");return v;}
}  // namespace detail
// Validates the request envelope and version; dispatchers validate typed arguments.
inline std::string service_name(std::string_view frame){return detail::service_payload(frame).service;}

struct FrameExchanger{virtual ~FrameExchanger()=default;virtual std::string exchange_frame(std::string_view frame)=0;};
struct ServiceError:std::runtime_error{std::string code,message;ServiceError(std::string c,std::string m):std::runtime_error(m.empty()?c:m),code(c),message(m){}};
namespace detail {
inline Raw service_response(std::string_view frame,std::string_view service,std::string_view method){
 Reader r{frame};r.skip_ws();auto v=decode_oa_service_reply(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");if(v.version!=1)throw DispatchError("unknown_version");if(v.service!=service||v.method!=method)throw DispatchError("mismatched_response");
 if(!v.ok){Reader e{v.payload};e.depth=1;e.skip_ws();auto error=decode_oa_service_error(e);e.skip_ws();if(e.pos!=e.buf.size())e.refuse("trailing_bytes");if(error.code.empty())throw DispatchError("invalid_error");throw ServiceError(error.code,error.message);}return v.payload;
}
inline std::string service_reply(const OAServiceFrame& request,const Raw& payload,const ServiceError* error=nullptr){
 OAServiceReply reply;reply.version=1;reply.service=request.service;reply.method=request.method;reply.ok=error==nullptr;reply.payload=payload;
 if(error){OAServiceError e;e.code=error->code.empty()?"handler_error":error->code;e.message=error->message;reply.payload.clear();enc_oa_service_error(reply.payload,e,1);}
 std::string frame;enc_oa_service_reply(frame,reply,0);Reader r{frame};r.skip_ws();decode_oa_service_reply(r);return frame;
}
}  // namespace detail

// The base-protocol service every dispatcher answers beside its own.
inline constexpr std::string_view kEndpointContract="abstraction.facade/endpoint@1";
// One service an endpoint hosts, as a dispatcher of any generated namespace
// reports it to describe_endpoint.
struct DescribedService{std::string contract;bool ready;std::string why;};
namespace detail {
template<class H>auto ready_hook(int)->decltype((void)static_cast<H*>(nullptr)->ready(),static_cast<bool(*)(void*,std::string&)>(nullptr)){return [](void* h,std::string& why)->bool{auto r=static_cast<H*>(h)->ready();why=r.second;return r.first;};}
template<class H>bool(*ready_hook(long))(void*,std::string&){return nullptr;}
}  // namespace detail
// Answers an abstraction.facade/endpoint@1 Describe frame for an endpoint
// hosting services, in that order: each is a dispatcher of any generated
// namespace. program and version are the provider's own display name and
// version, never authority. A frame for another service reads unknown_service.
template<class... Services>std::string describe_endpoint(std::string_view frame,const std::string& program,const std::string& version,const Services&... services){
 auto v=detail::service_payload(frame);
 if(v.service!=kEndpointContract){ServiceError e("unknown_service","");return detail::service_reply(v,"",&e);}
 if(v.method!="Describe"){ServiceError e("unknown_method","");return detail::service_reply(v,"",&e);}
 detail::Reader r{v.arguments};r.skip_ws();bool empty=false;
 if(r.pos<r.buf.size()&&r.buf[r.pos]=='{'){r.pos++;r.skip_ws();if(r.pos<r.buf.size()&&r.buf[r.pos]=='}'){r.pos++;r.skip_ws();empty=r.pos==r.buf.size();}}
 if(!empty){ServiceError e("unknown_field","");return detail::service_reply(v,"",&e);}
 try{
  Raw out="{\"value\":{\"outcome\":\"described\",\"program\":";detail::esc(out,program);out+=",\"version\":";detail::esc(out,version);out+=",\"services\":[";
  bool first=true;
  auto add=[&](const auto& s){if(!first)out+=',';first=false;out+="{\"contract\":";detail::esc(out,s.contract);out+=",\"readiness\":\"";out+=s.ready?"ready":"not_ready";out+="\",\"why\":";detail::esc(out,s.why);out+=",\"guarantees\":[],\"capabilities\":{}}";};
  (void)add;
  (add(services.describe_service()),...);
  out+="]}}";
  return detail::service_reply(v,out);
 }catch(const Refusal&e){ServiceError error(e.word,"");return detail::service_reply(v,"",&error);}
}
struct ConfigReader{virtual ~ConfigReader()=default;
virtual Snapshot read(const RunOverrides& overrides)=0;
};
template<class Transport>struct ConfigReaderClient:ConfigReader{Transport& transport_;explicit ConfigReaderClient(Transport&t):transport_(t){}
Snapshot read(const RunOverrides& overrides)override{detail::OAConfigReaderReadArguments args;
args.overrides=overrides;
detail::OAServiceFrame v;v.version=1;v.service="abstraction.config/reader@1";v.method="Read";detail::enc_oa_config_reader_read_arguments(v.arguments,args,1);std::string frame;detail::enc_oa_service_frame(frame,v,0);detail::service_payload(frame);
auto response=transport_.exchange_frame(frame);auto payload=detail::service_response(response,v.service,v.method);detail::Reader r{payload};r.depth=1;r.skip_ws();auto result=detail::decode_oa_config_reader_read_result(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");
return result.value;
}
};
struct ConfigReaderService{inline static constexpr std::string_view kWireName="abstraction.config/reader@1";inline static constexpr std::string_view kCapability="abstraction.config";template<class Transport>using Client=ConfigReaderClient<Transport>;};
struct ConfigReaderDispatcher:FrameWriter,FrameExchanger{ConfigReader&handler;explicit ConfigReaderDispatcher(ConfigReader&h):handler(h){}
// A handler whose own type has ready(), returning a pair of bool and std::string, reports its readiness through describe_service.
template<class H,class=decltype(static_cast<ConfigReader&>(*static_cast<H*>(nullptr)))>explicit ConfigReaderDispatcher(H&h):handler(h),ready_self_(&h),ready_hook_(detail::ready_hook<H>(0)){}
// This dispatcher's service as abstraction.facade/endpoint@1 Describe lists it.
DescribedService describe_service()const{DescribedService s{"abstraction.config/reader@1",true,std::string()};if(ready_hook_){s.ready=ready_hook_(ready_self_,s.why);if(s.ready)s.why.clear();}return s;}
void write_frame(std::string_view frame)override{auto v=detail::service_payload(frame);if(v.service!="abstraction.config/reader@1")throw DispatchError("unknown_service");
if(v.method=="Read"){
throw DispatchError("wrong_mode");}
throw DispatchError("unknown_method");}
std::string exchange_frame(std::string_view frame)override{auto v=detail::service_payload(frame);if(v.service==kEndpointContract)return describe_endpoint(frame,std::string(),std::string(),*this);if(v.service!="abstraction.config/reader@1"){ServiceError e("unknown_service","");return detail::service_reply(v,"",&e);}
try{
if(v.method=="Read"){
detail::Reader r{v.arguments};r.depth=1;r.skip_ws();auto args=detail::decode_oa_config_reader_read_arguments(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");auto payload=invoke_read(args);return detail::service_reply(v,payload);}
throw ServiceError("unknown_method","");}catch(const ServiceError&e){return detail::service_reply(v,"",&e);}catch(const Refusal&e){ServiceError error(e.word,"");return detail::service_reply(v,"",&error);}
}
private:
Raw invoke_read(const detail::OAConfigReaderReadArguments&args){
Snapshot result{};
try{
result=handler.read(args.overrides);
}catch(const ServiceError&){throw;}catch(...){throw ServiceError("handler_error","handler failed");}
try{
detail::OAConfigReaderReadResult value;
value.value=result;
Raw payload;detail::enc_oa_config_reader_read_result(payload,value,1);detail::Reader r{payload};r.depth=1;r.skip_ws();detail::decode_oa_config_reader_read_result(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");return payload;
}catch(...){throw ServiceError("invalid_result","");}
}
private:
void* ready_self_=nullptr;
bool(*ready_hook_)(void*,std::string&)=nullptr;
};
struct ConfigEditor{virtual ~ConfigEditor()=default;
virtual UserSnapshot read_user()=0;
virtual UserReplaceResult replace_user(const std::string& expected_revision,const UserSettings& values)=0;
};
template<class Transport>struct ConfigEditorClient:ConfigEditor{Transport& transport_;explicit ConfigEditorClient(Transport&t):transport_(t){}
UserSnapshot read_user()override{detail::OAConfigEditorReadUserArguments args;
detail::OAServiceFrame v;v.version=1;v.service="abstraction.config/editor@1";v.method="ReadUser";detail::enc_oa_config_editor_read_user_arguments(v.arguments,args,1);std::string frame;detail::enc_oa_service_frame(frame,v,0);detail::service_payload(frame);
auto response=transport_.exchange_frame(frame);auto payload=detail::service_response(response,v.service,v.method);detail::Reader r{payload};r.depth=1;r.skip_ws();auto result=detail::decode_oa_config_editor_read_user_result(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");
return result.value;
}
UserReplaceResult replace_user(const std::string& expected_revision,const UserSettings& values)override{detail::OAConfigEditorReplaceUserArguments args;
args.expected_revision=expected_revision;
args.values=values;
detail::OAServiceFrame v;v.version=1;v.service="abstraction.config/editor@1";v.method="ReplaceUser";detail::enc_oa_config_editor_replace_user_arguments(v.arguments,args,1);std::string frame;detail::enc_oa_service_frame(frame,v,0);detail::service_payload(frame);
auto response=transport_.exchange_frame(frame);auto payload=detail::service_response(response,v.service,v.method);detail::Reader r{payload};r.depth=1;r.skip_ws();auto result=detail::decode_oa_config_editor_replace_user_result(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");
return result.value;
}
};
struct ConfigEditorService{inline static constexpr std::string_view kWireName="abstraction.config/editor@1";inline static constexpr std::string_view kCapability="abstraction.config";template<class Transport>using Client=ConfigEditorClient<Transport>;};
struct ConfigEditorDispatcher:FrameWriter,FrameExchanger{ConfigEditor&handler;explicit ConfigEditorDispatcher(ConfigEditor&h):handler(h){}
// A handler whose own type has ready(), returning a pair of bool and std::string, reports its readiness through describe_service.
template<class H,class=decltype(static_cast<ConfigEditor&>(*static_cast<H*>(nullptr)))>explicit ConfigEditorDispatcher(H&h):handler(h),ready_self_(&h),ready_hook_(detail::ready_hook<H>(0)){}
// This dispatcher's service as abstraction.facade/endpoint@1 Describe lists it.
DescribedService describe_service()const{DescribedService s{"abstraction.config/editor@1",true,std::string()};if(ready_hook_){s.ready=ready_hook_(ready_self_,s.why);if(s.ready)s.why.clear();}return s;}
void write_frame(std::string_view frame)override{auto v=detail::service_payload(frame);if(v.service!="abstraction.config/editor@1")throw DispatchError("unknown_service");
if(v.method=="ReadUser"){
throw DispatchError("wrong_mode");}
if(v.method=="ReplaceUser"){
throw DispatchError("wrong_mode");}
throw DispatchError("unknown_method");}
std::string exchange_frame(std::string_view frame)override{auto v=detail::service_payload(frame);if(v.service==kEndpointContract)return describe_endpoint(frame,std::string(),std::string(),*this);if(v.service!="abstraction.config/editor@1"){ServiceError e("unknown_service","");return detail::service_reply(v,"",&e);}
try{
if(v.method=="ReadUser"){
detail::Reader r{v.arguments};r.depth=1;r.skip_ws();auto args=detail::decode_oa_config_editor_read_user_arguments(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");auto payload=invoke_read_user(args);return detail::service_reply(v,payload);}
if(v.method=="ReplaceUser"){
detail::Reader r{v.arguments};r.depth=1;r.skip_ws();auto args=detail::decode_oa_config_editor_replace_user_arguments(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");auto payload=invoke_replace_user(args);return detail::service_reply(v,payload);}
throw ServiceError("unknown_method","");}catch(const ServiceError&e){return detail::service_reply(v,"",&e);}catch(const Refusal&e){ServiceError error(e.word,"");return detail::service_reply(v,"",&error);}
}
private:
Raw invoke_read_user(const detail::OAConfigEditorReadUserArguments&args){
UserSnapshot result{};
try{
result=handler.read_user();
}catch(const ServiceError&){throw;}catch(...){throw ServiceError("handler_error","handler failed");}
try{
detail::OAConfigEditorReadUserResult value;
value.value=result;
Raw payload;detail::enc_oa_config_editor_read_user_result(payload,value,1);detail::Reader r{payload};r.depth=1;r.skip_ws();detail::decode_oa_config_editor_read_user_result(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");return payload;
}catch(...){throw ServiceError("invalid_result","");}
}
Raw invoke_replace_user(const detail::OAConfigEditorReplaceUserArguments&args){
UserReplaceResult result{};
try{
result=handler.replace_user(args.expected_revision,args.values);
}catch(const ServiceError&){throw;}catch(...){throw ServiceError("handler_error","handler failed");}
try{
detail::OAConfigEditorReplaceUserResult value;
value.value=result;
Raw payload;detail::enc_oa_config_editor_replace_user_result(payload,value,1);detail::Reader r{payload};r.depth=1;r.skip_ws();detail::decode_oa_config_editor_replace_user_result(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");return payload;
}catch(...){throw ServiceError("invalid_result","");}
}
private:
void* ready_self_=nullptr;
bool(*ready_hook_)(void*,std::string&)=nullptr;
};
struct ConfigObserver{virtual ~ConfigObserver()=default;
virtual ConfigObservation observe(const RunOverrides& overrides,const std::string& cursor,const std::int64_t& wait_ms)=0;
};
template<class Transport>struct ConfigObserverClient:ConfigObserver{Transport& transport_;explicit ConfigObserverClient(Transport&t):transport_(t){}
ConfigObservation observe(const RunOverrides& overrides,const std::string& cursor,const std::int64_t& wait_ms)override{detail::OAConfigObserverObserveArguments args;
args.overrides=overrides;
args.cursor=cursor;
args.wait_ms=wait_ms;
detail::OAServiceFrame v;v.version=1;v.service="abstraction.config/observer@1";v.method="Observe";detail::enc_oa_config_observer_observe_arguments(v.arguments,args,1);std::string frame;detail::enc_oa_service_frame(frame,v,0);detail::service_payload(frame);
auto response=transport_.exchange_frame(frame);auto payload=detail::service_response(response,v.service,v.method);detail::Reader r{payload};r.depth=1;r.skip_ws();auto result=detail::decode_oa_config_observer_observe_result(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");
return result.value;
}
};
struct ConfigObserverService{inline static constexpr std::string_view kWireName="abstraction.config/observer@1";inline static constexpr std::string_view kCapability="abstraction.config";template<class Transport>using Client=ConfigObserverClient<Transport>;};
struct ConfigObserverDispatcher:FrameWriter,FrameExchanger{ConfigObserver&handler;explicit ConfigObserverDispatcher(ConfigObserver&h):handler(h){}
// A handler whose own type has ready(), returning a pair of bool and std::string, reports its readiness through describe_service.
template<class H,class=decltype(static_cast<ConfigObserver&>(*static_cast<H*>(nullptr)))>explicit ConfigObserverDispatcher(H&h):handler(h),ready_self_(&h),ready_hook_(detail::ready_hook<H>(0)){}
// This dispatcher's service as abstraction.facade/endpoint@1 Describe lists it.
DescribedService describe_service()const{DescribedService s{"abstraction.config/observer@1",true,std::string()};if(ready_hook_){s.ready=ready_hook_(ready_self_,s.why);if(s.ready)s.why.clear();}return s;}
void write_frame(std::string_view frame)override{auto v=detail::service_payload(frame);if(v.service!="abstraction.config/observer@1")throw DispatchError("unknown_service");
if(v.method=="Observe"){
throw DispatchError("wrong_mode");}
throw DispatchError("unknown_method");}
std::string exchange_frame(std::string_view frame)override{auto v=detail::service_payload(frame);if(v.service==kEndpointContract)return describe_endpoint(frame,std::string(),std::string(),*this);if(v.service!="abstraction.config/observer@1"){ServiceError e("unknown_service","");return detail::service_reply(v,"",&e);}
try{
if(v.method=="Observe"){
detail::Reader r{v.arguments};r.depth=1;r.skip_ws();auto args=detail::decode_oa_config_observer_observe_arguments(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");auto payload=invoke_observe(args);return detail::service_reply(v,payload);}
throw ServiceError("unknown_method","");}catch(const ServiceError&e){return detail::service_reply(v,"",&e);}catch(const Refusal&e){ServiceError error(e.word,"");return detail::service_reply(v,"",&error);}
}
private:
Raw invoke_observe(const detail::OAConfigObserverObserveArguments&args){
ConfigObservation result{};
try{
result=handler.observe(args.overrides,args.cursor,args.wait_ms);
}catch(const ServiceError&){throw;}catch(...){throw ServiceError("handler_error","handler failed");}
try{
detail::OAConfigObserverObserveResult value;
value.value=result;
Raw payload;detail::enc_oa_config_observer_observe_result(payload,value,1);detail::Reader r{payload};r.depth=1;r.skip_ws();detail::decode_oa_config_observer_observe_result(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");return payload;
}catch(...){throw ServiceError("invalid_result","");}
}
private:
void* ready_self_=nullptr;
bool(*ready_hook_)(void*,std::string&)=nullptr;
};

}  // namespace abstraction::config
