// Code generated by abstraction-idl from abstraction-config/config.thrift. DO NOT EDIT.

// abstraction.config: generated contract types, vocabularies and service clients.
export {
  ConfigEditorClient,
  ConfigEditorService,
  ConfigObservationOutcome,
  ConfigObserverClient,
  ConfigObserverService,
  ConfigReaderClient,
  ConfigReaderService,
  DispatchError,
  Refusal,
  ServiceError,
  ServiceErrorCode,
  UserReplaceOutcome,
  decode,
  editorErrorCodes,
  encode,
  newConfigObservation,
  newOrigin,
  newOrigins,
  newRunOverrides,
  newSnapshot,
  newUserReplaceResult,
  newUserSettings,
  newUserSnapshot,
  readerErrorCodes,
} from "./internal.mjs";
