// Code generated by abstraction-idl from abstraction-config/config.thrift. DO NOT EDIT.

// abstraction.config: declarations for index.mjs.

/** The frame transport a generated client calls: a facade binding or a connector's transport. */
interface FrameTransport {
  exchangeFrame(frame: Uint8Array): Promise<Uint8Array>;
  writeFrame(frame: Uint8Array): Promise<void>;
}

/** Same-account Program-proven user editor on the config endpoint. The service selects its private user path once. Caller claims cannot grant authority; forbidden callers cause no storage access. Existing machine and run rungs are unaffected. */
export declare class ConfigEditorClient {
  constructor(transport: FrameTransport);
  /** Read only the authenticated service user's persisted rung. No environment or machine merge. Missing storage is empty; corrupt, unsupported or unavailable storage returns storage_unavailable. */
  readUser(): Promise<UserSnapshot>;
  /** Compare the opaque revision and replace atomically through the selected conditional-write store. Stale revision returns conflict. Empty revision is invalid_revision. Storage failures return storage_unavailable. A configured edit policy is evaluated after same-account proof and before storage access: refusal returns forbidden and a failed decision returns unavailable. A canceled wait leaves write outcome unresolved; reread rather than blindly retry. */
  replaceUser(expectedRevision: string, values: UserSettings): Promise<UserReplaceResult>;
}

export declare const ConfigEditorService: Readonly<{ wireName: "abstraction.config/editor@1"; Client: typeof ConfigEditorClient }>;

// Latest effective configuration, with an opaque cursor bound to provider
// instance and explicit run overrides. snapshot carries a snapshot and new
// cursor; unchanged carries the original cursor and no snapshot. Other outcomes
// carry no snapshot and preserve the supplied cursor. Intermediate revisions
// may be coalesced; this is not an event history. A restarted provider or
// changed override binding gives gap and requires an explicit empty-cursor
// restart.
export interface ConfigObservation {
  outcome: ConfigObservationOutcome;
  cursor: string;
  snapshot: Snapshot | null;
}

export type ConfigObservationOutcome = (typeof ConfigObservationOutcome)[keyof typeof ConfigObservationOutcome];
export declare const ConfigObservationOutcome: Readonly<{ Snapshot: "snapshot"; Unchanged: "unchanged"; Gap: "gap"; Unavailable: "unavailable"; Unsupported: "unsupported"; Invalid: "invalid" }>;

/** Same-account latest-snapshot long-poll observation over a provider's explicit change notification source. */
export declare class ConfigObserverClient {
  constructor(transport: FrameTransport);
  /** Empty cursor reads the current snapshot. At the same revision, wait at most wait_ms (0..30000) for provider invalidation; reread on expiry. Cursor is at most 512 UTF-8 bytes and each override at most 4096 bytes. A slow consumer receives the latest revision; revisions include values and provenance. Missing change notification support gives unsupported. Bounded waiter exhaustion or provider notification failure gives unavailable. Caller cancellation stops observation waiting only; setting mutations retain their own lifetimes. Receiving account authority is rechecked before returning data. */
  observe(overrides: RunOverrides, cursor: string, waitMs: bigint): Promise<ConfigObservation>;
}

export declare const ConfigObserverService: Readonly<{ wireName: "abstraction.config/observer@1"; Client: typeof ConfigObserverClient }>;

/** Per-user configuration read service. Caller identity is checked independently of overrides. */
export declare class ConfigReaderClient {
  constructor(transport: FrameTransport);
  /** Read same-user machine/user configuration with explicit caller run overrides. No writes, watch or provider fallback. */
  read(overrides: RunOverrides): Promise<Snapshot>;
}

export declare const ConfigReaderService: Readonly<{ wireName: "abstraction.config/reader@1"; Client: typeof ConfigReaderClient }>;

export declare class DispatchError extends Error {
  constructor(code: string);
  code: string;
}

// Per-key provenance: machine/user file path, or environment/default with empty
// path.
export interface Origin {
  rung: string;
  path: string;
}

// Provenance for every configuration key, including default answers.
export interface Origins {
  nasStore: Origin;
  store: Origin;
  logSink: Origin;
  logService: Origin;
  off: Origin;
}

export declare class Refusal extends Error {
  constructor(word: string, offset: number);
  word: "malformed" | "bad_string" | "number_spelling" | "wrong_type" | "depth_exceeded" | "duplicate_field" | "unknown_field" | "missing_field" | "bad_enum" | "trailing_bytes";
  offset: number;
}

// Existing per-run overrides. Empty strings do not override file values.
export interface RunOverrides {
  nasStore: string;
  store: string;
  logSink: string;
  logService: string;
}

export declare class ServiceError extends Error {
  constructor(code: string, message?: string);
  code: string;
}

export type ServiceErrorCode = (typeof ServiceErrorCode)[keyof typeof ServiceErrorCode];
export declare const ServiceErrorCode: Readonly<{ HandlerError: "handler_error"; InvalidResult: "invalid_result"; UnknownVersion: "unknown_version"; UnknownService: "unknown_service"; UnknownMethod: "unknown_method"; WrongMode: "wrong_mode"; StorageUnavailable: "storage_unavailable"; CallerUnavailable: "caller_unavailable"; IdentityRequired: "identity_required"; WrongUser: "wrong_user"; InvalidRevision: "invalid_revision" }>;

// Existing provider values and provenance. Empty values mean absence. Stamp
// follows values rather than provenance; paths are diagnostic configuration
// data, not permission to access a store.
export interface Snapshot {
  nasStore: string;
  store: string;
  logSink: string;
  logService: string;
  off: { [key: string]: string };
  origins: Origins;
  stamp: string;
}

export type UserReplaceOutcome = (typeof UserReplaceOutcome)[keyof typeof UserReplaceOutcome];
export declare const UserReplaceOutcome: Readonly<{ Applied: "applied"; Conflict: "conflict"; Forbidden: "forbidden"; Unavailable: "unavailable" }>;

// Applied returns the written snapshot. Conflict performs no write and returns
// the current snapshot. Forbidden reports an evaluated edit-policy refusal;
// unavailable reports that the edit-policy decision could not be obtained and
// may be retried. Both perform no storage access and carry empty values with an
// empty revision. No outcome merges settings implicitly.
export interface UserReplaceResult {
  outcome: UserReplaceOutcome;
  snapshot: UserSnapshot;
}

// User-rung overrides only. Empty values clear overrides; machine and run
// values never enter this record. The configuration backing-file path is
// selected by the service; path-valued settings grant no provider storage
// authority.
export interface UserSettings {
  nasStore: string;
  store: string;
  logSink: string;
  logService: string;
  off: { [key: string]: string };
}

// Normalized user-rung content and an opaque content revision. A missing file
// yields empty values; unreadable or unsupported storage is refused. Revision
// may recur when identical content is restored.
export interface UserSnapshot {
  values: UserSettings;
  revision: string;
}

export declare function decode(data: Uint8Array): Snapshot;

export declare const editorErrorCodes: readonly ["invalid_revision", "storage_unavailable", "caller_unavailable", "identity_required", "wrong_user"];

export declare function encode(v: Snapshot): Uint8Array;

export declare function newConfigObservation(): ConfigObservation;

export declare function newOrigin(): Origin;

export declare function newOrigins(): Origins;

export declare function newRunOverrides(): RunOverrides;

export declare function newSnapshot(): Snapshot;

export declare function newUserReplaceResult(): UserReplaceResult;

export declare function newUserSettings(): UserSettings;

export declare function newUserSnapshot(): UserSnapshot;

export declare const readerErrorCodes: readonly ["storage_unavailable", "caller_unavailable", "identity_required", "wrong_user"];

export {};
