// Code generated by abstraction-idl from abstraction-config/config.thrift. DO NOT EDIT.

const HEX = "0123456789abcdef";
const ENC = new TextEncoder();
const SHORT = { 0x22: '\\"', 0x5c: "\\\\", 0x08: "\\b", 0x0c: "\\f", 0x0a: "\\n", 0x0d: "\\r", 0x09: "\\t" };

class Out {
  constructor() { this.b = []; }
  byte(c) { this.b.push(c); }
  ascii(s) { for (let i = 0; i < s.length; i++) this.b.push(s.charCodeAt(i)); }
  bytes() { return Uint8Array.from(this.b); }
}

function escByte(out, c) {
  const short = SHORT[c];
  if (short !== undefined) out.ascii(short);
  else if (c < 0x20) out.ascii("\\u00" + HEX[c >> 4] + HEX[c & 0xf]);
  else out.byte(c);
}

// Every integer the definition calls i64 is a BigInt here, because Number
// rounds above 2^53 and two values in the conformance record are i64 extremes.
function num(out, n) { out.ascii(BigInt(n).toString()); }

function pad(out, depth) { for (let i = 0; i < depth * 2; i++) out.byte(0x20); }

function strs(out, v, depth) {
  if (v.length === 0) { out.ascii("[]"); return; }
  out.ascii("[\n");
  for (let i = 0; i < v.length; i++) {
    pad(out, depth + 1);
    esc(out, v[i]);
    if (i + 1 < v.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x5d);
}

const isWs = (c) => c === 0x20 || c === 0x09 || c === 0x0a || c === 0x0d;

function raw(out, s, depth) {
  const b = typeof s === "string" ? ENC.encode(s) : s;
  let i = 0;
  while (i < b.length) {
    const c = b[i];
    if (isWs(c)) { i++; continue; }
    if (c === 0x22) {
      let j = i + 1;
      while (j < b.length) {
        if (b[j] === 0x5c) { j += 2; continue; }
        if (b[j] === 0x22) { j++; break; }
        j++;
      }
      for (let k = i; k < j; k++) out.byte(b[k]);
      i = j;
    } else if (c === 0x7b || c === 0x5b) {
      out.byte(c);
      i++;
      let j = i;
      while (j < b.length && isWs(b[j])) j++;
      if (j < b.length && (b[j] === 0x7d || b[j] === 0x5d)) { out.byte(b[j]); i = j + 1; }
      else { depth++; out.byte(0x0a); pad(out, depth); }
    } else if (c === 0x7d || c === 0x5d) {
      depth--;
      out.byte(0x0a);
      pad(out, depth);
      out.byte(c);
      i++;
    } else if (c === 0x2c) {
      out.ascii(",\n");
      pad(out, depth);
      i++;
    } else if (c === 0x3a) {
      out.ascii(": ");
      i++;
    } else {
      out.byte(c);
      i++;
    }
  }
}

// A JavaScript string sorts by UTF-16 code unit, which puts U+1D11E before
// U+FFFD where every other target puts it after. The definition declares UTF-8
// byte order, so the comparison is done on the encoded bytes.
function byteLess(a, b) {
  const x = ENC.encode(a), y = ENC.encode(b);
  const n = Math.min(x.length, y.length);
  for (let i = 0; i < n; i++) if (x[i] !== y[i]) return x[i] - y[i];
  return x.length - y.length;
}

function rawmap(out, m, depth) {
  const keys = Object.keys(m).sort(byteLess);
  if (keys.length === 0) { out.ascii("{}"); return; }
  out.ascii("{\n");
  for (let i = 0; i < keys.length; i++) {
    pad(out, depth + 1);
    esc(out, keys[i]);
    out.ascii(": ");
    raw(out, m[keys[i]], depth + 1);
    if (i + 1 < keys.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x7d);
}

function esc(out, s) {
  out.byte(0x22);
  for (const c of ENC.encode(s)) escByte(out, c);
  out.byte(0x22);
}

function strmap(out, m, depth) {
  const keys = Object.keys(m).sort(byteLess);
  if (keys.length === 0) { out.ascii("{}"); return; }
  out.ascii("{\n");
  for (let i = 0; i < keys.length; i++) {
    pad(out, depth + 1);
    esc(out, keys[i]);
    out.ascii(": ");
    esc(out, m[keys[i]]);
    if (i + 1 < keys.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x7d);
}

export const UserReplaceOutcome = Object.freeze({
  Applied: "applied",
  Conflict: "conflict",
  Forbidden: "forbidden",
  Unavailable: "unavailable",
});

export const ConfigObservationOutcome = Object.freeze({
  Snapshot: "snapshot",
  Unchanged: "unchanged",
  Gap: "gap",
  Unavailable: "unavailable",
  Unsupported: "unsupported",
  Invalid: "invalid",
});

export const ServiceErrorCode = Object.freeze({
  HandlerError: "handler_error",
  InvalidResult: "invalid_result",
  UnknownVersion: "unknown_version",
  UnknownService: "unknown_service",
  UnknownMethod: "unknown_method",
  WrongMode: "wrong_mode",
  StorageUnavailable: "storage_unavailable",
  CallerUnavailable: "caller_unavailable",
  IdentityRequired: "identity_required",
  WrongUser: "wrong_user",
  InvalidRevision: "invalid_revision",
});

export const readerErrorCodes = ["storage_unavailable", "caller_unavailable", "identity_required", "wrong_user"];

export const editorErrorCodes = ["invalid_revision", "storage_unavailable", "caller_unavailable", "identity_required", "wrong_user"];

function writeRunOverrides(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "nas_store");
  out.ascii(": ");
  esc(out, v.nasStore);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "store");
  out.ascii(": ");
  esc(out, v.store);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "log_sink");
  out.ascii(": ");
  esc(out, v.logSink);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "log_service");
  out.ascii(": ");
  esc(out, v.logService);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOrigin(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "rung");
  out.ascii(": ");
  esc(out, v.rung);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "path");
  out.ascii(": ");
  esc(out, v.path);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOrigins(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "nas_store");
  out.ascii(": ");
  writeOrigin(out, v.nasStore, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "store");
  out.ascii(": ");
  writeOrigin(out, v.store, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "log_sink");
  out.ascii(": ");
  writeOrigin(out, v.logSink, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "log_service");
  out.ascii(": ");
  writeOrigin(out, v.logService, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "off");
  out.ascii(": ");
  writeOrigin(out, v.off, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeSnapshot(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "nas_store");
  out.ascii(": ");
  esc(out, v.nasStore);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "store");
  out.ascii(": ");
  esc(out, v.store);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "log_sink");
  out.ascii(": ");
  esc(out, v.logSink);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "log_service");
  out.ascii(": ");
  esc(out, v.logService);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "off");
  out.ascii(": ");
  strmap(out, v.off, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "origins");
  out.ascii(": ");
  writeOrigins(out, v.origins, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "stamp");
  out.ascii(": ");
  esc(out, v.stamp);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeUserSettings(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "nas_store");
  out.ascii(": ");
  esc(out, v.nasStore);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "store");
  out.ascii(": ");
  esc(out, v.store);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "log_sink");
  out.ascii(": ");
  esc(out, v.logSink);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "log_service");
  out.ascii(": ");
  esc(out, v.logService);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "off");
  out.ascii(": ");
  strmap(out, v.off, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeUserSnapshot(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "values");
  out.ascii(": ");
  writeUserSettings(out, v.values, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "revision");
  out.ascii(": ");
  esc(out, v.revision);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeUserReplaceResult(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "applied" && v.outcome !== "conflict" && v.outcome !== "forbidden" && v.outcome !== "unavailable") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "snapshot");
  out.ascii(": ");
  writeUserSnapshot(out, v.snapshot, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeConfigObservation(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "snapshot" && v.outcome !== "unchanged" && v.outcome !== "gap" && v.outcome !== "unavailable" && v.outcome !== "unsupported" && v.outcome !== "invalid") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "cursor");
  out.ascii(": ");
  esc(out, v.cursor);
  if (v.snapshot !== undefined && v.snapshot !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "snapshot");
    out.ascii(": ");
    writeSnapshot(out, v.snapshot, depth + 1);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAConfigReaderReadArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "overrides");
  out.ascii(": ");
  writeRunOverrides(out, v.overrides, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAConfigEditorReadUserArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x7d);
}

function writeOAConfigEditorReplaceUserArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "expected_revision");
  out.ascii(": ");
  esc(out, v.expectedRevision);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "values");
  out.ascii(": ");
  writeUserSettings(out, v.values, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAConfigObserverObserveArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "overrides");
  out.ascii(": ");
  writeRunOverrides(out, v.overrides, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "cursor");
  out.ascii(": ");
  esc(out, v.cursor);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "wait_ms");
  out.ascii(": ");
  num(out, v.waitMs);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAServiceFrame(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "version");
  out.ascii(": ");
  num(out, v.version);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "service");
  out.ascii(": ");
  esc(out, v.service);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "method");
  out.ascii(": ");
  esc(out, v.method);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "arguments");
  out.ascii(": ");
  for (const byte of (typeof v.arguments === "string" ? ENC.encode(v.arguments) : v.arguments)) out.byte(byte);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAServiceReply(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "version");
  out.ascii(": ");
  num(out, v.version);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "service");
  out.ascii(": ");
  esc(out, v.service);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "method");
  out.ascii(": ");
  esc(out, v.method);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "ok");
  out.ascii(": ");
  out.ascii(v.ok ? "true" : "false");
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "payload");
  out.ascii(": ");
  for (const byte of (typeof v.payload === "string" ? ENC.encode(v.payload) : v.payload)) out.byte(byte);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAServiceError(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "code");
  out.ascii(": ");
  esc(out, v.code);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "message");
  out.ascii(": ");
  esc(out, v.message);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAConfigReaderReadResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeSnapshot(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAConfigEditorReadUserResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeUserSnapshot(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAConfigEditorReplaceUserResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeUserReplaceResult(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAConfigObserverObserveResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeConfigObservation(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function encode(v) {
  const out = new Out();
  writeSnapshot(out, v, 0);
  out.byte(0x0a);
  return out.bytes();
}

// A BOM inside a JSON string is data, not a stream signature.
const DEC = new TextDecoder("utf-8", {ignoreBOM: true});
const DEPTH_LIMIT = 64;
const I64_DIGITS = 19;
const UNESCAPE = { 0x22: 0x22, 0x5c: 0x5c, 0x2f: 0x2f, 0x62: 0x08, 0x66: 0x0c, 0x6e: 0x0a, 0x72: 0x0d, 0x74: 0x09 };

export class Refusal extends Error {
  constructor(word, offset) {
    super("refused: " + word + " at byte " + offset);
    this.name = "Refusal";
    this.word = word;
    this.offset = offset;
  }
}

function appendRune(out, cp) {
  if (cp < 0x80) out.push(cp);
  else if (cp < 0x800) out.push(0xc0 | (cp >> 6), 0x80 | (cp & 0x3f));
  else if (cp < 0x10000) out.push(0xe0 | (cp >> 12), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
  else out.push(0xf0 | (cp >> 18), 0x80 | ((cp >> 12) & 0x3f), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
}

// TextDecoder substitutes U+FFFD for a bad sequence rather than reporting it, so
// the bytes are checked before they are decoded and the refusal says so.
function validUtf8(b) {
  for (let i = 0; i < b.length; ) {
    const c = b[i];
    if (c < 0x80) { i++; continue; }
    let n, cp;
    if (c >> 5 === 0x6) { n = 2; cp = c & 0x1f; }
    else if (c >> 4 === 0xe) { n = 3; cp = c & 0x0f; }
    else if (c >> 3 === 0x1e) { n = 4; cp = c & 0x07; }
    else return false;
    if (i + n > b.length) return false;
    for (let k = 1; k < n; k++) {
      if (b[i + k] >> 6 !== 0x2) return false;
      cp = (cp << 6) | (b[i + k] & 0x3f);
    }
    const lowest = [0, 0, 0x80, 0x800, 0x10000][n];
    if (cp < lowest || cp > 0x10ffff || (cp >= 0xd800 && cp <= 0xdfff)) return false;
    i += n;
  }
  return true;
}

class Reader {
  constructor(buf) { this.buf = buf; this.pos = 0; this.depth = 0; }

  refuse(word) { return new Refusal(word, this.pos); }

  at() { return this.pos < this.buf.length ? this.buf[this.pos] : 0; }

  digit() { const c = this.at(); return c >= 0x30 && c <= 0x39; }

  ws() { while (this.pos < this.buf.length && isWs(this.buf[this.pos])) this.pos++; }

  enter() {
    this.depth++;
    if (this.depth > DEPTH_LIMIT) throw this.refuse("depth_exceeded");
  }

  string() {
    if (this.at() !== 0x22) throw this.refuse("wrong_type");
    this.pos++;
    const out = [];
    for (;;) {
      if (this.pos >= this.buf.length) throw this.refuse("malformed");
      const c = this.buf[this.pos];
      if (c === 0x22) {
        this.pos++;
        const bytes = Uint8Array.from(out);
        if (!validUtf8(bytes)) throw this.refuse("bad_string");
        return DEC.decode(bytes);
      }
      if (c < 0x20) throw this.refuse("bad_string");
      if (c === 0x5c) this.escape(out);
      else { out.push(c); this.pos++; }
    }
  }

  escape(out) {
    this.pos++;
    if (this.pos >= this.buf.length) throw this.refuse("malformed");
    const c = this.buf[this.pos];
    this.pos++;
    const plain = UNESCAPE[c];
    if (plain !== undefined) { out.push(plain); return; }
    if (c !== 0x75) throw this.refuse("bad_string");
    let u = this.hex4();
    if (u >= 0xdc00 && u <= 0xdfff) throw this.refuse("bad_string");
    if (u >= 0xd800 && u <= 0xdbff) {
      if (this.pos + 1 >= this.buf.length || this.buf[this.pos] !== 0x5c || this.buf[this.pos + 1] !== 0x75)
        throw this.refuse("bad_string");
      this.pos += 2;
      const low = this.hex4();
      if (low < 0xdc00 || low > 0xdfff) throw this.refuse("bad_string");
      u = 0x10000 + ((u - 0xd800) << 10) + (low - 0xdc00);
    }
    appendRune(out, u);
  }

  hex4() {
    if (this.pos + 4 > this.buf.length) throw this.refuse("bad_string");
    let u = 0;
    for (let i = 0; i < 4; i++) {
      const c = this.buf[this.pos + i];
      if (c >= 0x30 && c <= 0x39) u = (u << 4) | (c - 0x30);
      else if (c >= 0x61 && c <= 0x66) u = (u << 4) | (c - 0x61 + 10);
      else if (c >= 0x41 && c <= 0x46) u = (u << 4) | (c - 0x41 + 10);
      else throw this.refuse("bad_string");
    }
    this.pos += 4;
    return u;
  }

  integer(low, high) {
    const c = this.at();
    if (c !== 0x2d && (c < 0x30 || c > 0x39)) throw this.refuse("wrong_type");
    const negative = c === 0x2d;
    if (negative) this.pos++;
    if (!this.digit()) throw this.refuse("malformed");
    const start = this.pos;
    if (this.at() === 0x30) this.pos++;
    else while (this.digit()) this.pos++;
    const after = this.at();
    if (after === 0x2e || after === 0x65 || after === 0x45 || this.digit()) throw this.refuse("number_spelling");
    if (this.pos - start > I64_DIGITS) throw this.refuse("number_spelling");
    let n = BigInt(String.fromCharCode(...this.buf.subarray(start, this.pos)));
    if (negative) {
      if (n === 0n) throw this.refuse("number_spelling");
      n = -n;
    }
    if (n < low || n > high) throw this.refuse("number_spelling");
    return n;
  }

  boolean() {
    if (this.at() === 0x74) { this.literal("true"); return true; }
    if (this.at() === 0x66) { this.literal("false"); return false; }
    throw this.refuse("wrong_type");
  }

  literal(word) {
    for (let i = 0; i < word.length; i++)
      if (this.buf[this.pos + i] !== word.charCodeAt(i)) throw this.refuse("malformed");
    this.pos += word.length;
  }

  strList() {
    if (this.at() !== 0x5b) throw this.refuse("wrong_type");
    this.enter();
    this.pos++;
    const out = [];
    this.ws();
    if (this.at() !== 0x5d) {
      for (;;) {
        this.ws();
        out.push(this.string());
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== 0x5d) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
    return out;
  }

  rawMap() {
    if (this.at() !== 0x7b) throw this.refuse("wrong_type");
    this.enter();
    this.pos++;
    const out = Object.create(null);
    this.ws();
    if (this.at() !== 0x7d) {
      for (;;) {
        this.ws();
        if (this.at() !== 0x22) throw this.refuse("malformed");
        const k = this.string();
        this.ws();
        if (this.at() !== 0x3a) throw this.refuse("malformed");
        this.pos++;
        this.ws();
        out[k] = this.rawValue();
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== 0x7d) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
    return out;
  }

  rawValue() {
    const start = this.pos;
    this.skipValue();
    return this.buf.subarray(start, this.pos);
  }

  skipValue() {
    const c = this.at();
    if (c === 0x22) this.skipString();
    else if (c === 0x7b || c === 0x5b) this.skipContainer();
    else if (c === 0x74) this.literal("true");
    else if (c === 0x66) this.literal("false");
    else if (c === 0x6e) this.literal("null");
    else if (c === 0x2d || (c >= 0x30 && c <= 0x39)) this.skipNumber();
    else throw this.refuse("malformed");
  }

  // An opaque value is validated and carried, never interpreted. Its syntax is
  // the record's own — the same string reader, so an escape, a control byte or a
  // lone surrogate is judged identically at any depth — and what it is free to
  // spell, it keeps: the bytes between these two offsets are what a writer
  // re-emits. A number is walked, never converted, so a value no host type holds
  // survives the reader that carried it.
  skipString() {
    this.string();
  }

  someDigits() {
    let n = 0;
    while (this.at() >= 0x30 && this.at() <= 0x39) { this.pos++; n++; }
    if (n === 0) throw this.refuse("number_spelling");
  }

  skipNumber() {
    if (this.at() === 0x2d) this.pos++;
    const c = this.at();
    if (c === 0x30) this.pos++;
    else if (c > 0x30 && c <= 0x39) { while (this.at() >= 0x30 && this.at() <= 0x39) this.pos++; }
    else throw this.refuse("number_spelling");
    if (this.at() === 0x2e) { this.pos++; this.someDigits(); }
    if (this.at() === 0x65 || this.at() === 0x45) {
      this.pos++;
      if (this.at() === 0x2b || this.at() === 0x2d) this.pos++;
      this.someDigits();
    }
  }

  skipContainer() {
    const opener = this.at();
    const shut = opener === 0x7b ? 0x7d : 0x5d;
    this.enter();
    this.pos++;
    this.ws();
    const seen = new Set();
    if (this.at() !== shut) {
      for (;;) {
        this.ws();
        if (opener === 0x7b) {
          if (this.at() !== 0x22) throw this.refuse("malformed");
          const k = this.string();
          this.ws();
          if (this.at() !== 0x3a) throw this.refuse("malformed");
          this.pos++;
          this.ws();
        }
        this.skipValue();
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== shut) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
  }
}

function strMap(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const out = Object.create(null);
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const k = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      out[k] = r.string();
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  return out;
}

// Existing per-run overrides. Empty strings do not override file values.
export function newRunOverrides() {
  return { nasStore: "", store: "", logSink: "", logService: "" };
}

// Per-key provenance: machine/user file path, or environment/default with empty
// path.
export function newOrigin() {
  return { rung: "", path: "" };
}

// Provenance for every configuration key, including default answers.
export function newOrigins() {
  return { nasStore: newOrigin(), store: newOrigin(), logSink: newOrigin(), logService: newOrigin(), off: newOrigin() };
}

// Existing provider values and provenance. Empty values mean absence. Stamp
// follows values rather than provenance; paths are diagnostic configuration
// data, not permission to access a store.
export function newSnapshot() {
  return { nasStore: "", store: "", logSink: "", logService: "", off: {}, origins: newOrigins(), stamp: "" };
}

// User-rung overrides only. Empty values clear overrides; machine and run
// values never enter this record. The configuration backing-file path is
// selected by the service; path-valued settings grant no provider storage
// authority.
export function newUserSettings() {
  return { nasStore: "", store: "", logSink: "", logService: "", off: {} };
}

// Normalized user-rung content and an opaque content revision. A missing file
// yields empty values; unreadable or unsupported storage is refused. Revision
// may recur when identical content is restored.
export function newUserSnapshot() {
  return { values: newUserSettings(), revision: "" };
}

// Applied returns the written snapshot. Conflict performs no write and returns
// the current snapshot. Forbidden reports an evaluated edit-policy refusal;
// unavailable reports that the edit-policy decision could not be obtained and
// may be retried. Both perform no storage access and carry empty values with an
// empty revision. No outcome merges settings implicitly.
export function newUserReplaceResult() {
  return { outcome: "", snapshot: newUserSnapshot() };
}

// Latest effective configuration, with an opaque cursor bound to provider
// instance and explicit run overrides. snapshot carries a snapshot and new
// cursor; unchanged carries the original cursor and no snapshot. Other outcomes
// carry no snapshot and preserve the supplied cursor. Intermediate revisions
// may be coalesced; this is not an event history. A restarted provider or
// changed override binding gives gap and requires an explicit empty-cursor
// restart.
export function newConfigObservation() {
  return { outcome: "", cursor: "", snapshot: null };
}

function newOAConfigReaderReadArguments() {
  return { overrides: newRunOverrides() };
}

function newOAConfigEditorReadUserArguments() {
  return { };
}

function newOAConfigEditorReplaceUserArguments() {
  return { expectedRevision: "", values: newUserSettings() };
}

function newOAConfigObserverObserveArguments() {
  return { overrides: newRunOverrides(), cursor: "", waitMs: 0n };
}

function newOAServiceFrame() {
  return { version: 0, service: "", method: "", arguments: "" };
}

function newOAServiceReply() {
  return { version: 0, service: "", method: "", ok: false, payload: "" };
}

function newOAServiceError() {
  return { code: "", message: "" };
}

function newOAConfigReaderReadResult() {
  return { value: newSnapshot() };
}

function newOAConfigEditorReadUserResult() {
  return { value: newUserSnapshot() };
}

function newOAConfigEditorReplaceUserResult() {
  return { value: newUserReplaceResult() };
}

function newOAConfigObserverObserveResult() {
  return { value: newConfigObservation() };
}

function readRunOverrides(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newRunOverrides();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "nas_store") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.nasStore = r.string();
      } else if (key === "store") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.store = r.string();
      } else if (key === "log_sink") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.logSink = r.string();
      } else if (key === "log_service") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.logService = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
  return v;
}

function readOrigin(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOrigin();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "rung") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.rung = r.string();
      } else if (key === "path") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.path = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function readOrigins(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOrigins();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "nas_store") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.nasStore = readOrigin(r);
      } else if (key === "store") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.store = readOrigin(r);
      } else if (key === "log_sink") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.logSink = readOrigin(r);
      } else if (key === "log_service") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.logService = readOrigin(r);
      } else if (key === "off") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.off = readOrigin(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 31) >>> 0) !== 31) throw r.refuse("missing_field");
  return v;
}

function readSnapshot(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newSnapshot();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "nas_store") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.nasStore = r.string();
      } else if (key === "store") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.store = r.string();
      } else if (key === "log_sink") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.logSink = r.string();
      } else if (key === "log_service") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.logService = r.string();
      } else if (key === "off") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.off = strMap(r);
      } else if (key === "origins") {
        if (seen & 32) throw r.refuse("duplicate_field");
        seen |= 32;
        v.origins = readOrigins(r);
      } else if (key === "stamp") {
        if (seen & 64) throw r.refuse("duplicate_field");
        seen |= 64;
        v.stamp = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 127) >>> 0) !== 127) throw r.refuse("missing_field");
  return v;
}

function readUserSettings(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newUserSettings();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "nas_store") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.nasStore = r.string();
      } else if (key === "store") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.store = r.string();
      } else if (key === "log_sink") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.logSink = r.string();
      } else if (key === "log_service") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.logService = r.string();
      } else if (key === "off") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.off = strMap(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 31) >>> 0) !== 31) throw r.refuse("missing_field");
  return v;
}

function readUserSnapshot(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newUserSnapshot();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "values") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.values = readUserSettings(r);
      } else if (key === "revision") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.revision = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function readUserReplaceResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newUserReplaceResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "snapshot") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.snapshot = readUserSnapshot(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
    if (v.outcome !== "applied" && v.outcome !== "conflict" && v.outcome !== "forbidden" && v.outcome !== "unavailable") { throw r.refuse("bad_enum"); }
  return v;
}

function readConfigObservation(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newConfigObservation();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "cursor") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.cursor = r.string();
      } else if (key === "snapshot") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.snapshot = readSnapshot(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
    if (v.outcome !== "snapshot" && v.outcome !== "unchanged" && v.outcome !== "gap" && v.outcome !== "unavailable" && v.outcome !== "unsupported" && v.outcome !== "invalid") { throw r.refuse("bad_enum"); }
  return v;
}

function readOAConfigReaderReadArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAConfigReaderReadArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "overrides") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.overrides = readRunOverrides(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOAConfigEditorReadUserArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAConfigEditorReadUserArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (false) {
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  return v;
}

function readOAConfigEditorReplaceUserArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAConfigEditorReplaceUserArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "expected_revision") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.expectedRevision = r.string();
      } else if (key === "values") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.values = readUserSettings(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function readOAConfigObserverObserveArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAConfigObserverObserveArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "overrides") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.overrides = readRunOverrides(r);
      } else if (key === "cursor") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.cursor = r.string();
      } else if (key === "wait_ms") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.waitMs = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 7) >>> 0) !== 7) throw r.refuse("missing_field");
  return v;
}

function readOAServiceFrame(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceFrame();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "version") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.version = Number(r.integer(-2147483648n, 2147483647n));
      } else if (key === "service") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.service = r.string();
      } else if (key === "method") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.method = r.string();
      } else if (key === "arguments") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.arguments = r.rawValue();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
  return v;
}

function readOAServiceReply(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceReply();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "version") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.version = Number(r.integer(-2147483648n, 2147483647n));
      } else if (key === "service") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.service = r.string();
      } else if (key === "method") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.method = r.string();
      } else if (key === "ok") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.ok = r.boolean();
      } else if (key === "payload") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.payload = r.rawValue();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 31) >>> 0) !== 31) throw r.refuse("missing_field");
  return v;
}

function readOAServiceError(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceError();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "code") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.code = r.string();
      } else if (key === "message") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.message = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function readOAConfigReaderReadResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAConfigReaderReadResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readSnapshot(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOAConfigEditorReadUserResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAConfigEditorReadUserResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readUserSnapshot(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOAConfigEditorReplaceUserResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAConfigEditorReplaceUserResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readUserReplaceResult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOAConfigObserverObserveResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAConfigObserverObserveResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readConfigObservation(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

export function decode(data) {
  const r = new Reader(data);
  r.ws();
  const v = readSnapshot(r);
  r.ws();
  if (r.pos < r.buf.length) throw r.refuse("trailing_bytes");
  return v;
}

// refusals is in the order two of them are chosen between.
const refusals = ["malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"];

function refusalRank(word) {
  return refusals.indexOf(word);
}

export class DispatchError extends Error {
  constructor(code) { super(code); this.name = "DispatchError"; this.code = code; }
}
export class ServiceError extends Error {
  constructor(code, message = "") { super(message || code); this.name = "ServiceError"; this.code = code; }
}
function _serviceDecode(decoder, frame, depth) {
  const reader = new Reader(typeof frame === "string" ? ENC.encode(frame) : frame);
  reader.depth = depth; reader.ws();
  const value = decoder(reader); reader.ws();
  if (reader.pos !== reader.buf.length) throw reader.refuse("trailing_bytes");
  return value;
}
function _serviceEncode(encoder, value, depth) {
  const out = new Out(); encoder(out, value, depth); return out.bytes();
}
function _serviceCheck(kind, value, depth = 0) {
  if (depth > DEPTH_LIMIT) throw new Refusal("depth_exceeded", 0);
  let valid = false;
  if (kind === "string") {
    valid = typeof value === "string";
    if (valid) for (const ch of value) {
      const cp = ch.codePointAt(0);
      if (cp >= 0xd800 && cp <= 0xdfff) throw new Refusal("bad_string", 0);
    }
  } else if (kind === "i32") {
    valid = typeof value === "number" && Number.isInteger(value) && value >= -2147483648 && value <= 2147483647;
  } else if (kind === "i64") {
    valid = typeof value === "bigint" && value >= -9223372036854775808n && value <= 9223372036854775807n;
  } else if (kind === "bool") valid = typeof value === "boolean";
  else if (kind === "json") {
    valid = typeof value === "string" || value instanceof Uint8Array;
    if (valid) { const r = new Reader(typeof value === "string" ? ENC.encode(value) : value); r.depth = depth; r.ws(); r.rawValue(); r.ws(); if (r.pos !== r.buf.length) throw r.refuse("trailing_bytes"); }
  } else if (kind.startsWith("list<")) {
    valid = Array.isArray(value);
    if (valid) for (const item of value) _serviceCheck(kind.slice(5,-1), item, depth + 1);
  } else if (kind.startsWith("map<string,")) {
    valid = value !== null && typeof value === "object" && !Array.isArray(value);
    if (valid) for (const [key,item] of Object.entries(value)) { _serviceCheck("string",key,depth+1); _serviceCheck(kind.slice(11,-1),item,depth+1); }
  } else {
    const fields = _serviceRecords[kind];
    valid = fields !== undefined && value !== null && typeof value === "object" && !Array.isArray(value);
    if (valid) for (const [name,type,omit] of fields) {
      if (!Object.hasOwn(value,name)) throw new Refusal("missing_field",0);
      const item = value[name];
      if (omit === "absent" && item === null) continue;
      _serviceCheck(type,item,depth+1);
    }
  }
  if (!valid) throw new Refusal("wrong_type", 0);
}

const _serviceRecords = Object.create(null);
_serviceRecords["RunOverrides"] = [["nasStore","string","never"],["store","string","never"],["logSink","string","never"],["logService","string","never"],];
_serviceRecords["Origin"] = [["rung","string","never"],["path","string","never"],];
_serviceRecords["Origins"] = [["nasStore","Origin","never"],["store","Origin","never"],["logSink","Origin","never"],["logService","Origin","never"],["off","Origin","never"],];
_serviceRecords["Snapshot"] = [["nasStore","string","never"],["store","string","never"],["logSink","string","never"],["logService","string","never"],["off","map<string,string>","never"],["origins","Origins","never"],["stamp","string","never"],];
_serviceRecords["UserSettings"] = [["nasStore","string","never"],["store","string","never"],["logSink","string","never"],["logService","string","never"],["off","map<string,string>","never"],];
_serviceRecords["UserSnapshot"] = [["values","UserSettings","never"],["revision","string","never"],];
_serviceRecords["UserReplaceResult"] = [["outcome","string","never"],["snapshot","UserSnapshot","never"],];
_serviceRecords["ConfigObservation"] = [["outcome","string","never"],["cursor","string","never"],["snapshot","Snapshot","absent"],];
_serviceRecords["OAConfigReaderReadArguments"] = [["overrides","RunOverrides","never"],];
_serviceRecords["OAConfigEditorReadUserArguments"] = [];
_serviceRecords["OAConfigEditorReplaceUserArguments"] = [["expectedRevision","string","never"],["values","UserSettings","never"],];
_serviceRecords["OAConfigObserverObserveArguments"] = [["overrides","RunOverrides","never"],["cursor","string","never"],["waitMs","i64","never"],];
_serviceRecords["OAServiceFrame"] = [["version","i32","never"],["service","string","never"],["method","string","never"],["arguments","json","never"],];
_serviceRecords["OAServiceReply"] = [["version","i32","never"],["service","string","never"],["method","string","never"],["ok","bool","never"],["payload","json","never"],];
_serviceRecords["OAServiceError"] = [["code","string","never"],["message","string","never"],];
_serviceRecords["OAConfigReaderReadResult"] = [["value","Snapshot","never"],];
_serviceRecords["OAConfigEditorReadUserResult"] = [["value","UserSnapshot","never"],];
_serviceRecords["OAConfigEditorReplaceUserResult"] = [["value","UserReplaceResult","never"],];
_serviceRecords["OAConfigObserverObserveResult"] = [["value","ConfigObservation","never"],];

function _serviceRequest(service, method, argumentsBytes) {
  return _serviceEncode(writeOAServiceFrame, {
    version:1, service, method, arguments:new TextDecoder("utf-8",{fatal:true}).decode(argumentsBytes)
  },0);
}

function _serviceResponse(frame, service, method) {
  if (!(frame instanceof Uint8Array)) throw new TypeError("transport frame must be Uint8Array");
  const reply = _serviceDecode(readOAServiceReply, frame, 0);
  if (reply.version !== 1) throw new DispatchError("unknown_version");
  if (reply.service !== service || reply.method !== method) throw new DispatchError("mismatched_response");
  if (!reply.ok) {
    const error = _serviceDecode(readOAServiceError, reply.payload, 1);
    if (!error.code) throw new DispatchError("invalid_error");
    throw new ServiceError(error.code, error.message);
  }
  return reply.payload;
}

export class ConfigReaderClient {
  constructor(transport) { this._transport = transport; }

  async read(overrides) {
    const _args = newOAConfigReaderReadArguments();
    _args.overrides = overrides;
    _serviceCheck("OAConfigReaderReadArguments", _args);
    const _payload = _serviceEncode(writeOAConfigReaderReadArguments, _args, 1);
    _serviceDecode(readOAConfigReaderReadArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.config/reader@1", "Read", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.config/reader@1", "Read");
    const _result = _serviceDecode(readOAConfigReaderReadResult, _reply, 1);
    return _result.value;
  }
}
export const ConfigReaderService = Object.freeze({wireName:"abstraction.config/reader@1",Client:ConfigReaderClient});

export class ConfigEditorClient {
  constructor(transport) { this._transport = transport; }

  async readUser() {
    const _args = newOAConfigEditorReadUserArguments();
    _serviceCheck("OAConfigEditorReadUserArguments", _args);
    const _payload = _serviceEncode(writeOAConfigEditorReadUserArguments, _args, 1);
    _serviceDecode(readOAConfigEditorReadUserArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.config/editor@1", "ReadUser", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.config/editor@1", "ReadUser");
    const _result = _serviceDecode(readOAConfigEditorReadUserResult, _reply, 1);
    return _result.value;
  }

  async replaceUser(expectedRevision, values) {
    const _args = newOAConfigEditorReplaceUserArguments();
    _args.expectedRevision = expectedRevision;
    _args.values = values;
    _serviceCheck("OAConfigEditorReplaceUserArguments", _args);
    const _payload = _serviceEncode(writeOAConfigEditorReplaceUserArguments, _args, 1);
    _serviceDecode(readOAConfigEditorReplaceUserArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.config/editor@1", "ReplaceUser", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.config/editor@1", "ReplaceUser");
    const _result = _serviceDecode(readOAConfigEditorReplaceUserResult, _reply, 1);
    return _result.value;
  }
}
export const ConfigEditorService = Object.freeze({wireName:"abstraction.config/editor@1",Client:ConfigEditorClient});

export class ConfigObserverClient {
  constructor(transport) { this._transport = transport; }

  async observe(overrides, cursor, waitMs) {
    const _args = newOAConfigObserverObserveArguments();
    _args.overrides = overrides;
    _args.cursor = cursor;
    _args.waitMs = waitMs;
    _serviceCheck("OAConfigObserverObserveArguments", _args);
    const _payload = _serviceEncode(writeOAConfigObserverObserveArguments, _args, 1);
    _serviceDecode(readOAConfigObserverObserveArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.config/observer@1", "Observe", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.config/observer@1", "Observe");
    const _result = _serviceDecode(readOAConfigObserverObserveResult, _reply, 1);
    return _result.value;
  }
}
export const ConfigObserverService = Object.freeze({wireName:"abstraction.config/observer@1",Client:ConfigObserverClient});
