# Code generated by abstraction-idl from abstraction-config/config.thrift. DO NOT EDIT.

"""abstraction.config: generated contract types, vocabularies and service clients."""

from ._codec import (
    ConfigEditor,
    ConfigEditorClient,
    ConfigObservation,
    ConfigObservationOutcome,
    ConfigObserver,
    ConfigObserverClient,
    ConfigReader,
    ConfigReaderClient,
    DispatchError,
    EDITOR_ERROR_CODES,
    Origin,
    Origins,
    READER_ERROR_CODES,
    Refusal,
    RunOverrides,
    ServiceError,
    ServiceErrorCode,
    Snapshot,
    UserReplaceOutcome,
    UserReplaceResult,
    UserSettings,
    UserSnapshot,
    decode,
    encode,
    service_name,
)

__all__ = [
    "ConfigEditor",
    "ConfigEditorClient",
    "ConfigObservation",
    "ConfigObservationOutcome",
    "ConfigObserver",
    "ConfigObserverClient",
    "ConfigReader",
    "ConfigReaderClient",
    "DispatchError",
    "EDITOR_ERROR_CODES",
    "Origin",
    "Origins",
    "READER_ERROR_CODES",
    "Refusal",
    "RunOverrides",
    "ServiceError",
    "ServiceErrorCode",
    "Snapshot",
    "UserReplaceOutcome",
    "UserReplaceResult",
    "UserSettings",
    "UserSnapshot",
    "decode",
    "encode",
    "service_name",
]

# Report every class and function as a member of this package, so help(),
# tracebacks and pickles name the import an application writes.
for _name in __all__:
    _value = globals()[_name]
    if isinstance(_value, type) or callable(_value):
        _value.__module__ = __name__
del _name, _value
