# Code generated by abstraction-idl from abstraction-config/config.thrift. DO NOT EDIT.

from __future__ import annotations

import dataclasses
import enum

_HEX = b"0123456789abcdef"
_WS = (0x20, 0x09, 0x0A, 0x0D)
_SHORT = {0x22: b'\\"', 0x5C: b"\\\\", 0x08: b"\\b", 0x0C: b"\\f",
          0x0A: b"\\n", 0x0D: b"\\r", 0x09: b"\\t"}


def _esc_byte(out, c):
    short = _SHORT.get(c)
    if short is not None:
        out += short
    elif c < 0x20:
        out += b"\\u00" + bytes([_HEX[c >> 4], _HEX[c & 0xF]])
    else:
        out.append(c)


def _num(out, n):
    out += str(int(n)).encode("ascii")


def _pad(out, depth):
    out += b" " * (depth * 2)


def _strs(out, v, depth):
    if not v:
        out += b"[]"
        return
    out += b"[\n"
    for i, s in enumerate(v):
        _pad(out, depth + 1)
        _esc(out, s)
        if i + 1 < len(v):
            out += b","
        out += b"\n"
    _pad(out, depth)
    out += b"]"


def _raw(out, s, depth):
    b = s.encode("utf-8") if isinstance(s, str) else s
    i, n = 0, len(b)
    while i < n:
        c = b[i]
        if c in _WS:
            i += 1
        elif c == 0x22:
            j = i + 1
            while j < n:
                if b[j] == 0x5C:
                    j += 2
                    continue
                if b[j] == 0x22:
                    j += 1
                    break
                j += 1
            out += b[i:j]
            i = j
        elif c in (0x7B, 0x5B):
            out.append(c)
            i += 1
            j = i
            while j < n and b[j] in _WS:
                j += 1
            if j < n and b[j] in (0x7D, 0x5D):
                out.append(b[j])
                i = j + 1
            else:
                depth += 1
                out += b"\n"
                _pad(out, depth)
        elif c in (0x7D, 0x5D):
            depth -= 1
            out += b"\n"
            _pad(out, depth)
            out.append(c)
            i += 1
        elif c == 0x2C:
            out += b",\n"
            _pad(out, depth)
            i += 1
        elif c == 0x3A:
            out += b": "
            i += 1
        else:
            out.append(c)
            i += 1


def _rawmap(out, m, depth):
    keys = sorted(m, key=lambda k: k.encode("utf-8"))
    if not keys:
        out += b"{}"
        return
    out += b"{\n"
    for i, k in enumerate(keys):
        _pad(out, depth + 1)
        _esc(out, k)
        out += b": "
        _raw(out, m[k], depth + 1)
        if i + 1 < len(keys):
            out += b","
        out += b"\n"
    _pad(out, depth)
    out += b"}"

def _esc(out, s):
    out += b'"'
    for c in s.encode("utf-8"):
        _esc_byte(out, c)
    out += b'"'


def _strmap(out, m, depth):
    keys = sorted(m, key=lambda k: k.encode("utf-8"))
    if not keys:
        out += b"{}"
        return
    out += b"{\n"
    for i, k in enumerate(keys):
        _pad(out, depth + 1)
        _esc(out, k)
        out += b": "
        _esc(out, m[k])
        if i + 1 < len(keys):
            out += b","
        out += b"\n"
    _pad(out, depth)
    out += b"}"


try:
    from enum import StrEnum as _StrEnum
except ImportError:  # Python 3.10
    class _StrEnum(str, enum.Enum):
        def __str__(self):
            return self.value


def _closed_enum(cls, value):
    if value is not None and not isinstance(value, str):
        raise Refusal("wrong_type", 0)
    try:
        cls(value)
    except ValueError:
        raise Refusal("bad_enum", 0) from None


def _open_enum(cls, value):
    try:
        return cls(value)
    except ValueError:
        return value


class UserReplaceOutcome(_StrEnum):
    APPLIED = "applied"
    CONFLICT = "conflict"
    FORBIDDEN = "forbidden"
    UNAVAILABLE = "unavailable"


class ConfigObservationOutcome(_StrEnum):
    SNAPSHOT = "snapshot"
    UNCHANGED = "unchanged"
    GAP = "gap"
    UNAVAILABLE = "unavailable"
    UNSUPPORTED = "unsupported"
    INVALID = "invalid"


class ServiceErrorCode(_StrEnum):
    HANDLER_ERROR = "handler_error"
    INVALID_RESULT = "invalid_result"
    UNKNOWN_VERSION = "unknown_version"
    UNKNOWN_SERVICE = "unknown_service"
    UNKNOWN_METHOD = "unknown_method"
    WRONG_MODE = "wrong_mode"
    STORAGE_UNAVAILABLE = "storage_unavailable"
    CALLER_UNAVAILABLE = "caller_unavailable"
    IDENTITY_REQUIRED = "identity_required"
    WRONG_USER = "wrong_user"
    INVALID_REVISION = "invalid_revision"


READER_ERROR_CODES = ["storage_unavailable", "caller_unavailable", "identity_required", "wrong_user"]


EDITOR_ERROR_CODES = ["invalid_revision", "storage_unavailable", "caller_unavailable", "identity_required", "wrong_user"]


@dataclasses.dataclass(kw_only=True)
class RunOverrides:
    """Existing per-run overrides. Empty strings do not override file values."""

    nas_store: str = ""
    store: str = ""
    log_sink: str = ""
    log_service: str = ""


@dataclasses.dataclass(kw_only=True)
class Origin:
    """Per-key provenance: machine/user file path, or environment/default with
    empty path."""

    rung: str = ""
    path: str = ""


@dataclasses.dataclass(kw_only=True)
class Origins:
    """Provenance for every configuration key, including default answers."""

    nas_store: Origin = dataclasses.field(default_factory=Origin)
    store: Origin = dataclasses.field(default_factory=Origin)
    log_sink: Origin = dataclasses.field(default_factory=Origin)
    log_service: Origin = dataclasses.field(default_factory=Origin)
    off: Origin = dataclasses.field(default_factory=Origin)


@dataclasses.dataclass(kw_only=True)
class Snapshot:
    """Existing provider values and provenance. Empty values mean absence. Stamp
    follows values rather than provenance; paths are diagnostic configuration
    data, not permission to access a store."""

    nas_store: str = ""
    store: str = ""
    log_sink: str = ""
    log_service: str = ""
    off: dict[str, str] = dataclasses.field(default_factory=dict)
    origins: Origins = dataclasses.field(default_factory=Origins)
    stamp: str = ""


@dataclasses.dataclass(kw_only=True)
class UserSettings:
    """User-rung overrides only. Empty values clear overrides; machine and run
    values never enter this record. The configuration backing-file path is
    selected by the service; path-valued settings grant no provider storage
    authority."""

    nas_store: str = ""
    store: str = ""
    log_sink: str = ""
    log_service: str = ""
    off: dict[str, str] = dataclasses.field(default_factory=dict)


@dataclasses.dataclass(kw_only=True)
class UserSnapshot:
    """Normalized user-rung content and an opaque content revision. A missing file
    yields empty values; unreadable or unsupported storage is refused. Revision
    may recur when identical content is restored."""

    values: UserSettings = dataclasses.field(default_factory=UserSettings)
    revision: str = ""


@dataclasses.dataclass(kw_only=True)
class UserReplaceResult:
    """Applied returns the written snapshot. Conflict performs no write and returns
    the current snapshot. Forbidden reports an evaluated edit-policy refusal;
    unavailable reports that the edit-policy decision could not be obtained and
    may be retried. Both perform no storage access and carry empty values with
    an empty revision. No outcome merges settings implicitly."""

    outcome: UserReplaceOutcome | None = None
    snapshot: UserSnapshot = dataclasses.field(default_factory=UserSnapshot)


@dataclasses.dataclass(kw_only=True)
class ConfigObservation:
    """Latest effective configuration, with an opaque cursor bound to provider
    instance and explicit run overrides. snapshot carries a snapshot and new
    cursor; unchanged carries the original cursor and no snapshot. Other
    outcomes carry no snapshot and preserve the supplied cursor. Intermediate
    revisions may be coalesced; this is not an event history. A restarted
    provider or changed override binding gives gap and requires an explicit
    empty-cursor restart."""

    outcome: ConfigObservationOutcome | None = None
    cursor: str = ""
    snapshot: Snapshot | None = None


@dataclasses.dataclass(kw_only=True)
class _ConfigReaderReadArguments:
    overrides: RunOverrides = dataclasses.field(default_factory=RunOverrides)


@dataclasses.dataclass(kw_only=True)
class _ConfigEditorReadUserArguments:
    pass


@dataclasses.dataclass(kw_only=True)
class _ConfigEditorReplaceUserArguments:
    expected_revision: str = ""
    values: UserSettings = dataclasses.field(default_factory=UserSettings)


@dataclasses.dataclass(kw_only=True)
class _ConfigObserverObserveArguments:
    overrides: RunOverrides = dataclasses.field(default_factory=RunOverrides)
    cursor: str = ""
    wait_ms: int = 0


@dataclasses.dataclass(kw_only=True)
class _ServiceFrame:
    version: int = 0
    service: str = ""
    method: str = ""
    arguments: bytes | str = ""


@dataclasses.dataclass(kw_only=True)
class _ServiceReply:
    version: int = 0
    service: str = ""
    method: str = ""
    ok: bool = False
    payload: bytes | str = ""


@dataclasses.dataclass(kw_only=True)
class _ServiceError:
    code: str = ""
    message: str = ""


@dataclasses.dataclass(kw_only=True)
class _ConfigReaderReadResult:
    value: Snapshot = dataclasses.field(default_factory=Snapshot)


@dataclasses.dataclass(kw_only=True)
class _ConfigEditorReadUserResult:
    value: UserSnapshot = dataclasses.field(default_factory=UserSnapshot)


@dataclasses.dataclass(kw_only=True)
class _ConfigEditorReplaceUserResult:
    value: UserReplaceResult = dataclasses.field(default_factory=UserReplaceResult)


@dataclasses.dataclass(kw_only=True)
class _ConfigObserverObserveResult:
    value: ConfigObservation = dataclasses.field(default_factory=ConfigObservation)


def _write_run_overrides(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "nas_store")
    out += b": "
    _esc(out, v.nas_store)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "store")
    out += b": "
    _esc(out, v.store)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "log_sink")
    out += b": "
    _esc(out, v.log_sink)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "log_service")
    out += b": "
    _esc(out, v.log_service)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_origin(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "rung")
    out += b": "
    _esc(out, v.rung)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "path")
    out += b": "
    _esc(out, v.path)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_origins(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "nas_store")
    out += b": "
    _write_origin(out, v.nas_store, depth + 1)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "store")
    out += b": "
    _write_origin(out, v.store, depth + 1)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "log_sink")
    out += b": "
    _write_origin(out, v.log_sink, depth + 1)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "log_service")
    out += b": "
    _write_origin(out, v.log_service, depth + 1)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "off")
    out += b": "
    _write_origin(out, v.off, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_snapshot(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "nas_store")
    out += b": "
    _esc(out, v.nas_store)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "store")
    out += b": "
    _esc(out, v.store)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "log_sink")
    out += b": "
    _esc(out, v.log_sink)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "log_service")
    out += b": "
    _esc(out, v.log_service)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "off")
    out += b": "
    _strmap(out, v.off, depth + 1)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "origins")
    out += b": "
    _write_origins(out, v.origins, depth + 1)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "stamp")
    out += b": "
    _esc(out, v.stamp)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_user_settings(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "nas_store")
    out += b": "
    _esc(out, v.nas_store)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "store")
    out += b": "
    _esc(out, v.store)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "log_sink")
    out += b": "
    _esc(out, v.log_sink)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "log_service")
    out += b": "
    _esc(out, v.log_service)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "off")
    out += b": "
    _strmap(out, v.off, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_user_snapshot(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "values")
    out += b": "
    _write_user_settings(out, v.values, depth + 1)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "revision")
    out += b": "
    _esc(out, v.revision)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_user_replace_result(out, v, depth):
    _closed_enum(UserReplaceOutcome, v.outcome)
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "outcome")
    out += b": "
    _esc(out, v.outcome)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "snapshot")
    out += b": "
    _write_user_snapshot(out, v.snapshot, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_config_observation(out, v, depth):
    _closed_enum(ConfigObservationOutcome, v.outcome)
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "outcome")
    out += b": "
    _esc(out, v.outcome)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "cursor")
    out += b": "
    _esc(out, v.cursor)
    if v.snapshot is not None:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "snapshot")
        out += b": "
        _write_snapshot(out, v.snapshot, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_config_reader_read_arguments(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "overrides")
    out += b": "
    _write_run_overrides(out, v.overrides, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_config_editor_read_user_arguments(out, v, depth):
    out += b"{"
    out += b"}"


def _write_oa_config_editor_replace_user_arguments(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "expected_revision")
    out += b": "
    _esc(out, v.expected_revision)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "values")
    out += b": "
    _write_user_settings(out, v.values, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_config_observer_observe_arguments(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "overrides")
    out += b": "
    _write_run_overrides(out, v.overrides, depth + 1)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "cursor")
    out += b": "
    _esc(out, v.cursor)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "wait_ms")
    out += b": "
    _num(out, v.wait_ms)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_service_frame(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "version")
    out += b": "
    _num(out, v.version)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "service")
    out += b": "
    _esc(out, v.service)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "method")
    out += b": "
    _esc(out, v.method)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "arguments")
    out += b": "
    out += v.arguments.encode("utf-8") if isinstance(v.arguments, str) else v.arguments
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_service_reply(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "version")
    out += b": "
    _num(out, v.version)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "service")
    out += b": "
    _esc(out, v.service)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "method")
    out += b": "
    _esc(out, v.method)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "ok")
    out += b": "
    out += b"true" if v.ok else b"false"
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "payload")
    out += b": "
    out += v.payload.encode("utf-8") if isinstance(v.payload, str) else v.payload
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_service_error(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "code")
    out += b": "
    _esc(out, v.code)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "message")
    out += b": "
    _esc(out, v.message)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_config_reader_read_result(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "value")
    out += b": "
    _write_snapshot(out, v.value, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_config_editor_read_user_result(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "value")
    out += b": "
    _write_user_snapshot(out, v.value, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_config_editor_replace_user_result(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "value")
    out += b": "
    _write_user_replace_result(out, v.value, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_config_observer_observe_result(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "value")
    out += b": "
    _write_config_observation(out, v.value, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def encode(v):
    out = bytearray()
    _write_snapshot(out, v, 0)
    out += b"\n"
    return bytes(out)


_QUOTE, _BACKSLASH, _COLON, _COMMA = 0x22, 0x5C, 0x3A, 0x2C
_LBRACE, _RBRACE, _LBRACK, _RBRACK = 0x7B, 0x7D, 0x5B, 0x5D
_MINUS, _ZERO, _NINE, _DOT, _LOWER_U, _LOWER_N = 0x2D, 0x30, 0x39, 0x2E, 0x75, 0x6E
_UNESCAPE = {0x22: 0x22, 0x5C: 0x5C, 0x2F: 0x2F, 0x62: 0x08,
             0x66: 0x0C, 0x6E: 0x0A, 0x72: 0x0D, 0x74: 0x09}
_DEPTH_LIMIT = 64
_I64_DIGITS = 19


class Refusal(ValueError):
    """Bytes the contract refuses: word names the rule, offset the byte."""

    def __init__(self, word, offset):
        super().__init__("refused: %s at byte %d" % (word, offset))
        self.word = word
        self.offset = offset


class _Reader:
    __slots__ = ("buf", "pos", "depth")

    def __init__(self, buf):
        self.buf = buf
        self.pos = 0
        self.depth = 0

    def refuse(self, word):
        return Refusal(word, self.pos)

    def at(self):
        return self.buf[self.pos] if self.pos < len(self.buf) else 0

    def ws(self):
        while self.pos < len(self.buf) and self.buf[self.pos] in _WS:
            self.pos += 1

    def enter(self):
        self.depth += 1
        if self.depth > _DEPTH_LIMIT:
            raise self.refuse("depth_exceeded")

    def digit(self):
        return _ZERO <= self.at() <= _NINE

    def string(self):
        if self.at() != _QUOTE:
            raise self.refuse("wrong_type")
        self.pos += 1
        out = bytearray()
        while True:
            if self.pos >= len(self.buf):
                raise self.refuse("malformed")
            c = self.buf[self.pos]
            if c == _QUOTE:
                self.pos += 1
                try:
                    return out.decode("utf-8")
                except UnicodeDecodeError:
                    raise self.refuse("bad_string") from None
            if c < 0x20:
                raise self.refuse("bad_string")
            if c == _BACKSLASH:
                self.escape(out)
            else:
                out.append(c)
                self.pos += 1

    def escape(self, out):
        self.pos += 1
        if self.pos >= len(self.buf):
            raise self.refuse("malformed")
        c = self.buf[self.pos]
        self.pos += 1
        plain = _UNESCAPE.get(c)
        if plain is not None:
            out.append(plain)
            return
        if c != _LOWER_U:
            raise self.refuse("bad_string")
        u = self.hex4()
        if 0xDC00 <= u <= 0xDFFF:
            raise self.refuse("bad_string")
        if 0xD800 <= u <= 0xDBFF:
            if (self.pos + 1 >= len(self.buf) or self.buf[self.pos] != _BACKSLASH
                    or self.buf[self.pos + 1] != _LOWER_U):
                raise self.refuse("bad_string")
            self.pos += 2
            low = self.hex4()
            if not 0xDC00 <= low <= 0xDFFF:
                raise self.refuse("bad_string")
            u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00)
        out += chr(u).encode("utf-8")

    def hex4(self):
        if self.pos + 4 > len(self.buf):
            raise self.refuse("bad_string")
        u = 0
        for i in range(4):
            c = self.buf[self.pos + i]
            if _ZERO <= c <= _NINE:
                u = u << 4 | (c - _ZERO)
            elif 0x61 <= c <= 0x66:
                u = u << 4 | (c - 0x61 + 10)
            elif 0x41 <= c <= 0x46:
                u = u << 4 | (c - 0x41 + 10)
            else:
                raise self.refuse("bad_string")
        self.pos += 4
        return u

    def integer(self, low, high):
        c = self.at()
        if c != _MINUS and not _ZERO <= c <= _NINE:
            raise self.refuse("wrong_type")
        negative = c == _MINUS
        if negative:
            self.pos += 1
        if not self.digit():
            raise self.refuse("malformed")
        start = self.pos
        if self.at() == _ZERO:
            self.pos += 1
        else:
            while self.digit():
                self.pos += 1
        if self.at() in (_DOT, 0x65, 0x45) or self.digit():
            raise self.refuse("number_spelling")
        if self.pos - start > _I64_DIGITS:
            raise self.refuse("number_spelling")
        n = int(self.buf[start:self.pos])
        if negative:
            if n == 0:
                raise self.refuse("number_spelling")
            n = -n
        if n < low or n > high:
            raise self.refuse("number_spelling")
        return n

    def boolean(self):
        if self.at() == 0x74:
            self.literal(b"true")
            return True
        if self.at() == 0x66:
            self.literal(b"false")
            return False
        raise self.refuse("wrong_type")

    def literal(self, word):
        if self.buf[self.pos:self.pos + len(word)] != word:
            raise self.refuse("malformed")
        self.pos += len(word)

    def str_list(self):
        if self.at() != _LBRACK:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = []
        self.ws()
        if self.at() != _RBRACK:
            while True:
                self.ws()
                out.append(self.string())
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACK:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out

    def raw_map(self):
        if self.at() != _LBRACE:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = {}
        self.ws()
        if self.at() != _RBRACE:
            while True:
                self.ws()
                if self.at() != _QUOTE:
                    raise self.refuse("malformed")
                k = self.string()
                self.ws()
                if self.at() != _COLON:
                    raise self.refuse("malformed")
                self.pos += 1
                self.ws()
                out[k] = self.raw_value()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACE:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out

    def raw_value(self):
        start = self.pos
        self.skip_value()
        return self.buf[start:self.pos]

    def skip_value(self):
        c = self.at()
        if c == _QUOTE:
            self.skip_string()
        elif c in (_LBRACE, _LBRACK):
            self.skip_container()
        elif c == 0x74:
            self.literal(b"true")
        elif c == 0x66:
            self.literal(b"false")
        elif c == 0x6E:
            self.literal(b"null")
        elif c == _MINUS or _ZERO <= c <= _NINE:
            self.skip_number()
        else:
            raise self.refuse("malformed")

    # An opaque value is validated and carried, never interpreted. Its syntax is
    # the record's own — the same string reader, so an escape, a control byte or
    # a lone surrogate is judged identically at any depth — and what it is free
    # to spell, it keeps: the bytes between these two offsets are what a writer
    # re-emits. A number is walked, never converted, so a value no host type
    # holds survives the reader that carried it.
    def skip_string(self):
        self.string()

    def some_digits(self):
        n = 0
        while _ZERO <= self.at() <= _NINE:
            self.pos += 1
            n += 1
        if n == 0:
            raise self.refuse("number_spelling")

    def skip_number(self):
        if self.at() == _MINUS:
            self.pos += 1
        c = self.at()
        if c == _ZERO:
            self.pos += 1
        elif _ZERO < c <= _NINE:
            while _ZERO <= self.at() <= _NINE:
                self.pos += 1
        else:
            raise self.refuse("number_spelling")
        if self.at() == _DOT:
            self.pos += 1
            self.some_digits()
        if self.at() in (0x65, 0x45):
            self.pos += 1
            if self.at() in (0x2B, _MINUS):
                self.pos += 1
            self.some_digits()

    def skip_container(self):
        opener = self.at()
        shut = _RBRACE if opener == _LBRACE else _RBRACK
        self.enter()
        self.pos += 1
        self.ws()
        seen = set()
        if self.at() != shut:
            while True:
                self.ws()
                if opener == _LBRACE:
                    if self.at() != _QUOTE:
                        raise self.refuse("malformed")
                    k = self.string()
                    self.ws()
                    if self.at() != _COLON:
                        raise self.refuse("malformed")
                    self.pos += 1
                    self.ws()
                self.skip_value()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != shut:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1

    def str_map(self):
        if self.at() != _LBRACE:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = {}
        self.ws()
        if self.at() != _RBRACE:
            while True:
                self.ws()
                if self.at() != _QUOTE:
                    raise self.refuse("malformed")
                k = self.string()
                self.ws()
                if self.at() != _COLON:
                    raise self.refuse("malformed")
                self.pos += 1
                self.ws()
                out[k] = self.string()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACE:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out


def _read_run_overrides(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = RunOverrides()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "nas_store":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.nas_store = r.string()
            elif key == "store":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.store = r.string()
            elif key == "log_sink":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.log_sink = r.string()
            elif key == "log_service":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.log_service = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 15 != 15:
        raise r.refuse("missing_field")
    return v


def _read_origin(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Origin()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "rung":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.rung = r.string()
            elif key == "path":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.path = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _read_origins(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Origins()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "nas_store":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.nas_store = _read_origin(r)
            elif key == "store":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.store = _read_origin(r)
            elif key == "log_sink":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.log_sink = _read_origin(r)
            elif key == "log_service":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.log_service = _read_origin(r)
            elif key == "off":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.off = _read_origin(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 31 != 31:
        raise r.refuse("missing_field")
    return v


def _read_snapshot(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Snapshot()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "nas_store":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.nas_store = r.string()
            elif key == "store":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.store = r.string()
            elif key == "log_sink":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.log_sink = r.string()
            elif key == "log_service":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.log_service = r.string()
            elif key == "off":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.off = r.str_map()
            elif key == "origins":
                if seen & 32:
                    raise r.refuse("duplicate_field")
                seen |= 32
                v.origins = _read_origins(r)
            elif key == "stamp":
                if seen & 64:
                    raise r.refuse("duplicate_field")
                seen |= 64
                v.stamp = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 127 != 127:
        raise r.refuse("missing_field")
    return v


def _read_user_settings(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = UserSettings()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "nas_store":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.nas_store = r.string()
            elif key == "store":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.store = r.string()
            elif key == "log_sink":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.log_sink = r.string()
            elif key == "log_service":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.log_service = r.string()
            elif key == "off":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.off = r.str_map()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 31 != 31:
        raise r.refuse("missing_field")
    return v


def _read_user_snapshot(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = UserSnapshot()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "values":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.values = _read_user_settings(r)
            elif key == "revision":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.revision = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _read_user_replace_result(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = UserReplaceResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "outcome":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.outcome = r.string()
            elif key == "snapshot":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.snapshot = _read_user_snapshot(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    try:
        v.outcome = UserReplaceOutcome(v.outcome)
    except ValueError:
        raise r.refuse("bad_enum") from None
    return v


def _read_config_observation(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = ConfigObservation()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "outcome":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.outcome = r.string()
            elif key == "cursor":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.cursor = r.string()
            elif key == "snapshot":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.snapshot = _read_snapshot(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    try:
        v.outcome = ConfigObservationOutcome(v.outcome)
    except ValueError:
        raise r.refuse("bad_enum") from None
    return v


def _read_oa_config_reader_read_arguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _ConfigReaderReadArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "overrides":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.overrides = _read_run_overrides(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _read_oa_config_editor_read_user_arguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _ConfigEditorReadUserArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if False:
                pass
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    return v


def _read_oa_config_editor_replace_user_arguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _ConfigEditorReplaceUserArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "expected_revision":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.expected_revision = r.string()
            elif key == "values":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.values = _read_user_settings(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _read_oa_config_observer_observe_arguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _ConfigObserverObserveArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "overrides":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.overrides = _read_run_overrides(r)
            elif key == "cursor":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.cursor = r.string()
            elif key == "wait_ms":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.wait_ms = r.integer(-9223372036854775808, 9223372036854775807)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 7 != 7:
        raise r.refuse("missing_field")
    return v


def _read_oa_service_frame(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _ServiceFrame()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "version":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.version = r.integer(-2147483648, 2147483647)
            elif key == "service":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.service = r.string()
            elif key == "method":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.method = r.string()
            elif key == "arguments":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.arguments = r.raw_value()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 15 != 15:
        raise r.refuse("missing_field")
    return v


def _read_oa_service_reply(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _ServiceReply()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "version":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.version = r.integer(-2147483648, 2147483647)
            elif key == "service":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.service = r.string()
            elif key == "method":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.method = r.string()
            elif key == "ok":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.ok = r.boolean()
            elif key == "payload":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.payload = r.raw_value()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 31 != 31:
        raise r.refuse("missing_field")
    return v


def _read_oa_service_error(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _ServiceError()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "code":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.code = r.string()
            elif key == "message":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.message = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _read_oa_config_reader_read_result(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _ConfigReaderReadResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _read_snapshot(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _read_oa_config_editor_read_user_result(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _ConfigEditorReadUserResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _read_user_snapshot(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _read_oa_config_editor_replace_user_result(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _ConfigEditorReplaceUserResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _read_user_replace_result(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _read_oa_config_observer_observe_result(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _ConfigObserverObserveResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _read_config_observation(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def decode(data):
    r = _Reader(bytes(data))
    r.ws()
    v = _read_snapshot(r)
    r.ws()
    if r.pos < len(r.buf):
        raise r.refuse("trailing_bytes")
    return v


# _REFUSALS is in the order two of them are chosen between.

_REFUSALS = ["malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"]


def _refusal_rank(word):
    return _REFUSALS.index(word) if word in _REFUSALS else -1


class DispatchError(ValueError):
    """A frame that names no version, service or method this module speaks."""

    def __init__(self, code):
        super().__init__(code)
        self.code = code


def _service_decode(decoder, frame, depth=0):
    if not isinstance(frame, (bytes, bytearray, memoryview)):
        raise TypeError("transport frame must be bytes")
    r = _Reader(bytes(frame))
    r.depth = depth
    r.ws()
    value = decoder(r)
    r.ws()
    if r.pos != len(r.buf):
        raise r.refuse("trailing_bytes")
    return value


def _service_encode(encoder, value, depth):
    out = bytearray()
    try:
        encoder(out, value, depth)
    except UnicodeError:
        raise Refusal("bad_string", 0) from None
    return bytes(out)


def _service_request(service, method, arguments):
    v = _ServiceFrame(version=1, service=service, method=method, arguments=arguments)
    frame = _service_encode(_write_oa_service_frame, v, 0)
    _service_decode(_read_oa_service_frame, frame)
    return frame


def _service_check(kind, value, depth=0):
    # Python coercions must not silently change typed service arguments.
    if depth >= _DEPTH_LIMIT and (kind.startswith(("list<", "map<")) or kind in _SERVICE_RECORDS):
        raise Refusal("depth_exceeded", 0)
    if kind == "string":
        valid = type(value) is str
    elif kind == "enum":
        valid = value is None or isinstance(value, str)
    elif kind in ("i32", "i64"):
        valid = type(value) is int
        if valid:
            limit = 1 << (31 if kind == "i32" else 63)
            if not -limit <= value < limit:
                raise Refusal("number_spelling", 0)
    elif kind == "bool":
        valid = type(value) is bool
    elif kind == "json":
        valid = isinstance(value, (str, bytes, bytearray, memoryview))
    elif kind.startswith("list<"):
        valid = type(value) is list
        if valid:
            for item in value:
                _service_check(kind[5:-1], item, depth + 1)
    elif kind.startswith("map<string,"):
        valid = type(value) is dict
        if valid:
            for key, item in value.items():
                _service_check("string", key, depth + 1)
                _service_check(kind[11:-1], item, depth + 1)
    else:
        cls, fields = _SERVICE_RECORDS[kind]
        valid = isinstance(value, cls)
        if valid:
            for name, field_kind, omit in fields:
                if not hasattr(value, name):
                    raise Refusal("missing_field", 0)
                item = getattr(value, name)
                if omit == "absent" and item is None:
                    continue
                _service_check(field_kind, item, depth + 1)
    if not valid:
        raise Refusal("wrong_type", 0)

def service_name(frame):
    """Validate envelope/version for routing; dispatchers validate typed arguments."""
    value = _service_decode(_read_oa_service_frame, frame)
    if value.version != 1:
        raise DispatchError("unknown_version")
    return value.service



class ServiceError(Exception):
    """The service answered the call with an error code and message."""

    def __init__(self, code, message=""):
        super().__init__(message if message else code)
        self.code = code
        self.message = message


def _service_response(frame, service, method):
    reply = _service_decode(_read_oa_service_reply, frame)
    if reply.version != 1:
        raise DispatchError("unknown_version")
    if reply.service != service or reply.method != method:
        raise DispatchError("mismatched_response")
    if not reply.ok:
        error = _service_decode(_read_oa_service_error, reply.payload, 1)
        if not error.code:
            raise DispatchError("invalid_error")
        raise ServiceError(error.code, error.message)
    return reply.payload

_SERVICE_RECORDS = {
    "RunOverrides": (RunOverrides, [("nas_store", "string", "never"), ("store", "string", "never"), ("log_sink", "string", "never"), ("log_service", "string", "never"), ]),
    "Origin": (Origin, [("rung", "string", "never"), ("path", "string", "never"), ]),
    "Origins": (Origins, [("nas_store", "Origin", "never"), ("store", "Origin", "never"), ("log_sink", "Origin", "never"), ("log_service", "Origin", "never"), ("off", "Origin", "never"), ]),
    "Snapshot": (Snapshot, [("nas_store", "string", "never"), ("store", "string", "never"), ("log_sink", "string", "never"), ("log_service", "string", "never"), ("off", "map<string,string>", "never"), ("origins", "Origins", "never"), ("stamp", "string", "never"), ]),
    "UserSettings": (UserSettings, [("nas_store", "string", "never"), ("store", "string", "never"), ("log_sink", "string", "never"), ("log_service", "string", "never"), ("off", "map<string,string>", "never"), ]),
    "UserSnapshot": (UserSnapshot, [("values", "UserSettings", "never"), ("revision", "string", "never"), ]),
    "UserReplaceResult": (UserReplaceResult, [("outcome", "enum", "never"), ("snapshot", "UserSnapshot", "never"), ]),
    "ConfigObservation": (ConfigObservation, [("outcome", "enum", "never"), ("cursor", "string", "never"), ("snapshot", "Snapshot", "absent"), ]),
    "OAConfigReaderReadArguments": (_ConfigReaderReadArguments, [("overrides", "RunOverrides", "never"), ]),
    "OAConfigEditorReadUserArguments": (_ConfigEditorReadUserArguments, []),
    "OAConfigEditorReplaceUserArguments": (_ConfigEditorReplaceUserArguments, [("expected_revision", "string", "never"), ("values", "UserSettings", "never"), ]),
    "OAConfigObserverObserveArguments": (_ConfigObserverObserveArguments, [("overrides", "RunOverrides", "never"), ("cursor", "string", "never"), ("wait_ms", "i64", "never"), ]),
    "OAServiceFrame": (_ServiceFrame, [("version", "i32", "never"), ("service", "string", "never"), ("method", "string", "never"), ("arguments", "json", "never"), ]),
    "OAServiceReply": (_ServiceReply, [("version", "i32", "never"), ("service", "string", "never"), ("method", "string", "never"), ("ok", "bool", "never"), ("payload", "json", "never"), ]),
    "OAServiceError": (_ServiceError, [("code", "string", "never"), ("message", "string", "never"), ]),
    "OAConfigReaderReadResult": (_ConfigReaderReadResult, [("value", "Snapshot", "never"), ]),
    "OAConfigEditorReadUserResult": (_ConfigEditorReadUserResult, [("value", "UserSnapshot", "never"), ]),
    "OAConfigEditorReplaceUserResult": (_ConfigEditorReplaceUserResult, [("value", "UserReplaceResult", "never"), ]),
    "OAConfigObserverObserveResult": (_ConfigObserverObserveResult, [("value", "ConfigObservation", "never"), ]),
}


class ConfigReader:
    """Per-user configuration read service. Caller identity is checked
    independently of overrides."""

    def read(self, overrides: RunOverrides) -> Snapshot:
        """Read same-user machine/user configuration with explicit caller run
        overrides. No writes, watch or provider fallback."""
        raise NotImplementedError


class ConfigReaderClient(ConfigReader):
    """Calls abstraction.config/reader@1 through a transport that exchanges frames."""

    def __init__(self, transport):
        self._transport = transport

    def read(self, overrides: RunOverrides) -> Snapshot:
        _service_check("RunOverrides", overrides)
        _args = _ConfigReaderReadArguments()
        _args.overrides = overrides
        _arguments = _service_encode(_write_oa_config_reader_read_arguments, _args, 1)
        _service_decode(_read_oa_config_reader_read_arguments, _arguments, 1)
        _request = _service_request("abstraction.config/reader@1", "Read", _arguments)
        _payload = _service_response(self._transport.exchange_frame(_request), "abstraction.config/reader@1", "Read")
        _result = _service_decode(_read_oa_config_reader_read_result, _payload, 1)
        return _result.value


class ConfigEditor:
    """Same-account Program-proven user editor on the config endpoint. The service
    selects its private user path once. Caller claims cannot grant authority;
    forbidden callers cause no storage access. Existing machine and run rungs
    are unaffected."""

    def read_user(self) -> UserSnapshot:
        """Read only the authenticated service user's persisted rung. No
        environment or machine merge. Missing storage is empty; corrupt,
        unsupported or unavailable storage returns storage_unavailable."""
        raise NotImplementedError

    def replace_user(self, expected_revision: str, values: UserSettings) -> UserReplaceResult:
        """Compare the opaque revision and replace atomically through the selected
        conditional-write store. Stale revision returns conflict. Empty revision
        is invalid_revision. Storage failures return storage_unavailable. A
        configured edit policy is evaluated after same-account proof and before
        storage access: refusal returns forbidden and a failed decision returns
        unavailable. A canceled wait leaves write outcome unresolved; reread
        rather than blindly retry."""
        raise NotImplementedError


class ConfigEditorClient(ConfigEditor):
    """Calls abstraction.config/editor@1 through a transport that exchanges frames."""

    def __init__(self, transport):
        self._transport = transport

    def read_user(self) -> UserSnapshot:
        _args = _ConfigEditorReadUserArguments()
        _arguments = _service_encode(_write_oa_config_editor_read_user_arguments, _args, 1)
        _service_decode(_read_oa_config_editor_read_user_arguments, _arguments, 1)
        _request = _service_request("abstraction.config/editor@1", "ReadUser", _arguments)
        _payload = _service_response(self._transport.exchange_frame(_request), "abstraction.config/editor@1", "ReadUser")
        _result = _service_decode(_read_oa_config_editor_read_user_result, _payload, 1)
        return _result.value

    def replace_user(self, expected_revision: str, values: UserSettings) -> UserReplaceResult:
        _service_check("string", expected_revision)
        _service_check("UserSettings", values)
        _args = _ConfigEditorReplaceUserArguments()
        _args.expected_revision = expected_revision
        _args.values = values
        _arguments = _service_encode(_write_oa_config_editor_replace_user_arguments, _args, 1)
        _service_decode(_read_oa_config_editor_replace_user_arguments, _arguments, 1)
        _request = _service_request("abstraction.config/editor@1", "ReplaceUser", _arguments)
        _payload = _service_response(self._transport.exchange_frame(_request), "abstraction.config/editor@1", "ReplaceUser")
        _result = _service_decode(_read_oa_config_editor_replace_user_result, _payload, 1)
        return _result.value


class ConfigObserver:
    """Same-account latest-snapshot long-poll observation over a provider's
    explicit change notification source."""

    def observe(self, overrides: RunOverrides, cursor: str, wait_ms: int) -> ConfigObservation:
        """Empty cursor reads the current snapshot. At the same revision, wait at
        most wait_ms (0..30000) for provider invalidation; reread on expiry.
        Cursor is at most 512 UTF-8 bytes and each override at most 4096 bytes.
        A slow consumer receives the latest revision; revisions include values
        and provenance. Missing change notification support gives unsupported.
        Bounded waiter exhaustion or provider notification failure gives
        unavailable. Caller cancellation stops observation waiting only; setting
        mutations retain their own lifetimes. Receiving account authority is
        rechecked before returning data."""
        raise NotImplementedError


class ConfigObserverClient(ConfigObserver):
    """Calls abstraction.config/observer@1 through a transport that exchanges frames."""

    def __init__(self, transport):
        self._transport = transport

    def observe(self, overrides: RunOverrides, cursor: str, wait_ms: int) -> ConfigObservation:
        _service_check("RunOverrides", overrides)
        _service_check("string", cursor)
        _service_check("i64", wait_ms)
        _args = _ConfigObserverObserveArguments()
        _args.overrides = overrides
        _args.cursor = cursor
        _args.wait_ms = wait_ms
        _arguments = _service_encode(_write_oa_config_observer_observe_arguments, _args, 1)
        _service_decode(_read_oa_config_observer_observe_arguments, _arguments, 1)
        _request = _service_request("abstraction.config/observer@1", "Observe", _arguments)
        _payload = _service_response(self._transport.exchange_frame(_request), "abstraction.config/observer@1", "Observe")
        _result = _service_decode(_read_oa_config_observer_observe_result, _payload, 1)
        return _result.value
