# Code generated by abstraction-idl from abstraction-config/config.thrift. DO NOT EDIT.

_HEX = b"0123456789abcdef"
_WS = (0x20, 0x09, 0x0A, 0x0D)
_SHORT = {0x22: b'\\"', 0x5C: b"\\\\", 0x08: b"\\b", 0x0C: b"\\f",
          0x0A: b"\\n", 0x0D: b"\\r", 0x09: b"\\t"}


def esc_byte(out, c):
    short = _SHORT.get(c)
    if short is not None:
        out += short
    elif c < 0x20:
        out += b"\\u00" + bytes([_HEX[c >> 4], _HEX[c & 0xF]])
    else:
        out.append(c)


def num(out, n):
    out += str(int(n)).encode("ascii")


def pad(out, depth):
    out += b" " * (depth * 2)


def strs(out, v, depth):
    if not v:
        out += b"[]"
        return
    out += b"[\n"
    for i, s in enumerate(v):
        pad(out, depth + 1)
        esc(out, s)
        if i + 1 < len(v):
            out += b","
        out += b"\n"
    pad(out, depth)
    out += b"]"


def raw(out, s, depth):
    b = s.encode("utf-8") if isinstance(s, str) else s
    i, n = 0, len(b)
    while i < n:
        c = b[i]
        if c in _WS:
            i += 1
        elif c == 0x22:
            j = i + 1
            while j < n:
                if b[j] == 0x5C:
                    j += 2
                    continue
                if b[j] == 0x22:
                    j += 1
                    break
                j += 1
            out += b[i:j]
            i = j
        elif c in (0x7B, 0x5B):
            out.append(c)
            i += 1
            j = i
            while j < n and b[j] in _WS:
                j += 1
            if j < n and b[j] in (0x7D, 0x5D):
                out.append(b[j])
                i = j + 1
            else:
                depth += 1
                out += b"\n"
                pad(out, depth)
        elif c in (0x7D, 0x5D):
            depth -= 1
            out += b"\n"
            pad(out, depth)
            out.append(c)
            i += 1
        elif c == 0x2C:
            out += b",\n"
            pad(out, depth)
            i += 1
        elif c == 0x3A:
            out += b": "
            i += 1
        else:
            out.append(c)
            i += 1


def rawmap(out, m, depth):
    keys = sorted(m, key=lambda k: k.encode("utf-8"))
    if not keys:
        out += b"{}"
        return
    out += b"{\n"
    for i, k in enumerate(keys):
        pad(out, depth + 1)
        esc(out, k)
        out += b": "
        raw(out, m[k], depth + 1)
        if i + 1 < len(keys):
            out += b","
        out += b"\n"
    pad(out, depth)
    out += b"}"

def esc(out, s):
    out += b'"'
    for c in s.encode("utf-8"):
        esc_byte(out, c)
    out += b'"'


def strmap(out, m, depth):
    keys = sorted(m, key=lambda k: k.encode("utf-8"))
    if not keys:
        out += b"{}"
        return
    out += b"{\n"
    for i, k in enumerate(keys):
        pad(out, depth + 1)
        esc(out, k)
        out += b": "
        esc(out, m[k])
        if i + 1 < len(keys):
            out += b","
        out += b"\n"
    pad(out, depth)
    out += b"}"


USERREPLACEOUTCOME_NAMES = ["applied", "conflict"]
USERREPLACEOUTCOME_UNKNOWN = "refuse"


CONFIGOBSERVATIONOUTCOME_NAMES = ["snapshot", "unchanged", "gap", "unavailable", "unsupported", "invalid"]
CONFIGOBSERVATIONOUTCOME_UNKNOWN = "refuse"


class RunOverrides:
    def __init__(self, **kw):
        self.nas_store = kw.get("nas_store", "")
        self.store = kw.get("store", "")
        self.log_sink = kw.get("log_sink", "")
        self.log_service = kw.get("log_service", "")


class Origin:
    def __init__(self, **kw):
        self.rung = kw.get("rung", "")
        self.path = kw.get("path", "")


class Origins:
    def __init__(self, **kw):
        self.nas_store = kw.get("nas_store", Origin())
        self.store = kw.get("store", Origin())
        self.log_sink = kw.get("log_sink", Origin())
        self.log_service = kw.get("log_service", Origin())
        self.off = kw.get("off", Origin())


class Snapshot:
    def __init__(self, **kw):
        self.nas_store = kw.get("nas_store", "")
        self.store = kw.get("store", "")
        self.log_sink = kw.get("log_sink", "")
        self.log_service = kw.get("log_service", "")
        self.off = kw.get("off", {})
        self.origins = kw.get("origins", Origins())
        self.stamp = kw.get("stamp", "")


class UserSettings:
    def __init__(self, **kw):
        self.nas_store = kw.get("nas_store", "")
        self.store = kw.get("store", "")
        self.log_sink = kw.get("log_sink", "")
        self.log_service = kw.get("log_service", "")
        self.off = kw.get("off", {})


class UserSnapshot:
    def __init__(self, **kw):
        self.values = kw.get("values", UserSettings())
        self.revision = kw.get("revision", "")


class UserReplaceResult:
    def __init__(self, **kw):
        self.outcome = kw.get("outcome", "")
        self.snapshot = kw.get("snapshot", UserSnapshot())


class ConfigObservation:
    def __init__(self, **kw):
        self.outcome = kw.get("outcome", "")
        self.cursor = kw.get("cursor", "")
        self.snapshot = kw.get("snapshot", None)


class OAConfigReaderReadArguments:
    def __init__(self, **kw):
        self.overrides = kw.get("overrides", RunOverrides())


class OAConfigEditorReadUserArguments:
    def __init__(self, **kw):
        pass


class OAConfigEditorReplaceUserArguments:
    def __init__(self, **kw):
        self.expected_revision = kw.get("expected_revision", "")
        self.values = kw.get("values", UserSettings())


class OAConfigObserverObserveArguments:
    def __init__(self, **kw):
        self.overrides = kw.get("overrides", RunOverrides())
        self.cursor = kw.get("cursor", "")
        self.wait_ms = kw.get("wait_ms", 0)


class OAServiceFrame:
    def __init__(self, **kw):
        self.version = kw.get("version", 0)
        self.service = kw.get("service", "")
        self.method = kw.get("method", "")
        self.arguments = kw.get("arguments", "")


class OAServiceReply:
    def __init__(self, **kw):
        self.version = kw.get("version", 0)
        self.service = kw.get("service", "")
        self.method = kw.get("method", "")
        self.ok = kw.get("ok", False)
        self.payload = kw.get("payload", "")


class OAServiceError:
    def __init__(self, **kw):
        self.code = kw.get("code", "")
        self.message = kw.get("message", "")


class OAConfigReaderReadResult:
    def __init__(self, **kw):
        self.value = kw.get("value", Snapshot())


class OAConfigEditorReadUserResult:
    def __init__(self, **kw):
        self.value = kw.get("value", UserSnapshot())


class OAConfigEditorReplaceUserResult:
    def __init__(self, **kw):
        self.value = kw.get("value", UserReplaceResult())


class OAConfigObserverObserveResult:
    def __init__(self, **kw):
        self.value = kw.get("value", ConfigObservation())


def enc_runoverrides(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "nas_store")
    out += b": "
    esc(out, v.nas_store)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "store")
    out += b": "
    esc(out, v.store)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "log_sink")
    out += b": "
    esc(out, v.log_sink)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "log_service")
    out += b": "
    esc(out, v.log_service)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_origin(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "rung")
    out += b": "
    esc(out, v.rung)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "path")
    out += b": "
    esc(out, v.path)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_origins(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "nas_store")
    out += b": "
    enc_origin(out, v.nas_store, depth + 1)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "store")
    out += b": "
    enc_origin(out, v.store, depth + 1)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "log_sink")
    out += b": "
    enc_origin(out, v.log_sink, depth + 1)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "log_service")
    out += b": "
    enc_origin(out, v.log_service, depth + 1)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "off")
    out += b": "
    enc_origin(out, v.off, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_snapshot(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "nas_store")
    out += b": "
    esc(out, v.nas_store)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "store")
    out += b": "
    esc(out, v.store)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "log_sink")
    out += b": "
    esc(out, v.log_sink)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "log_service")
    out += b": "
    esc(out, v.log_service)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "off")
    out += b": "
    strmap(out, v.off, depth + 1)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "origins")
    out += b": "
    enc_origins(out, v.origins, depth + 1)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "stamp")
    out += b": "
    esc(out, v.stamp)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_usersettings(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "nas_store")
    out += b": "
    esc(out, v.nas_store)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "store")
    out += b": "
    esc(out, v.store)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "log_sink")
    out += b": "
    esc(out, v.log_sink)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "log_service")
    out += b": "
    esc(out, v.log_service)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "off")
    out += b": "
    strmap(out, v.off, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_usersnapshot(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "values")
    out += b": "
    enc_usersettings(out, v.values, depth + 1)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "revision")
    out += b": "
    esc(out, v.revision)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_userreplaceresult(out, v, depth):
    if type(v.outcome) is not str: raise Refusal("wrong_type",0)
    if v.outcome != "applied" and v.outcome != "conflict": raise Refusal("bad_enum",0)
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "outcome")
    out += b": "
    esc(out, v.outcome)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "snapshot")
    out += b": "
    enc_usersnapshot(out, v.snapshot, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_configobservation(out, v, depth):
    if type(v.outcome) is not str: raise Refusal("wrong_type",0)
    if v.outcome != "snapshot" and v.outcome != "unchanged" and v.outcome != "gap" and v.outcome != "unavailable" and v.outcome != "unsupported" and v.outcome != "invalid": raise Refusal("bad_enum",0)
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "outcome")
    out += b": "
    esc(out, v.outcome)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "cursor")
    out += b": "
    esc(out, v.cursor)
    if v.snapshot is not None:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "snapshot")
        out += b": "
        enc_snapshot(out, v.snapshot, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaconfigreaderreadarguments(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "overrides")
    out += b": "
    enc_runoverrides(out, v.overrides, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaconfigeditorreaduserarguments(out, v, depth):
    out += b"{"
    out += b"}"


def enc_oaconfigeditorreplaceuserarguments(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "expected_revision")
    out += b": "
    esc(out, v.expected_revision)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "values")
    out += b": "
    enc_usersettings(out, v.values, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaconfigobserverobservearguments(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "overrides")
    out += b": "
    enc_runoverrides(out, v.overrides, depth + 1)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "cursor")
    out += b": "
    esc(out, v.cursor)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "wait_ms")
    out += b": "
    num(out, v.wait_ms)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaserviceframe(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "version")
    out += b": "
    num(out, v.version)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "service")
    out += b": "
    esc(out, v.service)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "method")
    out += b": "
    esc(out, v.method)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "arguments")
    out += b": "
    out += v.arguments.encode("utf-8") if isinstance(v.arguments, str) else v.arguments
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaservicereply(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "version")
    out += b": "
    num(out, v.version)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "service")
    out += b": "
    esc(out, v.service)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "method")
    out += b": "
    esc(out, v.method)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "ok")
    out += b": "
    out += b"true" if v.ok else b"false"
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "payload")
    out += b": "
    out += v.payload.encode("utf-8") if isinstance(v.payload, str) else v.payload
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaserviceerror(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "code")
    out += b": "
    esc(out, v.code)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "message")
    out += b": "
    esc(out, v.message)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaconfigreaderreadresult(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "value")
    out += b": "
    enc_snapshot(out, v.value, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaconfigeditorreaduserresult(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "value")
    out += b": "
    enc_usersnapshot(out, v.value, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaconfigeditorreplaceuserresult(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "value")
    out += b": "
    enc_userreplaceresult(out, v.value, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaconfigobserverobserveresult(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "value")
    out += b": "
    enc_configobservation(out, v.value, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def encode(v):
    out = bytearray()
    enc_snapshot(out, v, 0)
    out += b"\n"
    return bytes(out)


_QUOTE, _BACKSLASH, _COLON, _COMMA = 0x22, 0x5C, 0x3A, 0x2C
_LBRACE, _RBRACE, _LBRACK, _RBRACK = 0x7B, 0x7D, 0x5B, 0x5D
_MINUS, _ZERO, _NINE, _DOT, _LOWER_U, _LOWER_N = 0x2D, 0x30, 0x39, 0x2E, 0x75, 0x6E
_UNESCAPE = {0x22: 0x22, 0x5C: 0x5C, 0x2F: 0x2F, 0x62: 0x08,
             0x66: 0x0C, 0x6E: 0x0A, 0x72: 0x0D, 0x74: 0x09}
_DEPTH_LIMIT = 64
_I64_DIGITS = 19


class Refusal(ValueError):
    def __init__(self, word, offset):
        super().__init__("refused: %s at byte %d" % (word, offset))
        self.word = word
        self.offset = offset


class _Reader:
    __slots__ = ("buf", "pos", "depth")

    def __init__(self, buf):
        self.buf = buf
        self.pos = 0
        self.depth = 0

    def refuse(self, word):
        return Refusal(word, self.pos)

    def at(self):
        return self.buf[self.pos] if self.pos < len(self.buf) else 0

    def ws(self):
        while self.pos < len(self.buf) and self.buf[self.pos] in _WS:
            self.pos += 1

    def enter(self):
        self.depth += 1
        if self.depth > _DEPTH_LIMIT:
            raise self.refuse("depth_exceeded")

    def digit(self):
        return _ZERO <= self.at() <= _NINE

    def string(self):
        if self.at() != _QUOTE:
            raise self.refuse("wrong_type")
        self.pos += 1
        out = bytearray()
        while True:
            if self.pos >= len(self.buf):
                raise self.refuse("malformed")
            c = self.buf[self.pos]
            if c == _QUOTE:
                self.pos += 1
                try:
                    return out.decode("utf-8")
                except UnicodeDecodeError:
                    raise self.refuse("bad_string") from None
            if c < 0x20:
                raise self.refuse("bad_string")
            if c == _BACKSLASH:
                self.escape(out)
            else:
                out.append(c)
                self.pos += 1

    def escape(self, out):
        self.pos += 1
        if self.pos >= len(self.buf):
            raise self.refuse("malformed")
        c = self.buf[self.pos]
        self.pos += 1
        plain = _UNESCAPE.get(c)
        if plain is not None:
            out.append(plain)
            return
        if c != _LOWER_U:
            raise self.refuse("bad_string")
        u = self.hex4()
        if 0xDC00 <= u <= 0xDFFF:
            raise self.refuse("bad_string")
        if 0xD800 <= u <= 0xDBFF:
            if (self.pos + 1 >= len(self.buf) or self.buf[self.pos] != _BACKSLASH
                    or self.buf[self.pos + 1] != _LOWER_U):
                raise self.refuse("bad_string")
            self.pos += 2
            low = self.hex4()
            if not 0xDC00 <= low <= 0xDFFF:
                raise self.refuse("bad_string")
            u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00)
        out += chr(u).encode("utf-8")

    def hex4(self):
        if self.pos + 4 > len(self.buf):
            raise self.refuse("bad_string")
        u = 0
        for i in range(4):
            c = self.buf[self.pos + i]
            if _ZERO <= c <= _NINE:
                u = u << 4 | (c - _ZERO)
            elif 0x61 <= c <= 0x66:
                u = u << 4 | (c - 0x61 + 10)
            elif 0x41 <= c <= 0x46:
                u = u << 4 | (c - 0x41 + 10)
            else:
                raise self.refuse("bad_string")
        self.pos += 4
        return u

    def integer(self, low, high):
        c = self.at()
        if c != _MINUS and not _ZERO <= c <= _NINE:
            raise self.refuse("wrong_type")
        negative = c == _MINUS
        if negative:
            self.pos += 1
        if not self.digit():
            raise self.refuse("malformed")
        start = self.pos
        if self.at() == _ZERO:
            self.pos += 1
        else:
            while self.digit():
                self.pos += 1
        if self.at() in (_DOT, 0x65, 0x45) or self.digit():
            raise self.refuse("number_spelling")
        if self.pos - start > _I64_DIGITS:
            raise self.refuse("number_spelling")
        n = int(self.buf[start:self.pos])
        if negative:
            if n == 0:
                raise self.refuse("number_spelling")
            n = -n
        if n < low or n > high:
            raise self.refuse("number_spelling")
        return n

    def boolean(self):
        if self.at() == 0x74:
            self.literal(b"true")
            return True
        if self.at() == 0x66:
            self.literal(b"false")
            return False
        raise self.refuse("wrong_type")

    def literal(self, word):
        if self.buf[self.pos:self.pos + len(word)] != word:
            raise self.refuse("malformed")
        self.pos += len(word)

    def str_list(self):
        if self.at() != _LBRACK:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = []
        self.ws()
        if self.at() != _RBRACK:
            while True:
                self.ws()
                out.append(self.string())
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACK:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out

    def raw_map(self):
        if self.at() != _LBRACE:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = {}
        self.ws()
        if self.at() != _RBRACE:
            while True:
                self.ws()
                if self.at() != _QUOTE:
                    raise self.refuse("malformed")
                k = self.string()
                self.ws()
                if self.at() != _COLON:
                    raise self.refuse("malformed")
                self.pos += 1
                self.ws()
                out[k] = self.raw_value()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACE:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out

    def raw_value(self):
        start = self.pos
        self.skip_value()
        return self.buf[start:self.pos]

    def skip_value(self):
        c = self.at()
        if c == _QUOTE:
            self.skip_string()
        elif c in (_LBRACE, _LBRACK):
            self.skip_container()
        elif c == 0x74:
            self.literal(b"true")
        elif c == 0x66:
            self.literal(b"false")
        elif c == 0x6E:
            self.literal(b"null")
        elif c == _MINUS or _ZERO <= c <= _NINE:
            self.skip_number()
        else:
            raise self.refuse("malformed")

    # An opaque value is validated and carried, never interpreted. Its syntax is
    # the record's own — the same string reader, so an escape, a control byte or
    # a lone surrogate is judged identically at any depth — and what it is free
    # to spell, it keeps: the bytes between these two offsets are what a writer
    # re-emits. A number is walked, never converted, so a value no host type
    # holds survives the reader that carried it.
    def skip_string(self):
        self.string()

    def some_digits(self):
        n = 0
        while _ZERO <= self.at() <= _NINE:
            self.pos += 1
            n += 1
        if n == 0:
            raise self.refuse("number_spelling")

    def skip_number(self):
        if self.at() == _MINUS:
            self.pos += 1
        c = self.at()
        if c == _ZERO:
            self.pos += 1
        elif _ZERO < c <= _NINE:
            while _ZERO <= self.at() <= _NINE:
                self.pos += 1
        else:
            raise self.refuse("number_spelling")
        if self.at() == _DOT:
            self.pos += 1
            self.some_digits()
        if self.at() in (0x65, 0x45):
            self.pos += 1
            if self.at() in (0x2B, _MINUS):
                self.pos += 1
            self.some_digits()

    def skip_container(self):
        opener = self.at()
        shut = _RBRACE if opener == _LBRACE else _RBRACK
        self.enter()
        self.pos += 1
        self.ws()
        seen = set()
        if self.at() != shut:
            while True:
                self.ws()
                if opener == _LBRACE:
                    if self.at() != _QUOTE:
                        raise self.refuse("malformed")
                    k = self.string()
                    self.ws()
                    if self.at() != _COLON:
                        raise self.refuse("malformed")
                    self.pos += 1
                    self.ws()
                self.skip_value()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != shut:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1

    def str_map(self):
        if self.at() != _LBRACE:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = {}
        self.ws()
        if self.at() != _RBRACE:
            while True:
                self.ws()
                if self.at() != _QUOTE:
                    raise self.refuse("malformed")
                k = self.string()
                self.ws()
                if self.at() != _COLON:
                    raise self.refuse("malformed")
                self.pos += 1
                self.ws()
                out[k] = self.string()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACE:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out


def _decode_runoverrides(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = RunOverrides()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "nas_store":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.nas_store = r.string()
            elif key == "store":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.store = r.string()
            elif key == "log_sink":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.log_sink = r.string()
            elif key == "log_service":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.log_service = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 15 != 15:
        raise r.refuse("missing_field")
    return v


def _decode_origin(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Origin()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "rung":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.rung = r.string()
            elif key == "path":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.path = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _decode_origins(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Origins()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "nas_store":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.nas_store = _decode_origin(r)
            elif key == "store":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.store = _decode_origin(r)
            elif key == "log_sink":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.log_sink = _decode_origin(r)
            elif key == "log_service":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.log_service = _decode_origin(r)
            elif key == "off":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.off = _decode_origin(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 31 != 31:
        raise r.refuse("missing_field")
    return v


def _decode_snapshot(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Snapshot()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "nas_store":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.nas_store = r.string()
            elif key == "store":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.store = r.string()
            elif key == "log_sink":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.log_sink = r.string()
            elif key == "log_service":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.log_service = r.string()
            elif key == "off":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.off = r.str_map()
            elif key == "origins":
                if seen & 32:
                    raise r.refuse("duplicate_field")
                seen |= 32
                v.origins = _decode_origins(r)
            elif key == "stamp":
                if seen & 64:
                    raise r.refuse("duplicate_field")
                seen |= 64
                v.stamp = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 127 != 127:
        raise r.refuse("missing_field")
    return v


def _decode_usersettings(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = UserSettings()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "nas_store":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.nas_store = r.string()
            elif key == "store":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.store = r.string()
            elif key == "log_sink":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.log_sink = r.string()
            elif key == "log_service":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.log_service = r.string()
            elif key == "off":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.off = r.str_map()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 31 != 31:
        raise r.refuse("missing_field")
    return v


def _decode_usersnapshot(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = UserSnapshot()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "values":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.values = _decode_usersettings(r)
            elif key == "revision":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.revision = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _decode_userreplaceresult(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = UserReplaceResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "outcome":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.outcome = r.string()
            elif key == "snapshot":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.snapshot = _decode_usersnapshot(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    if v.outcome != "applied" and v.outcome != "conflict": raise r.refuse("bad_enum")
    return v


def _decode_configobservation(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = ConfigObservation()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "outcome":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.outcome = r.string()
            elif key == "cursor":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.cursor = r.string()
            elif key == "snapshot":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.snapshot = _decode_snapshot(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    if v.outcome != "snapshot" and v.outcome != "unchanged" and v.outcome != "gap" and v.outcome != "unavailable" and v.outcome != "unsupported" and v.outcome != "invalid": raise r.refuse("bad_enum")
    return v


def _decode_oaconfigreaderreadarguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAConfigReaderReadArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "overrides":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.overrides = _decode_runoverrides(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_oaconfigeditorreaduserarguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAConfigEditorReadUserArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if False:
                pass
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    return v


def _decode_oaconfigeditorreplaceuserarguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAConfigEditorReplaceUserArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "expected_revision":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.expected_revision = r.string()
            elif key == "values":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.values = _decode_usersettings(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _decode_oaconfigobserverobservearguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAConfigObserverObserveArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "overrides":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.overrides = _decode_runoverrides(r)
            elif key == "cursor":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.cursor = r.string()
            elif key == "wait_ms":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.wait_ms = r.integer(-9223372036854775808, 9223372036854775807)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 7 != 7:
        raise r.refuse("missing_field")
    return v


def _decode_oaserviceframe(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAServiceFrame()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "version":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.version = r.integer(-2147483648, 2147483647)
            elif key == "service":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.service = r.string()
            elif key == "method":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.method = r.string()
            elif key == "arguments":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.arguments = r.raw_value()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 15 != 15:
        raise r.refuse("missing_field")
    return v


def _decode_oaservicereply(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAServiceReply()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "version":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.version = r.integer(-2147483648, 2147483647)
            elif key == "service":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.service = r.string()
            elif key == "method":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.method = r.string()
            elif key == "ok":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.ok = r.boolean()
            elif key == "payload":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.payload = r.raw_value()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 31 != 31:
        raise r.refuse("missing_field")
    return v


def _decode_oaserviceerror(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAServiceError()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "code":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.code = r.string()
            elif key == "message":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.message = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _decode_oaconfigreaderreadresult(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAConfigReaderReadResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _decode_snapshot(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_oaconfigeditorreaduserresult(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAConfigEditorReadUserResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _decode_usersnapshot(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_oaconfigeditorreplaceuserresult(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAConfigEditorReplaceUserResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _decode_userreplaceresult(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_oaconfigobserverobserveresult(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAConfigObserverObserveResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _decode_configobservation(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def decode(data):
    r = _Reader(bytes(data))
    r.ws()
    v = _decode_snapshot(r)
    r.ws()
    if r.pos < len(r.buf):
        raise r.refuse("trailing_bytes")
    return v


# REFUSALS is in the order two of them are chosen between.

REFUSALS = ["malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"]


def refusal_rank(word):
    return REFUSALS.index(word) if word in REFUSALS else -1


class DispatchError(ValueError):
    def __init__(self, code):
        super().__init__(code)
        self.code = code


def _service_decode(decoder, frame, depth=0):
    if not isinstance(frame, (bytes, bytearray, memoryview)):
        raise TypeError("transport frame must be bytes")
    r = _Reader(bytes(frame))
    r.depth = depth
    r.ws()
    value = decoder(r)
    r.ws()
    if r.pos != len(r.buf):
        raise r.refuse("trailing_bytes")
    return value


def _service_encode(encoder, value, depth):
    out = bytearray()
    try:
        encoder(out, value, depth)
    except UnicodeError:
        raise Refusal("bad_string", 0) from None
    return bytes(out)


def _service_request(service, method, arguments):
    v = OAServiceFrame(version=1, service=service, method=method, arguments=arguments)
    frame = _service_encode(enc_oaserviceframe, v, 0)
    _service_decode(_decode_oaserviceframe, frame)
    return frame


def _service_check(kind, value, depth=0):
    # Python coercions must not silently change typed service arguments.
    if depth >= _DEPTH_LIMIT and (kind.startswith(("list<", "map<")) or kind in _SERVICE_RECORDS):
        raise Refusal("depth_exceeded", 0)
    if kind == "string":
        valid = type(value) is str
    elif kind in ("i32", "i64"):
        valid = type(value) is int
        if valid:
            limit = 1 << (31 if kind == "i32" else 63)
            if not -limit <= value < limit:
                raise Refusal("number_spelling", 0)
    elif kind == "bool":
        valid = type(value) is bool
    elif kind == "json":
        valid = isinstance(value, (str, bytes, bytearray, memoryview))
    elif kind.startswith("list<"):
        valid = type(value) is list
        if valid:
            for item in value:
                _service_check(kind[5:-1], item, depth + 1)
    elif kind.startswith("map<string,"):
        valid = type(value) is dict
        if valid:
            for key, item in value.items():
                _service_check("string", key, depth + 1)
                _service_check(kind[11:-1], item, depth + 1)
    else:
        cls, fields = _SERVICE_RECORDS[kind]
        valid = isinstance(value, cls)
        if valid:
            for name, field_kind, omit in fields:
                if not hasattr(value, name):
                    raise Refusal("missing_field", 0)
                item = getattr(value, name)
                if omit == "absent" and item is None:
                    continue
                _service_check(field_kind, item, depth + 1)
    if not valid:
        raise Refusal("wrong_type", 0)

def service_name(frame):
    """Validate envelope/version for routing; dispatchers validate typed arguments."""
    value = _service_decode(_decode_oaserviceframe, frame)
    if value.version != 1:
        raise DispatchError("unknown_version")
    return value.service



class ServiceError(Exception):
    def __init__(self, code, message=""):
        super().__init__(message if message else code)
        self.code = code
        self.message = message


def _service_response(frame, service, method):
    reply = _service_decode(_decode_oaservicereply, frame)
    if reply.version != 1:
        raise DispatchError("unknown_version")
    if reply.service != service or reply.method != method:
        raise DispatchError("mismatched_response")
    if not reply.ok:
        error = _service_decode(_decode_oaserviceerror, reply.payload, 1)
        if not error.code:
            raise DispatchError("invalid_error")
        raise ServiceError(error.code, error.message)
    return reply.payload

_SERVICE_RECORDS = {
    "RunOverrides": (RunOverrides, [("nas_store","string","never"),("store","string","never"),("log_sink","string","never"),("log_service","string","never"),]),
    "Origin": (Origin, [("rung","string","never"),("path","string","never"),]),
    "Origins": (Origins, [("nas_store","Origin","never"),("store","Origin","never"),("log_sink","Origin","never"),("log_service","Origin","never"),("off","Origin","never"),]),
    "Snapshot": (Snapshot, [("nas_store","string","never"),("store","string","never"),("log_sink","string","never"),("log_service","string","never"),("off","map<string,string>","never"),("origins","Origins","never"),("stamp","string","never"),]),
    "UserSettings": (UserSettings, [("nas_store","string","never"),("store","string","never"),("log_sink","string","never"),("log_service","string","never"),("off","map<string,string>","never"),]),
    "UserSnapshot": (UserSnapshot, [("values","UserSettings","never"),("revision","string","never"),]),
    "UserReplaceResult": (UserReplaceResult, [("outcome","string","never"),("snapshot","UserSnapshot","never"),]),
    "ConfigObservation": (ConfigObservation, [("outcome","string","never"),("cursor","string","never"),("snapshot","Snapshot","absent"),]),
    "OAConfigReaderReadArguments": (OAConfigReaderReadArguments, [("overrides","RunOverrides","never"),]),
    "OAConfigEditorReadUserArguments": (OAConfigEditorReadUserArguments, []),
    "OAConfigEditorReplaceUserArguments": (OAConfigEditorReplaceUserArguments, [("expected_revision","string","never"),("values","UserSettings","never"),]),
    "OAConfigObserverObserveArguments": (OAConfigObserverObserveArguments, [("overrides","RunOverrides","never"),("cursor","string","never"),("wait_ms","i64","never"),]),
    "OAServiceFrame": (OAServiceFrame, [("version","i32","never"),("service","string","never"),("method","string","never"),("arguments","json","never"),]),
    "OAServiceReply": (OAServiceReply, [("version","i32","never"),("service","string","never"),("method","string","never"),("ok","bool","never"),("payload","json","never"),]),
    "OAServiceError": (OAServiceError, [("code","string","never"),("message","string","never"),]),
    "OAConfigReaderReadResult": (OAConfigReaderReadResult, [("value","Snapshot","never"),]),
    "OAConfigEditorReadUserResult": (OAConfigEditorReadUserResult, [("value","UserSnapshot","never"),]),
    "OAConfigEditorReplaceUserResult": (OAConfigEditorReplaceUserResult, [("value","UserReplaceResult","never"),]),
    "OAConfigObserverObserveResult": (OAConfigObserverObserveResult, [("value","ConfigObservation","never"),]),
}


class ConfigReader:
    __doc__ = "Per-user configuration read service. Caller identity is checked independently of overrides."
    def Read(self, overrides: "RunOverrides") -> "Snapshot":
        raise NotImplementedError


class ConfigReaderClient(ConfigReader):
    def __init__(self, transport):
        self._transport = transport

    def Read(self, overrides: "RunOverrides") -> "Snapshot":
        _service_check("RunOverrides", overrides)
        _oa_args = OAConfigReaderReadArguments()
        _oa_args.overrides = overrides
        _oa_arguments = _service_encode(enc_oaconfigreaderreadarguments, _oa_args, 1)
        _service_decode(_decode_oaconfigreaderreadarguments, _oa_arguments, 1)
        _oa_request = _service_request("abstraction.config/reader@1", "Read", _oa_arguments)
        _oa_payload = _service_response(self._transport.exchange_frame(_oa_request), "abstraction.config/reader@1", "Read")
        _oa_result = _service_decode(_decode_oaconfigreaderreadresult, _oa_payload, 1)
        return _oa_result.value


class ConfigEditor:
    __doc__ = "Same-account Program-proven user editor on the config endpoint. The service selects its private user path once. Caller claims cannot grant authority; forbidden callers cause no storage access. Existing machine and run rungs are unaffected."
    def ReadUser(self) -> "UserSnapshot":
        raise NotImplementedError
    def ReplaceUser(self, expected_revision: "str", values: "UserSettings") -> "UserReplaceResult":
        raise NotImplementedError


class ConfigEditorClient(ConfigEditor):
    def __init__(self, transport):
        self._transport = transport

    def ReadUser(self) -> "UserSnapshot":
        _oa_args = OAConfigEditorReadUserArguments()
        _oa_arguments = _service_encode(enc_oaconfigeditorreaduserarguments, _oa_args, 1)
        _service_decode(_decode_oaconfigeditorreaduserarguments, _oa_arguments, 1)
        _oa_request = _service_request("abstraction.config/editor@1", "ReadUser", _oa_arguments)
        _oa_payload = _service_response(self._transport.exchange_frame(_oa_request), "abstraction.config/editor@1", "ReadUser")
        _oa_result = _service_decode(_decode_oaconfigeditorreaduserresult, _oa_payload, 1)
        return _oa_result.value

    def ReplaceUser(self, expected_revision: "str", values: "UserSettings") -> "UserReplaceResult":
        _service_check("string", expected_revision)
        _service_check("UserSettings", values)
        _oa_args = OAConfigEditorReplaceUserArguments()
        _oa_args.expected_revision = expected_revision
        _oa_args.values = values
        _oa_arguments = _service_encode(enc_oaconfigeditorreplaceuserarguments, _oa_args, 1)
        _service_decode(_decode_oaconfigeditorreplaceuserarguments, _oa_arguments, 1)
        _oa_request = _service_request("abstraction.config/editor@1", "ReplaceUser", _oa_arguments)
        _oa_payload = _service_response(self._transport.exchange_frame(_oa_request), "abstraction.config/editor@1", "ReplaceUser")
        _oa_result = _service_decode(_decode_oaconfigeditorreplaceuserresult, _oa_payload, 1)
        return _oa_result.value


class ConfigObserver:
    __doc__ = "Same-account latest-snapshot long-poll observation over a provider's explicit change notification source."
    def Observe(self, overrides: "RunOverrides", cursor: "str", wait_ms: "int") -> "ConfigObservation":
        raise NotImplementedError


class ConfigObserverClient(ConfigObserver):
    def __init__(self, transport):
        self._transport = transport

    def Observe(self, overrides: "RunOverrides", cursor: "str", wait_ms: "int") -> "ConfigObservation":
        _service_check("RunOverrides", overrides)
        _service_check("string", cursor)
        _service_check("i64", wait_ms)
        _oa_args = OAConfigObserverObserveArguments()
        _oa_args.overrides = overrides
        _oa_args.cursor = cursor
        _oa_args.wait_ms = wait_ms
        _oa_arguments = _service_encode(enc_oaconfigobserverobservearguments, _oa_args, 1)
        _service_decode(_decode_oaconfigobserverobservearguments, _oa_arguments, 1)
        _oa_request = _service_request("abstraction.config/observer@1", "Observe", _oa_arguments)
        _oa_payload = _service_response(self._transport.exchange_frame(_oa_request), "abstraction.config/observer@1", "Observe")
        _oa_result = _service_decode(_decode_oaconfigobserverobserveresult, _oa_payload, 1)
        return _oa_result.value
