// Code generated by abstraction-idl from abstraction-config/config.thrift. DO NOT EDIT.

#![allow(dead_code)]

use std::collections::BTreeMap;

// An opaque payload is bytes the contract forbids us to reinterpret, and String
// would refuse to hold one that is not UTF-8 rather than carry it back out.
pub type Raw = Vec<u8>;

const HEX: &[u8; 16] = b"0123456789abcdef";

fn esc_byte(out: &mut Vec<u8>, c: u8) {
    match c {
        b'"' => out.extend_from_slice(b"\\\""),
        b'\\' => out.extend_from_slice(b"\\\\"),
        0x08 => out.extend_from_slice(b"\\b"),
        0x0c => out.extend_from_slice(b"\\f"),
        b'\n' => out.extend_from_slice(b"\\n"),
        b'\r' => out.extend_from_slice(b"\\r"),
        b'\t' => out.extend_from_slice(b"\\t"),
        _ if c < 0x20 => {
            out.extend_from_slice(b"\\u00");
            out.push(HEX[(c >> 4) as usize]);
            out.push(HEX[(c & 0x0F) as usize]);
        }
        _ => out.push(c),
    }
}

pub fn num(out: &mut Vec<u8>, n: i64) {
    out.extend_from_slice(n.to_string().as_bytes());
}

pub fn pad(out: &mut Vec<u8>, depth: i32) {
    for _ in 0..depth * 2 {
        out.push(b' ');
    }
}

pub fn strs(out: &mut Vec<u8>, v: &[String], depth: i32) {
    if v.is_empty() {
        out.extend_from_slice(b"[]");
        return;
    }
    out.extend_from_slice(b"[\n");
    for (i, s) in v.iter().enumerate() {
        pad(out, depth + 1);
        esc(out, s);
        if i + 1 < v.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b']');
}

fn ws(c: u8) -> bool {
    c == b' ' || c == b'\t' || c == b'\n' || c == b'\r'
}

pub fn raw(out: &mut Vec<u8>, b: &[u8], depth: i32) {
    let mut depth = depth;
    let mut i = 0;
    while i < b.len() {
        let c = b[i];
        if ws(c) {
            i += 1;
        } else if c == b'"' {
            let mut j = i + 1;
            while j < b.len() {
                if b[j] == b'\\' {
                    j += 2;
                    continue;
                }
                if b[j] == b'"' {
                    j += 1;
                    break;
                }
                j += 1;
            }
            out.extend_from_slice(&b[i..j]);
            i = j;
        } else if c == b'{' || c == b'[' {
            out.push(c);
            i += 1;
            let mut j = i;
            while j < b.len() && ws(b[j]) {
                j += 1;
            }
            if j < b.len() && (b[j] == b'}' || b[j] == b']') {
                out.push(b[j]);
                i = j + 1;
            } else {
                depth += 1;
                out.push(b'\n');
                pad(out, depth);
            }
        } else if c == b'}' || c == b']' {
            depth -= 1;
            out.push(b'\n');
            pad(out, depth);
            out.push(c);
            i += 1;
        } else if c == b',' {
            out.extend_from_slice(b",\n");
            pad(out, depth);
            i += 1;
        } else if c == b':' {
            out.extend_from_slice(b": ");
            i += 1;
        } else {
            out.push(c);
            i += 1;
        }
    }
}

// A BTreeMap<String, _> walks its keys in String's Ord, which compares the
// UTF-8 bytes — the order the definition declares. Nothing sorts here.
pub fn rawmap(out: &mut Vec<u8>, m: &BTreeMap<String, Raw>, depth: i32) {
    if m.is_empty() {
        out.extend_from_slice(b"{}");
        return;
    }
    out.extend_from_slice(b"{\n");
    for (i, (k, v)) in m.iter().enumerate() {
        pad(out, depth + 1);
        esc(out, k);
        out.extend_from_slice(b": ");
        raw(out, v, depth + 1);
        if i + 1 < m.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b'}');
}

pub fn esc(out: &mut Vec<u8>, s: &str) {
    out.push(b'"');
    for c in s.as_bytes() {
        esc_byte(out, *c);
    }
    out.push(b'"');
}

pub fn strmap(out: &mut Vec<u8>, m: &BTreeMap<String, String>, depth: i32) {
    if m.is_empty() {
        out.extend_from_slice(b"{}");
        return;
    }
    out.extend_from_slice(b"{\n");
    for (i, (k, v)) in m.iter().enumerate() {
        pad(out, depth + 1);
        esc(out, k);
        out.extend_from_slice(b": ");
        esc(out, v);
        if i + 1 < m.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b'}');
}

pub const USERREPLACEOUTCOME_NAMES: [&str; 4] = ["applied", "conflict", "forbidden", "unavailable"];
pub const USERREPLACEOUTCOME_UNKNOWN: &str = "refuse";

pub const CONFIGOBSERVATIONOUTCOME_NAMES: [&str; 6] = ["snapshot", "unchanged", "gap", "unavailable", "unsupported", "invalid"];
pub const CONFIGOBSERVATIONOUTCOME_UNKNOWN: &str = "refuse";

#[derive(Default)]
pub struct RunOverrides {
    pub nas_store: String,
    pub store: String,
    pub log_sink: String,
    pub log_service: String,
}

#[derive(Default)]
pub struct Origin {
    pub rung: String,
    pub path: String,
}

#[derive(Default)]
pub struct Origins {
    pub nas_store: Origin,
    pub store: Origin,
    pub log_sink: Origin,
    pub log_service: Origin,
    pub off: Origin,
}

#[derive(Default)]
pub struct Snapshot {
    pub nas_store: String,
    pub store: String,
    pub log_sink: String,
    pub log_service: String,
    pub off: BTreeMap<String, String>,
    pub origins: Origins,
    pub stamp: String,
}

#[derive(Default)]
pub struct UserSettings {
    pub nas_store: String,
    pub store: String,
    pub log_sink: String,
    pub log_service: String,
    pub off: BTreeMap<String, String>,
}

#[derive(Default)]
pub struct UserSnapshot {
    pub values: UserSettings,
    pub revision: String,
}

#[derive(Default)]
pub struct UserReplaceResult {
    pub outcome: String,
    pub snapshot: UserSnapshot,
}

#[derive(Default)]
pub struct ConfigObservation {
    pub outcome: String,
    pub cursor: String,
    pub snapshot: Option<Snapshot>,
}

#[derive(Default)]
pub struct OAConfigReaderReadArguments {
    pub overrides: RunOverrides,
}

#[derive(Default)]
pub struct OAConfigEditorReadUserArguments {
}

#[derive(Default)]
pub struct OAConfigEditorReplaceUserArguments {
    pub expected_revision: String,
    pub values: UserSettings,
}

#[derive(Default)]
pub struct OAConfigObserverObserveArguments {
    pub overrides: RunOverrides,
    pub cursor: String,
    pub wait_ms: i64,
}

#[derive(Default)]
pub struct OAServiceFrame {
    pub version: i32,
    pub service: String,
    pub method: String,
    pub arguments: Raw,
}

#[derive(Default)]
pub struct OAServiceReply {
    pub version: i32,
    pub service: String,
    pub method: String,
    pub ok: bool,
    pub payload: Raw,
}

#[derive(Default)]
pub struct OAServiceError {
    pub code: String,
    pub message: String,
}

#[derive(Default)]
pub struct OAConfigReaderReadResult {
    pub value: Snapshot,
}

#[derive(Default)]
pub struct OAConfigEditorReadUserResult {
    pub value: UserSnapshot,
}

#[derive(Default)]
pub struct OAConfigEditorReplaceUserResult {
    pub value: UserReplaceResult,
}

#[derive(Default)]
pub struct OAConfigObserverObserveResult {
    pub value: ConfigObservation,
}

pub fn enc_runoverrides(out: &mut Vec<u8>, v: &RunOverrides, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "nas_store");
    out.extend_from_slice(b": ");
    esc(out, &v.nas_store);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "store");
    out.extend_from_slice(b": ");
    esc(out, &v.store);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "log_sink");
    out.extend_from_slice(b": ");
    esc(out, &v.log_sink);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "log_service");
    out.extend_from_slice(b": ");
    esc(out, &v.log_service);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_origin(out: &mut Vec<u8>, v: &Origin, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "rung");
    out.extend_from_slice(b": ");
    esc(out, &v.rung);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "path");
    out.extend_from_slice(b": ");
    esc(out, &v.path);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_origins(out: &mut Vec<u8>, v: &Origins, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "nas_store");
    out.extend_from_slice(b": ");
    enc_origin(out, &v.nas_store, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "store");
    out.extend_from_slice(b": ");
    enc_origin(out, &v.store, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "log_sink");
    out.extend_from_slice(b": ");
    enc_origin(out, &v.log_sink, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "log_service");
    out.extend_from_slice(b": ");
    enc_origin(out, &v.log_service, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "off");
    out.extend_from_slice(b": ");
    enc_origin(out, &v.off, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_snapshot(out: &mut Vec<u8>, v: &Snapshot, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "nas_store");
    out.extend_from_slice(b": ");
    esc(out, &v.nas_store);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "store");
    out.extend_from_slice(b": ");
    esc(out, &v.store);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "log_sink");
    out.extend_from_slice(b": ");
    esc(out, &v.log_sink);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "log_service");
    out.extend_from_slice(b": ");
    esc(out, &v.log_service);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "off");
    out.extend_from_slice(b": ");
    strmap(out, &v.off, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "origins");
    out.extend_from_slice(b": ");
    enc_origins(out, &v.origins, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "stamp");
    out.extend_from_slice(b": ");
    esc(out, &v.stamp);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_usersettings(out: &mut Vec<u8>, v: &UserSettings, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "nas_store");
    out.extend_from_slice(b": ");
    esc(out, &v.nas_store);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "store");
    out.extend_from_slice(b": ");
    esc(out, &v.store);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "log_sink");
    out.extend_from_slice(b": ");
    esc(out, &v.log_sink);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "log_service");
    out.extend_from_slice(b": ");
    esc(out, &v.log_service);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "off");
    out.extend_from_slice(b": ");
    strmap(out, &v.off, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_usersnapshot(out: &mut Vec<u8>, v: &UserSnapshot, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "values");
    out.extend_from_slice(b": ");
    enc_usersettings(out, &v.values, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "revision");
    out.extend_from_slice(b": ");
    esc(out, &v.revision);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_userreplaceresult(out: &mut Vec<u8>, v: &UserReplaceResult, depth: i32) {
    if v.outcome != "applied" && v.outcome != "conflict" && v.outcome != "forbidden" && v.outcome != "unavailable" { std::panic::panic_any(Refusal{word:"bad_enum",offset:0}); }
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "outcome");
    out.extend_from_slice(b": ");
    esc(out, &v.outcome);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "snapshot");
    out.extend_from_slice(b": ");
    enc_usersnapshot(out, &v.snapshot, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_configobservation(out: &mut Vec<u8>, v: &ConfigObservation, depth: i32) {
    if v.outcome != "snapshot" && v.outcome != "unchanged" && v.outcome != "gap" && v.outcome != "unavailable" && v.outcome != "unsupported" && v.outcome != "invalid" { std::panic::panic_any(Refusal{word:"bad_enum",offset:0}); }
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "outcome");
    out.extend_from_slice(b": ");
    esc(out, &v.outcome);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "cursor");
    out.extend_from_slice(b": ");
    esc(out, &v.cursor);
    if v.snapshot.is_some() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "snapshot");
        out.extend_from_slice(b": ");
        enc_snapshot(out, v.snapshot.as_ref().unwrap(), depth + 1);
    }
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaconfigreaderreadarguments(out: &mut Vec<u8>, v: &OAConfigReaderReadArguments, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "overrides");
    out.extend_from_slice(b": ");
    enc_runoverrides(out, &v.overrides, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaconfigeditorreaduserarguments(out: &mut Vec<u8>, v: &OAConfigEditorReadUserArguments, depth: i32) {
    out.push(b'{');
    out.push(b'}');
}

pub fn enc_oaconfigeditorreplaceuserarguments(out: &mut Vec<u8>, v: &OAConfigEditorReplaceUserArguments, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "expected_revision");
    out.extend_from_slice(b": ");
    esc(out, &v.expected_revision);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "values");
    out.extend_from_slice(b": ");
    enc_usersettings(out, &v.values, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaconfigobserverobservearguments(out: &mut Vec<u8>, v: &OAConfigObserverObserveArguments, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "overrides");
    out.extend_from_slice(b": ");
    enc_runoverrides(out, &v.overrides, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "cursor");
    out.extend_from_slice(b": ");
    esc(out, &v.cursor);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "wait_ms");
    out.extend_from_slice(b": ");
    num(out, v.wait_ms);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaserviceframe(out: &mut Vec<u8>, v: &OAServiceFrame, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "version");
    out.extend_from_slice(b": ");
    num(out, v.version as i64);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "service");
    out.extend_from_slice(b": ");
    esc(out, &v.service);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "method");
    out.extend_from_slice(b": ");
    esc(out, &v.method);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "arguments");
    out.extend_from_slice(b": ");
    out.extend_from_slice(&v.arguments);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaservicereply(out: &mut Vec<u8>, v: &OAServiceReply, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "version");
    out.extend_from_slice(b": ");
    num(out, v.version as i64);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "service");
    out.extend_from_slice(b": ");
    esc(out, &v.service);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "method");
    out.extend_from_slice(b": ");
    esc(out, &v.method);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "ok");
    out.extend_from_slice(b": ");
    out.extend_from_slice(if v.ok { b"true" } else { b"false" });
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "payload");
    out.extend_from_slice(b": ");
    out.extend_from_slice(&v.payload);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaserviceerror(out: &mut Vec<u8>, v: &OAServiceError, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "code");
    out.extend_from_slice(b": ");
    esc(out, &v.code);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "message");
    out.extend_from_slice(b": ");
    esc(out, &v.message);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaconfigreaderreadresult(out: &mut Vec<u8>, v: &OAConfigReaderReadResult, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "value");
    out.extend_from_slice(b": ");
    enc_snapshot(out, &v.value, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaconfigeditorreaduserresult(out: &mut Vec<u8>, v: &OAConfigEditorReadUserResult, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "value");
    out.extend_from_slice(b": ");
    enc_usersnapshot(out, &v.value, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaconfigeditorreplaceuserresult(out: &mut Vec<u8>, v: &OAConfigEditorReplaceUserResult, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "value");
    out.extend_from_slice(b": ");
    enc_userreplaceresult(out, &v.value, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaconfigobserverobserveresult(out: &mut Vec<u8>, v: &OAConfigObserverObserveResult, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "value");
    out.extend_from_slice(b": ");
    enc_configobservation(out, &v.value, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn encode(v: &Snapshot) -> Vec<u8> {
    let mut out = Vec::new();
    enc_snapshot(&mut out, v, 0);
    out.push(b'\n');
    out
}

const DEPTH_LIMIT: i32 = 64;

#[derive(Debug)]
pub struct Refusal {
    pub word: &'static str,
    pub offset: usize,
}

impl std::fmt::Display for Refusal {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "refused: {} at byte {}", self.word, self.offset)
    }
}

impl std::error::Error for Refusal {}

fn append_rune(out: &mut Vec<u8>, cp: u32) {
    if cp < 0x80 {
        out.push(cp as u8);
    } else if cp < 0x800 {
        out.push(0xC0 | (cp >> 6) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    } else if cp < 0x10000 {
        out.push(0xE0 | (cp >> 12) as u8);
        out.push(0x80 | ((cp >> 6) & 0x3F) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    } else {
        out.push(0xF0 | (cp >> 18) as u8);
        out.push(0x80 | ((cp >> 12) & 0x3F) as u8);
        out.push(0x80 | ((cp >> 6) & 0x3F) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    }
}

struct Reader<'a> {
    buf: &'a [u8],
    pos: usize,
    depth: i32,
}

impl<'a> Reader<'a> {
    fn refuse<T>(&self, word: &'static str) -> Result<T, Refusal> {
        Err(Refusal { word, offset: self.pos })
    }

    fn at(&self) -> u8 {
        if self.pos < self.buf.len() { self.buf[self.pos] } else { 0 }
    }

    fn skip_ws(&mut self) {
        while self.pos < self.buf.len() && ws(self.buf[self.pos]) {
            self.pos += 1;
        }
    }

    fn enter(&mut self) -> Result<(), Refusal> {
        self.depth += 1;
        if self.depth > DEPTH_LIMIT {
            return self.refuse("depth_exceeded");
        }
        Ok(())
    }

    fn string(&mut self) -> Result<String, Refusal> {
        if self.at() != b'"' {
            return self.refuse("wrong_type");
        }
        self.pos += 1;
        let mut out: Vec<u8> = Vec::new();
        loop {
            if self.pos >= self.buf.len() {
                return self.refuse("malformed");
            }
            let c = self.buf[self.pos];
            if c == b'"' {
                self.pos += 1;
                return match String::from_utf8(out) {
                    Ok(s) => Ok(s),
                    Err(_) => self.refuse("bad_string"),
                };
            }
            if c < 0x20 {
                return self.refuse("bad_string");
            }
            if c == b'\\' {
                self.escape(&mut out)?;
            } else {
                out.push(c);
                self.pos += 1;
            }
        }
    }

    fn escape(&mut self, out: &mut Vec<u8>) -> Result<(), Refusal> {
        self.pos += 1;
        if self.pos >= self.buf.len() {
            return self.refuse("malformed");
        }
        let c = self.buf[self.pos];
        self.pos += 1;
        match c {
            b'"' | b'\\' | b'/' => out.push(c),
            b'b' => out.push(0x08),
            b'f' => out.push(0x0c),
            b'n' => out.push(b'\n'),
            b'r' => out.push(b'\r'),
            b't' => out.push(b'\t'),
            b'u' => {
                let mut u = self.hex4()?;
                if (0xDC00..=0xDFFF).contains(&u) {
                    return self.refuse("bad_string");
                }
                if (0xD800..=0xDBFF).contains(&u) {
                    if self.pos + 1 >= self.buf.len()
                        || self.buf[self.pos] != b'\\'
                        || self.buf[self.pos + 1] != b'u'
                    {
                        return self.refuse("bad_string");
                    }
                    self.pos += 2;
                    let low = self.hex4()?;
                    if !(0xDC00..=0xDFFF).contains(&low) {
                        return self.refuse("bad_string");
                    }
                    u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00);
                }
                append_rune(out, u);
            }
            _ => return self.refuse("bad_string"),
        }
        Ok(())
    }

    fn hex4(&mut self) -> Result<u32, Refusal> {
        if self.pos + 4 > self.buf.len() {
            return self.refuse("bad_string");
        }
        let mut u: u32 = 0;
        for i in 0..4 {
            let c = self.buf[self.pos + i];
            let d = match c {
                b'0'..=b'9' => c - b'0',
                b'a'..=b'f' => c - b'a' + 10,
                b'A'..=b'F' => c - b'A' + 10,
                _ => return self.refuse("bad_string"),
            };
            u = u << 4 | d as u32;
        }
        self.pos += 4;
        Ok(u)
    }

    fn integer(&mut self, low: i64, high: i64) -> Result<i64, Refusal> {
        let c = self.at();
        if c != b'-' && !c.is_ascii_digit() {
            return self.refuse("wrong_type");
        }
        let negative = c == b'-';
        if negative {
            self.pos += 1;
        }
        if !self.at().is_ascii_digit() {
            return self.refuse("malformed");
        }
        let mut u: u64 = 0;
        if self.at() == b'0' {
            self.pos += 1;
        } else {
            while self.at().is_ascii_digit() {
                if u > 922337203685477580 {
                    return self.refuse("number_spelling");
                }
                u = u * 10 + (self.at() - b'0') as u64;
                self.pos += 1;
            }
        }
        let after = self.at();
        if after == b'.' || after == b'e' || after == b'E' || after.is_ascii_digit() {
            return self.refuse("number_spelling");
        }
        if negative && u == 0 {
            return self.refuse("number_spelling");
        }
        let n = if negative {
            if u > 1u64 << 63 {
                return self.refuse("number_spelling");
            }
            if u == 1u64 << 63 { i64::MIN } else { -(u as i64) }
        } else {
            if u > i64::MAX as u64 {
                return self.refuse("number_spelling");
            }
            u as i64
        };
        if n < low || n > high {
            return self.refuse("number_spelling");
        }
        Ok(n)
    }

    fn boolean(&mut self) -> Result<bool, Refusal> {
        match self.at() {
            b't' => {
                self.literal(b"true")?;
                Ok(true)
            }
            b'f' => {
                self.literal(b"false")?;
                Ok(false)
            }
            _ => self.refuse("wrong_type"),
        }
    }

    fn literal(&mut self, word: &[u8]) -> Result<(), Refusal> {
        if self.pos + word.len() > self.buf.len() || &self.buf[self.pos..self.pos + word.len()] != word {
            return self.refuse("malformed");
        }
        self.pos += word.len();
        Ok(())
    }

    fn str_list(&mut self) -> Result<Vec<String>, Refusal> {
        if self.at() != b'[' {
            return self.refuse("wrong_type");
        }
        self.enter()?;
        self.pos += 1;
        let mut out = Vec::new();
        self.skip_ws();
        if self.at() != b']' {
            loop {
                self.skip_ws();
                out.push(self.string()?);
                self.skip_ws();
                if self.at() != b',' {
                    break;
                }
                self.pos += 1;
            }
        }
        if self.at() != b']' {
            return self.refuse("malformed");
        }
        self.pos += 1;
        self.depth -= 1;
        Ok(out)
    }

    fn raw_map(&mut self) -> Result<BTreeMap<String, Raw>, Refusal> {
        if self.at() != b'{' {
            return self.refuse("wrong_type");
        }
        self.enter()?;
        self.pos += 1;
        let mut out = BTreeMap::new();
        self.skip_ws();
        if self.at() != b'}' {
            loop {
                self.skip_ws();
                if self.at() != b'"' {
                    return self.refuse("malformed");
                }
                let k = self.string()?;
                self.skip_ws();
                if self.at() != b':' {
                    return self.refuse("malformed");
                }
                self.pos += 1;
                self.skip_ws();
                let v = self.raw_value()?;
                out.insert(k, v);
                self.skip_ws();
                if self.at() != b',' {
                    break;
                }
                self.pos += 1;
            }
        }
        if self.at() != b'}' {
            return self.refuse("malformed");
        }
        self.pos += 1;
        self.depth -= 1;
        Ok(out)
    }

    fn raw_value(&mut self) -> Result<Raw, Refusal> {
        let start = self.pos;
        self.skip_value()?;
        Ok(self.buf[start..self.pos].to_vec())
    }

    fn skip_value(&mut self) -> Result<(), Refusal> {
        let c = self.at();
        match c {
            b'"' => self.skip_string(),
            b'{' | b'[' => self.skip_container(),
            b't' => self.literal(b"true"),
            b'f' => self.literal(b"false"),
            b'n' => self.literal(b"null"),
            b'-' => self.skip_number(),
            _ if c.is_ascii_digit() => self.skip_number(),
            _ => self.refuse("malformed"),
        }
    }

    // An opaque value is validated and carried, never interpreted. Its syntax is
    // the record's own — the same string reader, so an escape, a control byte or
    // a lone surrogate is judged identically at any depth — and what it is free
    // to spell, it keeps: the bytes between these two offsets are what a writer
    // re-emits. A number is walked, never converted, so a value no host type
    // holds survives the reader that carried it.
    fn skip_string(&mut self) -> Result<(), Refusal> {
        self.string()?;
        Ok(())
    }

    fn some_digits(&mut self) -> Result<(), Refusal> {
        let mut n = 0;
        while self.at().is_ascii_digit() {
            self.pos += 1;
            n += 1;
        }
        if n == 0 {
            return self.refuse("number_spelling");
        }
        Ok(())
    }

    fn skip_number(&mut self) -> Result<(), Refusal> {
        if self.at() == b'-' {
            self.pos += 1;
        }
        match self.at() {
            b'0' => self.pos += 1,
            c if c.is_ascii_digit() => {
                while self.at().is_ascii_digit() {
                    self.pos += 1;
                }
            }
            _ => return self.refuse("number_spelling"),
        }
        if self.at() == b'.' {
            self.pos += 1;
            self.some_digits()?;
        }
        if self.at() == b'e' || self.at() == b'E' {
            self.pos += 1;
            if self.at() == b'+' || self.at() == b'-' {
                self.pos += 1;
            }
            self.some_digits()?;
        }
        Ok(())
    }

    fn skip_container(&mut self) -> Result<(), Refusal> {
        let opener = self.at();
        let shut = if opener == b'{' { b'}' } else { b']' };
        self.enter()?;
        self.pos += 1;
        self.skip_ws();
        if self.at() != shut {
            loop {
                self.skip_ws();
                if opener == b'{' {
                    if self.at() != b'"' {
                        return self.refuse("malformed");
                    }
                    self.string()?;
                    self.skip_ws();
                    if self.at() != b':' {
                        return self.refuse("malformed");
                    }
                    self.pos += 1;
                    self.skip_ws();
                }
                self.skip_value()?;
                self.skip_ws();
                if self.at() != b',' {
                    break;
                }
                self.pos += 1;
            }
        }
        if self.at() != shut {
            return self.refuse("malformed");
        }
        self.pos += 1;
        self.depth -= 1;
        Ok(())
    }
}

fn str_map(r: &mut Reader) -> Result<BTreeMap<String, String>, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut out = BTreeMap::new();
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let k = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            let v = r.string()?;
            out.insert(k, v);
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    Ok(out)
}

fn decode_runoverrides(r: &mut Reader) -> Result<RunOverrides, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = RunOverrides::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "nas_store" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.nas_store = r.string()?;
                }
                "store" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.store = r.string()?;
                }
                "log_sink" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.log_sink = r.string()?;
                }
                "log_service" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.log_service = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 15 != 15 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_origin(r: &mut Reader) -> Result<Origin, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = Origin::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "rung" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.rung = r.string()?;
                }
                "path" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.path = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_origins(r: &mut Reader) -> Result<Origins, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = Origins::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "nas_store" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.nas_store = decode_origin(r)?;
                }
                "store" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.store = decode_origin(r)?;
                }
                "log_sink" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.log_sink = decode_origin(r)?;
                }
                "log_service" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.log_service = decode_origin(r)?;
                }
                "off" => {
                    if seen & 16 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 16;
                    v.off = decode_origin(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 31 != 31 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_snapshot(r: &mut Reader) -> Result<Snapshot, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = Snapshot::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "nas_store" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.nas_store = r.string()?;
                }
                "store" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.store = r.string()?;
                }
                "log_sink" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.log_sink = r.string()?;
                }
                "log_service" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.log_service = r.string()?;
                }
                "off" => {
                    if seen & 16 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 16;
                    v.off = str_map(r)?;
                }
                "origins" => {
                    if seen & 32 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 32;
                    v.origins = decode_origins(r)?;
                }
                "stamp" => {
                    if seen & 64 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 64;
                    v.stamp = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 127 != 127 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_usersettings(r: &mut Reader) -> Result<UserSettings, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = UserSettings::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "nas_store" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.nas_store = r.string()?;
                }
                "store" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.store = r.string()?;
                }
                "log_sink" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.log_sink = r.string()?;
                }
                "log_service" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.log_service = r.string()?;
                }
                "off" => {
                    if seen & 16 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 16;
                    v.off = str_map(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 31 != 31 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_usersnapshot(r: &mut Reader) -> Result<UserSnapshot, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = UserSnapshot::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "values" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.values = decode_usersettings(r)?;
                }
                "revision" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.revision = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_userreplaceresult(r: &mut Reader) -> Result<UserReplaceResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = UserReplaceResult::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "outcome" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.outcome = r.string()?;
                }
                "snapshot" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.snapshot = decode_usersnapshot(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    if v.outcome != "applied" && v.outcome != "conflict" && v.outcome != "forbidden" && v.outcome != "unavailable" { return r.refuse("bad_enum"); }
    Ok(v)
}

fn decode_configobservation(r: &mut Reader) -> Result<ConfigObservation, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = ConfigObservation::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "outcome" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.outcome = r.string()?;
                }
                "cursor" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.cursor = r.string()?;
                }
                "snapshot" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.snapshot = Some(decode_snapshot(r)?);
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    if v.outcome != "snapshot" && v.outcome != "unchanged" && v.outcome != "gap" && v.outcome != "unavailable" && v.outcome != "unsupported" && v.outcome != "invalid" { return r.refuse("bad_enum"); }
    Ok(v)
}

fn decode_oaconfigreaderreadarguments(r: &mut Reader) -> Result<OAConfigReaderReadArguments, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAConfigReaderReadArguments::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "overrides" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.overrides = decode_runoverrides(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaconfigeditorreaduserarguments(r: &mut Reader) -> Result<OAConfigEditorReadUserArguments, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAConfigEditorReadUserArguments::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    Ok(v)
}

fn decode_oaconfigeditorreplaceuserarguments(r: &mut Reader) -> Result<OAConfigEditorReplaceUserArguments, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAConfigEditorReplaceUserArguments::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "expected_revision" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.expected_revision = r.string()?;
                }
                "values" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.values = decode_usersettings(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaconfigobserverobservearguments(r: &mut Reader) -> Result<OAConfigObserverObserveArguments, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAConfigObserverObserveArguments::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "overrides" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.overrides = decode_runoverrides(r)?;
                }
                "cursor" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.cursor = r.string()?;
                }
                "wait_ms" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.wait_ms = r.integer(i64::MIN, i64::MAX)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 7 != 7 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaserviceframe(r: &mut Reader) -> Result<OAServiceFrame, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAServiceFrame::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "version" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.version = r.integer(-2147483648, 2147483647)? as i32;
                }
                "service" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.service = r.string()?;
                }
                "method" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.method = r.string()?;
                }
                "arguments" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.arguments = r.raw_value()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 15 != 15 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaservicereply(r: &mut Reader) -> Result<OAServiceReply, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAServiceReply::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "version" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.version = r.integer(-2147483648, 2147483647)? as i32;
                }
                "service" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.service = r.string()?;
                }
                "method" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.method = r.string()?;
                }
                "ok" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.ok = r.boolean()?;
                }
                "payload" => {
                    if seen & 16 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 16;
                    v.payload = r.raw_value()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 31 != 31 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaserviceerror(r: &mut Reader) -> Result<OAServiceError, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAServiceError::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "code" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.code = r.string()?;
                }
                "message" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.message = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaconfigreaderreadresult(r: &mut Reader) -> Result<OAConfigReaderReadResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAConfigReaderReadResult::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "value" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.value = decode_snapshot(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaconfigeditorreaduserresult(r: &mut Reader) -> Result<OAConfigEditorReadUserResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAConfigEditorReadUserResult::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "value" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.value = decode_usersnapshot(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaconfigeditorreplaceuserresult(r: &mut Reader) -> Result<OAConfigEditorReplaceUserResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAConfigEditorReplaceUserResult::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "value" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.value = decode_userreplaceresult(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaconfigobserverobserveresult(r: &mut Reader) -> Result<OAConfigObserverObserveResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAConfigObserverObserveResult::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "value" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.value = decode_configobservation(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

pub fn decode(data: &[u8]) -> Result<Snapshot, Refusal> {
    let mut r = Reader { buf: data, pos: 0, depth: 0 };
    r.skip_ws();
    let v = decode_snapshot(&mut r)?;
    r.skip_ws();
    if r.pos < r.buf.len() {
        return r.refuse("trailing_bytes");
    }
    Ok(v)
}

// REFUSALS is in the order two of them are chosen between.
pub const REFUSALS: [&str; 10] = ["malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"];

pub fn refusal_rank(word: &str) -> i32 {
    match REFUSALS.iter().position(|w| *w == word) {
        Some(i) => i as i32,
        None => -1,
    }
}

#[allow(unused_variables)]
fn service_check_runoverrides(v: &RunOverrides) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_origin(v: &Origin) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_origins(v: &Origins) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_origin(&v.nas_store)?;
    service_check_origin(&v.store)?;
    service_check_origin(&v.log_sink)?;
    service_check_origin(&v.log_service)?;
    service_check_origin(&v.off)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_snapshot(v: &Snapshot) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_origins(&v.origins)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_usersettings(v: &UserSettings) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_usersnapshot(v: &UserSnapshot) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_usersettings(&v.values)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_userreplaceresult(v: &UserReplaceResult) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    if v.outcome != "applied" && v.outcome != "conflict" && v.outcome != "forbidden" && v.outcome != "unavailable" { return r.refuse("bad_enum"); }
    service_check_usersnapshot(&v.snapshot)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_configobservation(v: &ConfigObservation) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    if v.outcome != "snapshot" && v.outcome != "unchanged" && v.outcome != "gap" && v.outcome != "unavailable" && v.outcome != "unsupported" && v.outcome != "invalid" { return r.refuse("bad_enum"); }
    if let Some(value) = &v.snapshot { service_check_snapshot(value)?; }
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaconfigreaderreadarguments(v: &OAConfigReaderReadArguments) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_runoverrides(&v.overrides)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaconfigeditorreaduserarguments(v: &OAConfigEditorReadUserArguments) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaconfigeditorreplaceuserarguments(v: &OAConfigEditorReplaceUserArguments) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_usersettings(&v.values)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaconfigobserverobservearguments(v: &OAConfigObserverObserveArguments) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_runoverrides(&v.overrides)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaserviceframe(v: &OAServiceFrame) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaservicereply(v: &OAServiceReply) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaserviceerror(v: &OAServiceError) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaconfigreaderreadresult(v: &OAConfigReaderReadResult) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_snapshot(&v.value)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaconfigeditorreaduserresult(v: &OAConfigEditorReadUserResult) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_usersnapshot(&v.value)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaconfigeditorreplaceuserresult(v: &OAConfigEditorReplaceUserResult) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_userreplaceresult(&v.value)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaconfigobserverobserveresult(v: &OAConfigObserverObserveResult) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_configobservation(&v.value)?;
    Ok(())
}

/// Common generated framing boundary; implementation owns waiting and identity.
pub use abstraction_frame::FrameTransport;

#[derive(Debug)]
pub struct ServiceError { pub code: String, pub message: String }
#[derive(Debug)]
pub enum CallError<E> {
    /// Transport failure does not establish whether the receiver accepted work.
    Transport(E),
    Refusal(Refusal),
    Dispatch(&'static str),
    Service(ServiceError),
}
fn service_decode<T>(data: &[u8], decode: fn(&mut Reader) -> Result<T, Refusal>) -> Result<T, Refusal> {
    let mut r = Reader { buf: data, pos: 0, depth: 0 };
    r.skip_ws();
    let value = decode(&mut r)?;
    r.skip_ws();
    if r.pos != data.len() { return r.refuse("trailing_bytes"); }
    Ok(value)
}
fn service_encode<T>(value: &T, check: fn(&T) -> Result<(), Refusal>, encode: fn(&mut Vec<u8>, &T, i32), decode: fn(&mut Reader) -> Result<T, Refusal>) -> Result<Vec<u8>, Refusal> {
    check(value)?;
    let mut data = Vec::new();
    encode(&mut data, value, 0);
    service_decode(&data, decode)?;
    Ok(data)
}

#[allow(non_snake_case)]
pub trait ConfigReader {
    type Error;
    fn Read(&self, arg0: RunOverrides) -> Result<Snapshot, Self::Error>;
}

pub struct ConfigReaderClient<T> { transport: T }
impl<T> ConfigReaderClient<T> {
    pub fn new(transport: T) -> Self { Self { transport } }
    pub fn transport(&self) -> &T { &self.transport }
}
#[allow(non_snake_case)]
impl<T: FrameTransport> ConfigReader for ConfigReaderClient<T> {
    type Error = CallError<T::Error>;
    fn Read(&self, arg0: RunOverrides) -> Result<Snapshot, Self::Error> {
        let args = OAConfigReaderReadArguments { overrides: arg0, };
        let arguments = service_encode(&args, service_check_oaconfigreaderreadarguments, enc_oaconfigreaderreadarguments, decode_oaconfigreaderreadarguments).map_err(CallError::Refusal)?;
        let request = OAServiceFrame { version: 1, service: "abstraction.config/reader@1".into(), method: "Read".into(), arguments };
        let frame = service_encode(&request, service_check_oaserviceframe, enc_oaserviceframe, decode_oaserviceframe).map_err(CallError::Refusal)?;
        let reply = self.transport.exchange_frame(&frame).map_err(CallError::Transport)?;
        let reply = service_decode(&reply, decode_oaservicereply).map_err(CallError::Refusal)?;
        if reply.version != 1 { return Err(CallError::Dispatch("unknown_version")); }
        if reply.service != "abstraction.config/reader@1" || reply.method != "Read" { return Err(CallError::Dispatch("mismatched_response")); }
        if !reply.ok {
            let error = service_decode(&reply.payload, decode_oaserviceerror).map_err(CallError::Refusal)?;
            if error.code.is_empty() { return Err(CallError::Dispatch("invalid_error")); }
            return Err(CallError::Service(ServiceError { code: error.code, message: error.message }));
        }
        let result = service_decode(&reply.payload, decode_oaconfigreaderreadresult).map_err(CallError::Refusal)?;
        Ok(result.value)
    }
}

#[allow(non_snake_case)]
pub trait ConfigEditor {
    type Error;
    fn ReadUser(&self) -> Result<UserSnapshot, Self::Error>;
    fn ReplaceUser(&self, arg0: String, arg1: UserSettings) -> Result<UserReplaceResult, Self::Error>;
}

pub struct ConfigEditorClient<T> { transport: T }
impl<T> ConfigEditorClient<T> {
    pub fn new(transport: T) -> Self { Self { transport } }
    pub fn transport(&self) -> &T { &self.transport }
}
#[allow(non_snake_case)]
impl<T: FrameTransport> ConfigEditor for ConfigEditorClient<T> {
    type Error = CallError<T::Error>;
    fn ReadUser(&self) -> Result<UserSnapshot, Self::Error> {
        let args = OAConfigEditorReadUserArguments { };
        let arguments = service_encode(&args, service_check_oaconfigeditorreaduserarguments, enc_oaconfigeditorreaduserarguments, decode_oaconfigeditorreaduserarguments).map_err(CallError::Refusal)?;
        let request = OAServiceFrame { version: 1, service: "abstraction.config/editor@1".into(), method: "ReadUser".into(), arguments };
        let frame = service_encode(&request, service_check_oaserviceframe, enc_oaserviceframe, decode_oaserviceframe).map_err(CallError::Refusal)?;
        let reply = self.transport.exchange_frame(&frame).map_err(CallError::Transport)?;
        let reply = service_decode(&reply, decode_oaservicereply).map_err(CallError::Refusal)?;
        if reply.version != 1 { return Err(CallError::Dispatch("unknown_version")); }
        if reply.service != "abstraction.config/editor@1" || reply.method != "ReadUser" { return Err(CallError::Dispatch("mismatched_response")); }
        if !reply.ok {
            let error = service_decode(&reply.payload, decode_oaserviceerror).map_err(CallError::Refusal)?;
            if error.code.is_empty() { return Err(CallError::Dispatch("invalid_error")); }
            return Err(CallError::Service(ServiceError { code: error.code, message: error.message }));
        }
        let result = service_decode(&reply.payload, decode_oaconfigeditorreaduserresult).map_err(CallError::Refusal)?;
        Ok(result.value)
    }
    fn ReplaceUser(&self, arg0: String, arg1: UserSettings) -> Result<UserReplaceResult, Self::Error> {
        let args = OAConfigEditorReplaceUserArguments { expected_revision: arg0, values: arg1, };
        let arguments = service_encode(&args, service_check_oaconfigeditorreplaceuserarguments, enc_oaconfigeditorreplaceuserarguments, decode_oaconfigeditorreplaceuserarguments).map_err(CallError::Refusal)?;
        let request = OAServiceFrame { version: 1, service: "abstraction.config/editor@1".into(), method: "ReplaceUser".into(), arguments };
        let frame = service_encode(&request, service_check_oaserviceframe, enc_oaserviceframe, decode_oaserviceframe).map_err(CallError::Refusal)?;
        let reply = self.transport.exchange_frame(&frame).map_err(CallError::Transport)?;
        let reply = service_decode(&reply, decode_oaservicereply).map_err(CallError::Refusal)?;
        if reply.version != 1 { return Err(CallError::Dispatch("unknown_version")); }
        if reply.service != "abstraction.config/editor@1" || reply.method != "ReplaceUser" { return Err(CallError::Dispatch("mismatched_response")); }
        if !reply.ok {
            let error = service_decode(&reply.payload, decode_oaserviceerror).map_err(CallError::Refusal)?;
            if error.code.is_empty() { return Err(CallError::Dispatch("invalid_error")); }
            return Err(CallError::Service(ServiceError { code: error.code, message: error.message }));
        }
        let result = service_decode(&reply.payload, decode_oaconfigeditorreplaceuserresult).map_err(CallError::Refusal)?;
        Ok(result.value)
    }
}

#[allow(non_snake_case)]
pub trait ConfigObserver {
    type Error;
    fn Observe(&self, arg0: RunOverrides, arg1: String, arg2: i64) -> Result<ConfigObservation, Self::Error>;
}

pub struct ConfigObserverClient<T> { transport: T }
impl<T> ConfigObserverClient<T> {
    pub fn new(transport: T) -> Self { Self { transport } }
    pub fn transport(&self) -> &T { &self.transport }
}
#[allow(non_snake_case)]
impl<T: FrameTransport> ConfigObserver for ConfigObserverClient<T> {
    type Error = CallError<T::Error>;
    fn Observe(&self, arg0: RunOverrides, arg1: String, arg2: i64) -> Result<ConfigObservation, Self::Error> {
        let args = OAConfigObserverObserveArguments { overrides: arg0, cursor: arg1, wait_ms: arg2, };
        let arguments = service_encode(&args, service_check_oaconfigobserverobservearguments, enc_oaconfigobserverobservearguments, decode_oaconfigobserverobservearguments).map_err(CallError::Refusal)?;
        let request = OAServiceFrame { version: 1, service: "abstraction.config/observer@1".into(), method: "Observe".into(), arguments };
        let frame = service_encode(&request, service_check_oaserviceframe, enc_oaserviceframe, decode_oaserviceframe).map_err(CallError::Refusal)?;
        let reply = self.transport.exchange_frame(&frame).map_err(CallError::Transport)?;
        let reply = service_decode(&reply, decode_oaservicereply).map_err(CallError::Refusal)?;
        if reply.version != 1 { return Err(CallError::Dispatch("unknown_version")); }
        if reply.service != "abstraction.config/observer@1" || reply.method != "Observe" { return Err(CallError::Dispatch("mismatched_response")); }
        if !reply.ok {
            let error = service_decode(&reply.payload, decode_oaserviceerror).map_err(CallError::Refusal)?;
            if error.code.is_empty() { return Err(CallError::Dispatch("invalid_error")); }
            return Err(CallError::Service(ServiceError { code: error.code, message: error.message }));
        }
        let result = service_decode(&reply.payload, decode_oaconfigobserverobserveresult).map_err(CallError::Refusal)?;
        Ok(result.value)
    }
}
