// Code generated by abstraction-idl from abstraction-config/config.thrift. DO NOT EDIT.

use std::collections::BTreeMap;

// An opaque payload is bytes the contract forbids us to reinterpret, and String
// would refuse to hold one that is not UTF-8 rather than carry it back out.
pub type Raw = Vec<u8>;

const HEX: &[u8; 16] = b"0123456789abcdef";

fn esc_byte(out: &mut Vec<u8>, c: u8) {
    match c {
        b'"' => out.extend_from_slice(b"\\\""),
        b'\\' => out.extend_from_slice(b"\\\\"),
        0x08 => out.extend_from_slice(b"\\b"),
        0x0c => out.extend_from_slice(b"\\f"),
        b'\n' => out.extend_from_slice(b"\\n"),
        b'\r' => out.extend_from_slice(b"\\r"),
        b'\t' => out.extend_from_slice(b"\\t"),
        _ if c < 0x20 => {
            out.extend_from_slice(b"\\u00");
            out.push(HEX[(c >> 4) as usize]);
            out.push(HEX[(c & 0x0F) as usize]);
        }
        _ => out.push(c),
    }
}

fn num(out: &mut Vec<u8>, n: i64) {
    out.extend_from_slice(n.to_string().as_bytes());
}

fn pad(out: &mut Vec<u8>, depth: i32) {
    for _ in 0..depth * 2 {
        out.push(b' ');
    }
}

fn ws(c: u8) -> bool {
    c == b' ' || c == b'\t' || c == b'\n' || c == b'\r'
}

fn esc(out: &mut Vec<u8>, s: &str) {
    out.push(b'"');
    for c in s.as_bytes() {
        esc_byte(out, *c);
    }
    out.push(b'"');
}

fn strmap(out: &mut Vec<u8>, m: &BTreeMap<String, String>, depth: i32) {
    if m.is_empty() {
        out.extend_from_slice(b"{}");
        return;
    }
    out.extend_from_slice(b"{\n");
    for (i, (k, v)) in m.iter().enumerate() {
        pad(out, depth + 1);
        esc(out, k);
        out.extend_from_slice(b": ");
        esc(out, v);
        if i + 1 < m.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b'}');
}

/// The closed vocabulary UserReplaceOutcome. A reader refuses a name it does not list.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum UserReplaceOutcome {
    Applied,
    Conflict,
    Forbidden,
    Unavailable,
}

impl UserReplaceOutcome {
    /// Every member, in declaration order.
    pub const ALL: [Self; 4] = [Self::Applied, Self::Conflict, Self::Forbidden, Self::Unavailable];

    /// The member's name on the wire.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Applied => "applied",
            Self::Conflict => "conflict",
            Self::Forbidden => "forbidden",
            Self::Unavailable => "unavailable",
        }
    }

    /// The member a wire name spells, or `None` for a name this vocabulary refuses.
    pub fn from_wire(name: &str) -> Option<Self> {
        match name {
            "applied" => Some(Self::Applied),
            "conflict" => Some(Self::Conflict),
            "forbidden" => Some(Self::Forbidden),
            "unavailable" => Some(Self::Unavailable),
            _ => None,
        }
    }
}

impl std::fmt::Display for UserReplaceOutcome {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl PartialEq<str> for UserReplaceOutcome {
    fn eq(&self, other: &str) -> bool {
        self.as_str() == other
    }
}

impl PartialEq<&str> for UserReplaceOutcome {
    fn eq(&self, other: &&str) -> bool {
        self.as_str() == *other
    }
}

/// The closed vocabulary ConfigObservationOutcome. A reader refuses a name it does not list.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum ConfigObservationOutcome {
    Snapshot,
    Unchanged,
    Gap,
    Unavailable,
    Unsupported,
    Invalid,
}

impl ConfigObservationOutcome {
    /// Every member, in declaration order.
    pub const ALL: [Self; 6] = [Self::Snapshot, Self::Unchanged, Self::Gap, Self::Unavailable, Self::Unsupported, Self::Invalid];

    /// The member's name on the wire.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Snapshot => "snapshot",
            Self::Unchanged => "unchanged",
            Self::Gap => "gap",
            Self::Unavailable => "unavailable",
            Self::Unsupported => "unsupported",
            Self::Invalid => "invalid",
        }
    }

    /// The member a wire name spells, or `None` for a name this vocabulary refuses.
    pub fn from_wire(name: &str) -> Option<Self> {
        match name {
            "snapshot" => Some(Self::Snapshot),
            "unchanged" => Some(Self::Unchanged),
            "gap" => Some(Self::Gap),
            "unavailable" => Some(Self::Unavailable),
            "unsupported" => Some(Self::Unsupported),
            "invalid" => Some(Self::Invalid),
            _ => None,
        }
    }
}

impl std::fmt::Display for ConfigObservationOutcome {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl PartialEq<str> for ConfigObservationOutcome {
    fn eq(&self, other: &str) -> bool {
        self.as_str() == other
    }
}

impl PartialEq<&str> for ConfigObservationOutcome {
    fn eq(&self, other: &&str) -> bool {
        self.as_str() == *other
    }
}

/// Names of the open vocabulary ServiceErrorCode. A reader keeps a name it has never heard
/// of, so fields carry `String` and a match needs an arm for the rest.
pub mod service_error_code {
    pub const HANDLER_ERROR: &str = "handler_error";
    pub const INVALID_RESULT: &str = "invalid_result";
    pub const UNKNOWN_VERSION: &str = "unknown_version";
    pub const UNKNOWN_SERVICE: &str = "unknown_service";
    pub const UNKNOWN_METHOD: &str = "unknown_method";
    pub const WRONG_MODE: &str = "wrong_mode";
    pub const STORAGE_UNAVAILABLE: &str = "storage_unavailable";
    pub const CALLER_UNAVAILABLE: &str = "caller_unavailable";
    pub const IDENTITY_REQUIRED: &str = "identity_required";
    pub const WRONG_USER: &str = "wrong_user";
    pub const INVALID_REVISION: &str = "invalid_revision";
    /// Every name this definition declares, in declaration order.
    pub const ALL: [&str; 11] = [HANDLER_ERROR, INVALID_RESULT, UNKNOWN_VERSION, UNKNOWN_SERVICE, UNKNOWN_METHOD, WRONG_MODE, STORAGE_UNAVAILABLE, CALLER_UNAVAILABLE, IDENTITY_REQUIRED, WRONG_USER, INVALID_REVISION];
}

pub const READER_ERROR_CODES: [&str; 4] = ["storage_unavailable", "caller_unavailable", "identity_required", "wrong_user"];

pub const EDITOR_ERROR_CODES: [&str; 5] = ["invalid_revision", "storage_unavailable", "caller_unavailable", "identity_required", "wrong_user"];

/// Existing per-run overrides. Empty strings do not override file values.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct RunOverrides {
    pub nas_store: String,
    pub store: String,
    pub log_sink: String,
    pub log_service: String,
}

/// Per-key provenance: machine/user file path, or environment/default with
/// empty path.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Origin {
    pub rung: String,
    pub path: String,
}

/// Provenance for every configuration key, including default answers.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Origins {
    pub nas_store: Origin,
    pub store: Origin,
    pub log_sink: Origin,
    pub log_service: Origin,
    pub off: Origin,
}

/// Existing provider values and provenance. Empty values mean absence. Stamp
/// follows values rather than provenance; paths are diagnostic configuration
/// data, not permission to access a store.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Snapshot {
    pub nas_store: String,
    pub store: String,
    pub log_sink: String,
    pub log_service: String,
    pub off: BTreeMap<String, String>,
    pub origins: Origins,
    pub stamp: String,
}

/// User-rung overrides only. Empty values clear overrides; machine and run
/// values never enter this record. The configuration backing-file path is
/// selected by the service; path-valued settings grant no provider storage
/// authority.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct UserSettings {
    pub nas_store: String,
    pub store: String,
    pub log_sink: String,
    pub log_service: String,
    pub off: BTreeMap<String, String>,
}

/// Normalized user-rung content and an opaque content revision. A missing file
/// yields empty values; unreadable or unsupported storage is refused. Revision
/// may recur when identical content is restored.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct UserSnapshot {
    pub values: UserSettings,
    pub revision: String,
}

/// Applied returns the written snapshot. Conflict performs no write and returns
/// the current snapshot. Forbidden reports an evaluated edit-policy refusal;
/// unavailable reports that the edit-policy decision could not be obtained and
/// may be retried. Both perform no storage access and carry empty values with
/// an empty revision. No outcome merges settings implicitly.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct UserReplaceResult {
    pub outcome: UserReplaceOutcome,
    pub snapshot: UserSnapshot,
}

/// Latest effective configuration, with an opaque cursor bound to provider
/// instance and explicit run overrides. snapshot carries a snapshot and new
/// cursor; unchanged carries the original cursor and no snapshot. Other
/// outcomes carry no snapshot and preserve the supplied cursor. Intermediate
/// revisions may be coalesced; this is not an event history. A restarted
/// provider or changed override binding gives gap and requires an explicit
/// empty-cursor restart.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ConfigObservation {
    pub outcome: ConfigObservationOutcome,
    pub cursor: String,
    pub snapshot: Option<Snapshot>,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
struct OAConfigReaderReadArguments {
    overrides: RunOverrides,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
struct OAConfigEditorReadUserArguments {
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
struct OAConfigEditorReplaceUserArguments {
    expected_revision: String,
    values: UserSettings,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
struct OAConfigObserverObserveArguments {
    overrides: RunOverrides,
    cursor: String,
    wait_ms: i64,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
struct OAServiceFrame {
    version: i32,
    service: String,
    method: String,
    arguments: Raw,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
struct OAServiceReply {
    version: i32,
    service: String,
    method: String,
    ok: bool,
    payload: Raw,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
struct OAServiceError {
    code: String,
    message: String,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
struct OAConfigReaderReadResult {
    value: Snapshot,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
struct OAConfigEditorReadUserResult {
    value: UserSnapshot,
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct OAConfigEditorReplaceUserResult {
    value: UserReplaceResult,
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct OAConfigObserverObserveResult {
    value: ConfigObservation,
}

fn enc_run_overrides(out: &mut Vec<u8>, v: &RunOverrides, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "nas_store");
    out.extend_from_slice(b": ");
    esc(out, &v.nas_store);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "store");
    out.extend_from_slice(b": ");
    esc(out, &v.store);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "log_sink");
    out.extend_from_slice(b": ");
    esc(out, &v.log_sink);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "log_service");
    out.extend_from_slice(b": ");
    esc(out, &v.log_service);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

fn enc_origin(out: &mut Vec<u8>, v: &Origin, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "rung");
    out.extend_from_slice(b": ");
    esc(out, &v.rung);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "path");
    out.extend_from_slice(b": ");
    esc(out, &v.path);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

fn enc_origins(out: &mut Vec<u8>, v: &Origins, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "nas_store");
    out.extend_from_slice(b": ");
    enc_origin(out, &v.nas_store, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "store");
    out.extend_from_slice(b": ");
    enc_origin(out, &v.store, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "log_sink");
    out.extend_from_slice(b": ");
    enc_origin(out, &v.log_sink, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "log_service");
    out.extend_from_slice(b": ");
    enc_origin(out, &v.log_service, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "off");
    out.extend_from_slice(b": ");
    enc_origin(out, &v.off, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

fn enc_snapshot(out: &mut Vec<u8>, v: &Snapshot, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "nas_store");
    out.extend_from_slice(b": ");
    esc(out, &v.nas_store);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "store");
    out.extend_from_slice(b": ");
    esc(out, &v.store);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "log_sink");
    out.extend_from_slice(b": ");
    esc(out, &v.log_sink);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "log_service");
    out.extend_from_slice(b": ");
    esc(out, &v.log_service);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "off");
    out.extend_from_slice(b": ");
    strmap(out, &v.off, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "origins");
    out.extend_from_slice(b": ");
    enc_origins(out, &v.origins, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "stamp");
    out.extend_from_slice(b": ");
    esc(out, &v.stamp);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

fn enc_user_settings(out: &mut Vec<u8>, v: &UserSettings, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "nas_store");
    out.extend_from_slice(b": ");
    esc(out, &v.nas_store);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "store");
    out.extend_from_slice(b": ");
    esc(out, &v.store);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "log_sink");
    out.extend_from_slice(b": ");
    esc(out, &v.log_sink);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "log_service");
    out.extend_from_slice(b": ");
    esc(out, &v.log_service);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "off");
    out.extend_from_slice(b": ");
    strmap(out, &v.off, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

fn enc_oa_config_reader_read_arguments(out: &mut Vec<u8>, v: &OAConfigReaderReadArguments, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "overrides");
    out.extend_from_slice(b": ");
    enc_run_overrides(out, &v.overrides, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

fn enc_oa_config_editor_read_user_arguments(out: &mut Vec<u8>, _v: &OAConfigEditorReadUserArguments, _depth: i32) {
    out.push(b'{');
    out.push(b'}');
}

fn enc_oa_config_editor_replace_user_arguments(out: &mut Vec<u8>, v: &OAConfigEditorReplaceUserArguments, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "expected_revision");
    out.extend_from_slice(b": ");
    esc(out, &v.expected_revision);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "values");
    out.extend_from_slice(b": ");
    enc_user_settings(out, &v.values, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

fn enc_oa_config_observer_observe_arguments(out: &mut Vec<u8>, v: &OAConfigObserverObserveArguments, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "overrides");
    out.extend_from_slice(b": ");
    enc_run_overrides(out, &v.overrides, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "cursor");
    out.extend_from_slice(b": ");
    esc(out, &v.cursor);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "wait_ms");
    out.extend_from_slice(b": ");
    num(out, v.wait_ms);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

fn enc_oa_service_frame(out: &mut Vec<u8>, v: &OAServiceFrame, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "version");
    out.extend_from_slice(b": ");
    num(out, i64::from(v.version));
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "service");
    out.extend_from_slice(b": ");
    esc(out, &v.service);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "method");
    out.extend_from_slice(b": ");
    esc(out, &v.method);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "arguments");
    out.extend_from_slice(b": ");
    out.extend_from_slice(&v.arguments);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn encode(v: &Snapshot) -> Vec<u8> {
    let mut out = Vec::new();
    enc_snapshot(&mut out, v, 0);
    out.push(b'\n');
    out
}

const DEPTH_LIMIT: i32 = 64;

#[derive(Debug)]
pub struct Refusal {
    pub word: &'static str,
    pub offset: usize,
}

impl std::fmt::Display for Refusal {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "refused: {} at byte {}", self.word, self.offset)
    }
}

impl std::error::Error for Refusal {}

fn append_rune(out: &mut Vec<u8>, cp: u32) {
    if cp < 0x80 {
        out.push(cp as u8);
    } else if cp < 0x800 {
        out.push(0xC0 | (cp >> 6) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    } else if cp < 0x10000 {
        out.push(0xE0 | (cp >> 12) as u8);
        out.push(0x80 | ((cp >> 6) & 0x3F) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    } else {
        out.push(0xF0 | (cp >> 18) as u8);
        out.push(0x80 | ((cp >> 12) & 0x3F) as u8);
        out.push(0x80 | ((cp >> 6) & 0x3F) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    }
}

struct Reader<'a> {
    buf: &'a [u8],
    pos: usize,
    depth: i32,
}

impl<'a> Reader<'a> {
    fn refuse<T>(&self, word: &'static str) -> Result<T, Refusal> {
        Err(Refusal { word, offset: self.pos })
    }

    fn at(&self) -> u8 {
        if self.pos < self.buf.len() { self.buf[self.pos] } else { 0 }
    }

    fn skip_ws(&mut self) {
        while self.pos < self.buf.len() && ws(self.buf[self.pos]) {
            self.pos += 1;
        }
    }

    fn enter(&mut self) -> Result<(), Refusal> {
        self.depth += 1;
        if self.depth > DEPTH_LIMIT {
            return self.refuse("depth_exceeded");
        }
        Ok(())
    }

    fn string(&mut self) -> Result<String, Refusal> {
        if self.at() != b'"' {
            return self.refuse("wrong_type");
        }
        self.pos += 1;
        let mut out: Vec<u8> = Vec::new();
        loop {
            if self.pos >= self.buf.len() {
                return self.refuse("malformed");
            }
            let c = self.buf[self.pos];
            if c == b'"' {
                self.pos += 1;
                return match String::from_utf8(out) {
                    Ok(s) => Ok(s),
                    Err(_) => self.refuse("bad_string"),
                };
            }
            if c < 0x20 {
                return self.refuse("bad_string");
            }
            if c == b'\\' {
                self.escape(&mut out)?;
            } else {
                out.push(c);
                self.pos += 1;
            }
        }
    }

    fn escape(&mut self, out: &mut Vec<u8>) -> Result<(), Refusal> {
        self.pos += 1;
        if self.pos >= self.buf.len() {
            return self.refuse("malformed");
        }
        let c = self.buf[self.pos];
        self.pos += 1;
        match c {
            b'"' | b'\\' | b'/' => out.push(c),
            b'b' => out.push(0x08),
            b'f' => out.push(0x0c),
            b'n' => out.push(b'\n'),
            b'r' => out.push(b'\r'),
            b't' => out.push(b'\t'),
            b'u' => {
                let mut u = self.hex4()?;
                if (0xDC00..=0xDFFF).contains(&u) {
                    return self.refuse("bad_string");
                }
                if (0xD800..=0xDBFF).contains(&u) {
                    if self.pos + 1 >= self.buf.len()
                        || self.buf[self.pos] != b'\\'
                        || self.buf[self.pos + 1] != b'u'
                    {
                        return self.refuse("bad_string");
                    }
                    self.pos += 2;
                    let low = self.hex4()?;
                    if !(0xDC00..=0xDFFF).contains(&low) {
                        return self.refuse("bad_string");
                    }
                    u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00);
                }
                append_rune(out, u);
            }
            _ => return self.refuse("bad_string"),
        }
        Ok(())
    }

    fn hex4(&mut self) -> Result<u32, Refusal> {
        if self.pos + 4 > self.buf.len() {
            return self.refuse("bad_string");
        }
        let mut u: u32 = 0;
        for i in 0..4 {
            let c = self.buf[self.pos + i];
            let d = match c {
                b'0'..=b'9' => c - b'0',
                b'a'..=b'f' => c - b'a' + 10,
                b'A'..=b'F' => c - b'A' + 10,
                _ => return self.refuse("bad_string"),
            };
            u = u << 4 | d as u32;
        }
        self.pos += 4;
        Ok(u)
    }

    fn integer(&mut self, low: i64, high: i64) -> Result<i64, Refusal> {
        let c = self.at();
        if c != b'-' && !c.is_ascii_digit() {
            return self.refuse("wrong_type");
        }
        let negative = c == b'-';
        if negative {
            self.pos += 1;
        }
        if !self.at().is_ascii_digit() {
            return self.refuse("malformed");
        }
        let mut u: u64 = 0;
        if self.at() == b'0' {
            self.pos += 1;
        } else {
            while self.at().is_ascii_digit() {
                if u > 922337203685477580 {
                    return self.refuse("number_spelling");
                }
                u = u * 10 + (self.at() - b'0') as u64;
                self.pos += 1;
            }
        }
        let after = self.at();
        if after == b'.' || after == b'e' || after == b'E' || after.is_ascii_digit() {
            return self.refuse("number_spelling");
        }
        if negative && u == 0 {
            return self.refuse("number_spelling");
        }
        let n = if negative {
            if u > 1u64 << 63 {
                return self.refuse("number_spelling");
            }
            if u == 1u64 << 63 { i64::MIN } else { -(u as i64) }
        } else {
            if u > i64::MAX as u64 {
                return self.refuse("number_spelling");
            }
            u as i64
        };
        if n < low || n > high {
            return self.refuse("number_spelling");
        }
        Ok(n)
    }

    fn boolean(&mut self) -> Result<bool, Refusal> {
        match self.at() {
            b't' => {
                self.literal(b"true")?;
                Ok(true)
            }
            b'f' => {
                self.literal(b"false")?;
                Ok(false)
            }
            _ => self.refuse("wrong_type"),
        }
    }

    fn literal(&mut self, word: &[u8]) -> Result<(), Refusal> {
        if self.pos + word.len() > self.buf.len() || &self.buf[self.pos..self.pos + word.len()] != word {
            return self.refuse("malformed");
        }
        self.pos += word.len();
        Ok(())
    }

    fn raw_value(&mut self) -> Result<Raw, Refusal> {
        let start = self.pos;
        self.skip_value()?;
        Ok(self.buf[start..self.pos].to_vec())
    }

    fn skip_value(&mut self) -> Result<(), Refusal> {
        let c = self.at();
        match c {
            b'"' => self.skip_string(),
            b'{' | b'[' => self.skip_container(),
            b't' => self.literal(b"true"),
            b'f' => self.literal(b"false"),
            b'n' => self.literal(b"null"),
            b'-' => self.skip_number(),
            _ if c.is_ascii_digit() => self.skip_number(),
            _ => self.refuse("malformed"),
        }
    }

    // An opaque value is validated and carried, never interpreted. Its syntax is
    // the record's own — the same string reader, so an escape, a control byte or
    // a lone surrogate is judged identically at any depth — and what it is free
    // to spell, it keeps: the bytes between these two offsets are what a writer
    // re-emits. A number is walked, never converted, so a value no host type
    // holds survives the reader that carried it.
    fn skip_string(&mut self) -> Result<(), Refusal> {
        self.string()?;
        Ok(())
    }

    fn some_digits(&mut self) -> Result<(), Refusal> {
        let mut n = 0;
        while self.at().is_ascii_digit() {
            self.pos += 1;
            n += 1;
        }
        if n == 0 {
            return self.refuse("number_spelling");
        }
        Ok(())
    }

    fn skip_number(&mut self) -> Result<(), Refusal> {
        if self.at() == b'-' {
            self.pos += 1;
        }
        match self.at() {
            b'0' => self.pos += 1,
            c if c.is_ascii_digit() => {
                while self.at().is_ascii_digit() {
                    self.pos += 1;
                }
            }
            _ => return self.refuse("number_spelling"),
        }
        if self.at() == b'.' {
            self.pos += 1;
            self.some_digits()?;
        }
        if self.at() == b'e' || self.at() == b'E' {
            self.pos += 1;
            if self.at() == b'+' || self.at() == b'-' {
                self.pos += 1;
            }
            self.some_digits()?;
        }
        Ok(())
    }

    fn skip_container(&mut self) -> Result<(), Refusal> {
        let opener = self.at();
        let shut = if opener == b'{' { b'}' } else { b']' };
        self.enter()?;
        self.pos += 1;
        self.skip_ws();
        if self.at() != shut {
            loop {
                self.skip_ws();
                if opener == b'{' {
                    if self.at() != b'"' {
                        return self.refuse("malformed");
                    }
                    self.string()?;
                    self.skip_ws();
                    if self.at() != b':' {
                        return self.refuse("malformed");
                    }
                    self.pos += 1;
                    self.skip_ws();
                }
                self.skip_value()?;
                self.skip_ws();
                if self.at() != b',' {
                    break;
                }
                self.pos += 1;
            }
        }
        if self.at() != shut {
            return self.refuse("malformed");
        }
        self.pos += 1;
        self.depth -= 1;
        Ok(())
    }
}

fn str_map(r: &mut Reader) -> Result<BTreeMap<String, String>, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut out = BTreeMap::new();
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let k = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            let v = r.string()?;
            out.insert(k, v);
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    Ok(out)
}

fn decode_run_overrides(r: &mut Reader) -> Result<RunOverrides, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_nas_store: String = Default::default();
    let mut field_store: String = Default::default();
    let mut field_log_sink: String = Default::default();
    let mut field_log_service: String = Default::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "nas_store" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_nas_store = r.string()?;
                }
                "store" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    field_store = r.string()?;
                }
                "log_sink" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    field_log_sink = r.string()?;
                }
                "log_service" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    field_log_service = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 15 != 15 {
        return r.refuse("missing_field");
    }
    Ok(RunOverrides {
        nas_store: field_nas_store,
        store: field_store,
        log_sink: field_log_sink,
        log_service: field_log_service,
    })
}

fn decode_origin(r: &mut Reader) -> Result<Origin, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_rung: String = Default::default();
    let mut field_path: String = Default::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "rung" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_rung = r.string()?;
                }
                "path" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    field_path = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(Origin {
        rung: field_rung,
        path: field_path,
    })
}

fn decode_origins(r: &mut Reader) -> Result<Origins, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_nas_store: Origin = Default::default();
    let mut field_store: Origin = Default::default();
    let mut field_log_sink: Origin = Default::default();
    let mut field_log_service: Origin = Default::default();
    let mut field_off: Origin = Default::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "nas_store" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_nas_store = decode_origin(r)?;
                }
                "store" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    field_store = decode_origin(r)?;
                }
                "log_sink" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    field_log_sink = decode_origin(r)?;
                }
                "log_service" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    field_log_service = decode_origin(r)?;
                }
                "off" => {
                    if seen & 16 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 16;
                    field_off = decode_origin(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 31 != 31 {
        return r.refuse("missing_field");
    }
    Ok(Origins {
        nas_store: field_nas_store,
        store: field_store,
        log_sink: field_log_sink,
        log_service: field_log_service,
        off: field_off,
    })
}

fn decode_snapshot(r: &mut Reader) -> Result<Snapshot, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_nas_store: String = Default::default();
    let mut field_store: String = Default::default();
    let mut field_log_sink: String = Default::default();
    let mut field_log_service: String = Default::default();
    let mut field_off: BTreeMap<String, String> = Default::default();
    let mut field_origins: Origins = Default::default();
    let mut field_stamp: String = Default::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "nas_store" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_nas_store = r.string()?;
                }
                "store" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    field_store = r.string()?;
                }
                "log_sink" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    field_log_sink = r.string()?;
                }
                "log_service" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    field_log_service = r.string()?;
                }
                "off" => {
                    if seen & 16 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 16;
                    field_off = str_map(r)?;
                }
                "origins" => {
                    if seen & 32 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 32;
                    field_origins = decode_origins(r)?;
                }
                "stamp" => {
                    if seen & 64 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 64;
                    field_stamp = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 127 != 127 {
        return r.refuse("missing_field");
    }
    Ok(Snapshot {
        nas_store: field_nas_store,
        store: field_store,
        log_sink: field_log_sink,
        log_service: field_log_service,
        off: field_off,
        origins: field_origins,
        stamp: field_stamp,
    })
}

fn decode_user_settings(r: &mut Reader) -> Result<UserSettings, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_nas_store: String = Default::default();
    let mut field_store: String = Default::default();
    let mut field_log_sink: String = Default::default();
    let mut field_log_service: String = Default::default();
    let mut field_off: BTreeMap<String, String> = Default::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "nas_store" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_nas_store = r.string()?;
                }
                "store" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    field_store = r.string()?;
                }
                "log_sink" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    field_log_sink = r.string()?;
                }
                "log_service" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    field_log_service = r.string()?;
                }
                "off" => {
                    if seen & 16 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 16;
                    field_off = str_map(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 31 != 31 {
        return r.refuse("missing_field");
    }
    Ok(UserSettings {
        nas_store: field_nas_store,
        store: field_store,
        log_sink: field_log_sink,
        log_service: field_log_service,
        off: field_off,
    })
}

fn decode_user_snapshot(r: &mut Reader) -> Result<UserSnapshot, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_values: UserSettings = Default::default();
    let mut field_revision: String = Default::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "values" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_values = decode_user_settings(r)?;
                }
                "revision" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    field_revision = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(UserSnapshot {
        values: field_values,
        revision: field_revision,
    })
}

fn decode_user_replace_result(r: &mut Reader) -> Result<UserReplaceResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_outcome: Option<String> = None;
    let mut field_snapshot: UserSnapshot = Default::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "outcome" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_outcome = Some(r.string()?);
                }
                "snapshot" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    field_snapshot = decode_user_snapshot(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    let Some(field_outcome) = field_outcome.as_deref().and_then(UserReplaceOutcome::from_wire) else {
        return r.refuse("bad_enum");
    };
    Ok(UserReplaceResult {
        outcome: field_outcome,
        snapshot: field_snapshot,
    })
}

fn decode_config_observation(r: &mut Reader) -> Result<ConfigObservation, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_outcome: Option<String> = None;
    let mut field_cursor: String = Default::default();
    let mut field_snapshot: Option<Snapshot> = None;
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "outcome" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_outcome = Some(r.string()?);
                }
                "cursor" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    field_cursor = r.string()?;
                }
                "snapshot" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    field_snapshot = Some(decode_snapshot(r)?);
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    let Some(field_outcome) = field_outcome.as_deref().and_then(ConfigObservationOutcome::from_wire) else {
        return r.refuse("bad_enum");
    };
    Ok(ConfigObservation {
        outcome: field_outcome,
        cursor: field_cursor,
        snapshot: field_snapshot,
    })
}

fn decode_oa_config_reader_read_arguments(r: &mut Reader) -> Result<OAConfigReaderReadArguments, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_overrides: RunOverrides = Default::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "overrides" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_overrides = decode_run_overrides(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(OAConfigReaderReadArguments {
        overrides: field_overrides,
    })
}

fn decode_oa_config_editor_read_user_arguments(r: &mut Reader) -> Result<OAConfigEditorReadUserArguments, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    r.skip_ws();
    if r.at() != b'}' {
        if r.at() != b'"' {
            return r.refuse("malformed");
        }
        r.string()?;
        r.skip_ws();
        if r.at() != b':' {
            return r.refuse("malformed");
        }
        return r.refuse("unknown_field");
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    Ok(OAConfigEditorReadUserArguments {})
}

fn decode_oa_config_editor_replace_user_arguments(r: &mut Reader) -> Result<OAConfigEditorReplaceUserArguments, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_expected_revision: String = Default::default();
    let mut field_values: UserSettings = Default::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "expected_revision" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_expected_revision = r.string()?;
                }
                "values" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    field_values = decode_user_settings(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(OAConfigEditorReplaceUserArguments {
        expected_revision: field_expected_revision,
        values: field_values,
    })
}

fn decode_oa_config_observer_observe_arguments(r: &mut Reader) -> Result<OAConfigObserverObserveArguments, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_overrides: RunOverrides = Default::default();
    let mut field_cursor: String = Default::default();
    let mut field_wait_ms: i64 = Default::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "overrides" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_overrides = decode_run_overrides(r)?;
                }
                "cursor" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    field_cursor = r.string()?;
                }
                "wait_ms" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    field_wait_ms = r.integer(i64::MIN, i64::MAX)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 7 != 7 {
        return r.refuse("missing_field");
    }
    Ok(OAConfigObserverObserveArguments {
        overrides: field_overrides,
        cursor: field_cursor,
        wait_ms: field_wait_ms,
    })
}

fn decode_oa_service_frame(r: &mut Reader) -> Result<OAServiceFrame, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_version: i32 = Default::default();
    let mut field_service: String = Default::default();
    let mut field_method: String = Default::default();
    let mut field_arguments: Raw = Default::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "version" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_version = r.integer(-2147483648, 2147483647)? as i32;
                }
                "service" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    field_service = r.string()?;
                }
                "method" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    field_method = r.string()?;
                }
                "arguments" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    field_arguments = r.raw_value()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 15 != 15 {
        return r.refuse("missing_field");
    }
    Ok(OAServiceFrame {
        version: field_version,
        service: field_service,
        method: field_method,
        arguments: field_arguments,
    })
}

fn decode_oa_service_reply(r: &mut Reader) -> Result<OAServiceReply, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_version: i32 = Default::default();
    let mut field_service: String = Default::default();
    let mut field_method: String = Default::default();
    let mut field_ok: bool = Default::default();
    let mut field_payload: Raw = Default::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "version" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_version = r.integer(-2147483648, 2147483647)? as i32;
                }
                "service" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    field_service = r.string()?;
                }
                "method" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    field_method = r.string()?;
                }
                "ok" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    field_ok = r.boolean()?;
                }
                "payload" => {
                    if seen & 16 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 16;
                    field_payload = r.raw_value()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 31 != 31 {
        return r.refuse("missing_field");
    }
    Ok(OAServiceReply {
        version: field_version,
        service: field_service,
        method: field_method,
        ok: field_ok,
        payload: field_payload,
    })
}

fn decode_oa_service_error(r: &mut Reader) -> Result<OAServiceError, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_code: String = Default::default();
    let mut field_message: String = Default::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "code" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_code = r.string()?;
                }
                "message" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    field_message = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(OAServiceError {
        code: field_code,
        message: field_message,
    })
}

fn decode_oa_config_reader_read_result(r: &mut Reader) -> Result<OAConfigReaderReadResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_value: Snapshot = Default::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "value" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_value = decode_snapshot(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(OAConfigReaderReadResult {
        value: field_value,
    })
}

fn decode_oa_config_editor_read_user_result(r: &mut Reader) -> Result<OAConfigEditorReadUserResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_value: UserSnapshot = Default::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "value" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_value = decode_user_snapshot(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(OAConfigEditorReadUserResult {
        value: field_value,
    })
}

fn decode_oa_config_editor_replace_user_result(r: &mut Reader) -> Result<OAConfigEditorReplaceUserResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_value: Option<UserReplaceResult> = None;
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "value" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_value = Some(decode_user_replace_result(r)?);
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    let Some(field_value) = field_value else {
        return r.refuse("missing_field");
    };
    Ok(OAConfigEditorReplaceUserResult {
        value: field_value,
    })
}

fn decode_oa_config_observer_observe_result(r: &mut Reader) -> Result<OAConfigObserverObserveResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_value: Option<ConfigObservation> = None;
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "value" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_value = Some(decode_config_observation(r)?);
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    let Some(field_value) = field_value else {
        return r.refuse("missing_field");
    };
    Ok(OAConfigObserverObserveResult {
        value: field_value,
    })
}

pub fn decode(data: &[u8]) -> Result<Snapshot, Refusal> {
    let mut r = Reader { buf: data, pos: 0, depth: 0 };
    r.skip_ws();
    let v = decode_snapshot(&mut r)?;
    r.skip_ws();
    if r.pos < r.buf.len() {
        return r.refuse("trailing_bytes");
    }
    Ok(v)
}

fn service_check_run_overrides(_v: &RunOverrides) -> Result<(), Refusal> {
    Ok(())
}

fn service_check_user_settings(_v: &UserSettings) -> Result<(), Refusal> {
    Ok(())
}

fn service_check_oa_config_reader_read_arguments(v: &OAConfigReaderReadArguments) -> Result<(), Refusal> {
    service_check_run_overrides(&v.overrides)?;
    Ok(())
}

fn service_check_oa_config_editor_read_user_arguments(_v: &OAConfigEditorReadUserArguments) -> Result<(), Refusal> {
    Ok(())
}

fn service_check_oa_config_editor_replace_user_arguments(v: &OAConfigEditorReplaceUserArguments) -> Result<(), Refusal> {
    service_check_user_settings(&v.values)?;
    Ok(())
}

fn service_check_oa_config_observer_observe_arguments(v: &OAConfigObserverObserveArguments) -> Result<(), Refusal> {
    service_check_run_overrides(&v.overrides)?;
    Ok(())
}

fn service_check_oa_service_frame(_v: &OAServiceFrame) -> Result<(), Refusal> {
    Ok(())
}

/// Common generated framing boundary; implementation owns waiting and identity.
pub use abstraction_frame::FrameTransport;

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ServiceError {
    pub code: String,
    pub message: String,
}

#[derive(Debug)]
pub enum CallError<E> {
    /// Transport failure does not establish whether the receiver accepted work.
    Transport(E),
    Refusal(Refusal),
    Dispatch(&'static str),
    Service(ServiceError),
}

fn service_decode<T>(data: &[u8], decode: fn(&mut Reader) -> Result<T, Refusal>) -> Result<T, Refusal> {
    let mut r = Reader { buf: data, pos: 0, depth: 0 };
    r.skip_ws();
    let value = decode(&mut r)?;
    r.skip_ws();
    if r.pos != data.len() {
        return r.refuse("trailing_bytes");
    }
    Ok(value)
}

fn service_encode<T>(value: &T, check: fn(&T) -> Result<(), Refusal>, encode: fn(&mut Vec<u8>, &T, i32), decode: fn(&mut Reader) -> Result<T, Refusal>) -> Result<Vec<u8>, Refusal> {
    check(value)?;
    let mut data = Vec::new();
    encode(&mut data, value, 0);
    service_decode(&data, decode)?;
    Ok(data)
}

/// Per-user configuration read service. Caller identity is checked
/// independently of overrides.
pub trait ConfigReader {
    type Error;
    /// Read same-user machine/user configuration with explicit caller run
    /// overrides. No writes, watch or provider fallback.
    fn read(&self, overrides: RunOverrides) -> Result<Snapshot, Self::Error>;
}

pub struct ConfigReaderClient<T> {
    transport: T,
}

impl<T> ConfigReaderClient<T> {
    pub fn new(transport: T) -> Self {
        Self { transport }
    }

    pub fn transport(&self) -> &T {
        &self.transport
    }
}

impl<T: FrameTransport> ConfigReader for ConfigReaderClient<T> {
    type Error = CallError<T::Error>;
    fn read(&self, overrides: RunOverrides) -> Result<Snapshot, Self::Error> {
        let args = OAConfigReaderReadArguments { overrides };
        let arguments = service_encode(&args, service_check_oa_config_reader_read_arguments, enc_oa_config_reader_read_arguments, decode_oa_config_reader_read_arguments).map_err(CallError::Refusal)?;
        let request = OAServiceFrame { version: 1, service: "abstraction.config/reader@1".into(), method: "Read".into(), arguments };
        let frame = service_encode(&request, service_check_oa_service_frame, enc_oa_service_frame, decode_oa_service_frame).map_err(CallError::Refusal)?;
        let reply = self.transport.exchange_frame(&frame).map_err(CallError::Transport)?;
        let reply = service_decode(&reply, decode_oa_service_reply).map_err(CallError::Refusal)?;
        if reply.version != 1 {
            return Err(CallError::Dispatch("unknown_version"));
        }
        if reply.service != "abstraction.config/reader@1" || reply.method != "Read" {
            return Err(CallError::Dispatch("mismatched_response"));
        }
        if !reply.ok {
            let error = service_decode(&reply.payload, decode_oa_service_error).map_err(CallError::Refusal)?;
            if error.code.is_empty() {
                return Err(CallError::Dispatch("invalid_error"));
            }
            return Err(CallError::Service(ServiceError { code: error.code, message: error.message }));
        }
        let result = service_decode(&reply.payload, decode_oa_config_reader_read_result).map_err(CallError::Refusal)?;
        Ok(result.value)
    }
}

/// Same-account Program-proven user editor on the config endpoint. The service
/// selects its private user path once. Caller claims cannot grant authority;
/// forbidden callers cause no storage access. Existing machine and run rungs
/// are unaffected.
pub trait ConfigEditor {
    type Error;
    /// Read only the authenticated service user's persisted rung. No
    /// environment or machine merge. Missing storage is empty; corrupt,
    /// unsupported or unavailable storage returns storage_unavailable.
    fn read_user(&self) -> Result<UserSnapshot, Self::Error>;
    /// Compare the opaque revision and replace atomically through the selected
    /// conditional-write store. Stale revision returns conflict. Empty revision
    /// is invalid_revision. Storage failures return storage_unavailable. A
    /// configured edit policy is evaluated after same-account proof and before
    /// storage access: refusal returns forbidden and a failed decision returns
    /// unavailable. A canceled wait leaves write outcome unresolved; reread
    /// rather than blindly retry.
    fn replace_user(&self, expected_revision: String, values: UserSettings) -> Result<UserReplaceResult, Self::Error>;
}

pub struct ConfigEditorClient<T> {
    transport: T,
}

impl<T> ConfigEditorClient<T> {
    pub fn new(transport: T) -> Self {
        Self { transport }
    }

    pub fn transport(&self) -> &T {
        &self.transport
    }
}

impl<T: FrameTransport> ConfigEditor for ConfigEditorClient<T> {
    type Error = CallError<T::Error>;
    fn read_user(&self) -> Result<UserSnapshot, Self::Error> {
        let args = OAConfigEditorReadUserArguments {};
        let arguments = service_encode(&args, service_check_oa_config_editor_read_user_arguments, enc_oa_config_editor_read_user_arguments, decode_oa_config_editor_read_user_arguments).map_err(CallError::Refusal)?;
        let request = OAServiceFrame { version: 1, service: "abstraction.config/editor@1".into(), method: "ReadUser".into(), arguments };
        let frame = service_encode(&request, service_check_oa_service_frame, enc_oa_service_frame, decode_oa_service_frame).map_err(CallError::Refusal)?;
        let reply = self.transport.exchange_frame(&frame).map_err(CallError::Transport)?;
        let reply = service_decode(&reply, decode_oa_service_reply).map_err(CallError::Refusal)?;
        if reply.version != 1 {
            return Err(CallError::Dispatch("unknown_version"));
        }
        if reply.service != "abstraction.config/editor@1" || reply.method != "ReadUser" {
            return Err(CallError::Dispatch("mismatched_response"));
        }
        if !reply.ok {
            let error = service_decode(&reply.payload, decode_oa_service_error).map_err(CallError::Refusal)?;
            if error.code.is_empty() {
                return Err(CallError::Dispatch("invalid_error"));
            }
            return Err(CallError::Service(ServiceError { code: error.code, message: error.message }));
        }
        let result = service_decode(&reply.payload, decode_oa_config_editor_read_user_result).map_err(CallError::Refusal)?;
        Ok(result.value)
    }

    fn replace_user(&self, expected_revision: String, values: UserSettings) -> Result<UserReplaceResult, Self::Error> {
        let args = OAConfigEditorReplaceUserArguments { expected_revision, values };
        let arguments = service_encode(&args, service_check_oa_config_editor_replace_user_arguments, enc_oa_config_editor_replace_user_arguments, decode_oa_config_editor_replace_user_arguments).map_err(CallError::Refusal)?;
        let request = OAServiceFrame { version: 1, service: "abstraction.config/editor@1".into(), method: "ReplaceUser".into(), arguments };
        let frame = service_encode(&request, service_check_oa_service_frame, enc_oa_service_frame, decode_oa_service_frame).map_err(CallError::Refusal)?;
        let reply = self.transport.exchange_frame(&frame).map_err(CallError::Transport)?;
        let reply = service_decode(&reply, decode_oa_service_reply).map_err(CallError::Refusal)?;
        if reply.version != 1 {
            return Err(CallError::Dispatch("unknown_version"));
        }
        if reply.service != "abstraction.config/editor@1" || reply.method != "ReplaceUser" {
            return Err(CallError::Dispatch("mismatched_response"));
        }
        if !reply.ok {
            let error = service_decode(&reply.payload, decode_oa_service_error).map_err(CallError::Refusal)?;
            if error.code.is_empty() {
                return Err(CallError::Dispatch("invalid_error"));
            }
            return Err(CallError::Service(ServiceError { code: error.code, message: error.message }));
        }
        let result = service_decode(&reply.payload, decode_oa_config_editor_replace_user_result).map_err(CallError::Refusal)?;
        Ok(result.value)
    }
}

/// Same-account latest-snapshot long-poll observation over a provider's
/// explicit change notification source.
pub trait ConfigObserver {
    type Error;
    /// Empty cursor reads the current snapshot. At the same revision, wait at
    /// most wait_ms (0..30000) for provider invalidation; reread on expiry.
    /// Cursor is at most 512 UTF-8 bytes and each override at most 4096 bytes.
    /// A slow consumer receives the latest revision; revisions include values
    /// and provenance. Missing change notification support gives unsupported.
    /// Bounded waiter exhaustion or provider notification failure gives
    /// unavailable. Caller cancellation stops observation waiting only; setting
    /// mutations retain their own lifetimes. Receiving account authority is
    /// rechecked before returning data.
    fn observe(&self, overrides: RunOverrides, cursor: String, wait_ms: i64) -> Result<ConfigObservation, Self::Error>;
}

pub struct ConfigObserverClient<T> {
    transport: T,
}

impl<T> ConfigObserverClient<T> {
    pub fn new(transport: T) -> Self {
        Self { transport }
    }

    pub fn transport(&self) -> &T {
        &self.transport
    }
}

impl<T: FrameTransport> ConfigObserver for ConfigObserverClient<T> {
    type Error = CallError<T::Error>;
    fn observe(&self, overrides: RunOverrides, cursor: String, wait_ms: i64) -> Result<ConfigObservation, Self::Error> {
        let args = OAConfigObserverObserveArguments { overrides, cursor, wait_ms };
        let arguments = service_encode(&args, service_check_oa_config_observer_observe_arguments, enc_oa_config_observer_observe_arguments, decode_oa_config_observer_observe_arguments).map_err(CallError::Refusal)?;
        let request = OAServiceFrame { version: 1, service: "abstraction.config/observer@1".into(), method: "Observe".into(), arguments };
        let frame = service_encode(&request, service_check_oa_service_frame, enc_oa_service_frame, decode_oa_service_frame).map_err(CallError::Refusal)?;
        let reply = self.transport.exchange_frame(&frame).map_err(CallError::Transport)?;
        let reply = service_decode(&reply, decode_oa_service_reply).map_err(CallError::Refusal)?;
        if reply.version != 1 {
            return Err(CallError::Dispatch("unknown_version"));
        }
        if reply.service != "abstraction.config/observer@1" || reply.method != "Observe" {
            return Err(CallError::Dispatch("mismatched_response"));
        }
        if !reply.ok {
            let error = service_decode(&reply.payload, decode_oa_service_error).map_err(CallError::Refusal)?;
            if error.code.is_empty() {
                return Err(CallError::Dispatch("invalid_error"));
            }
            return Err(CallError::Service(ServiceError { code: error.code, message: error.message }));
        }
        let result = service_decode(&reply.payload, decode_oa_config_observer_observe_result).map_err(CallError::Refusal)?;
        Ok(result.value)
    }
}
